// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package container

import (
	"context"
	"example/bootstrap"
	"example/internal/client"
	"example/internal/helper"
	"example/internal/input/application/command"
	"example/internal/input/application/command/admin/authentication"
	"example/internal/input/application/command/admin/resource"
	"example/internal/input/application/cron"
	"example/internal/input/application/cron/admin/authentication"
	"example/internal/input/application/cron/admin/resource"
	"example/internal/input/application/daemon"
	"example/internal/input/application/daemon/watcher/source"
	"example/internal/input/application/facade"
	"example/internal/input/application/facade/admin/authentication"
	"example/internal/input/application/facade/admin/resource"
	"example/internal/input/application/facade/register"
	"example/internal/input/application/facade/table"
	"example/internal/input/application/http"
	"example/internal/input/application/http/admin/authentication"
	"example/internal/input/application/http/admin/option"
	"example/internal/input/application/http/admin/resource"
	"example/internal/input/application/http/game/authentication"
	"example/internal/input/application/rabbitmq"
	"example/internal/input/application/rabbitmq/admin/resource"
	"example/internal/input/application/resource"
	"example/internal/input/application/resource/event"
	"example/internal/input/application/resource/logic"
	"example/internal/input/application/resource/model"
	"example/internal/input/application/source"
	"example/internal/input/application/source/announcement"
	"example/internal/input/application/tcp"
	"example/internal/input/application/tcp/admin/authentication"
	"example/internal/input/application/websocket"
	"example/internal/input/application/websocket/admin/authentication"
	"example/internal/interceptor/facade/admin"
	"example/internal/interceptor/facade/game"
	"example/internal/interceptor/resource/logic"
	"example/internal/interceptor/resource/model"
	"example/internal/middleware/http/admin"
	"example/internal/middleware/http/game"
	"example/internal/middleware/http/table"
	"example/internal/middleware/websocket/admin"
	"example/internal/output/application/cache"
	"example/internal/output/application/cache/model"
	"example/internal/output/application/memory"
	"example/internal/output/application/memory/model"
	"example/internal/output/application/mysql"
	"example/internal/output/application/mysql/logic"
	"example/internal/output/application/mysql/model"
	"example/internal/output/application/rabbitmq"
	"example/internal/output/application/rabbitmq/event"
	"example/internal/output/application/resource"
	"example/internal/output/application/resource/logic"
	"example/internal/output/application/resource/model"
	"example/internal/output/port/any/event"
	"example/internal/usecase/application/any/admin"
	"example/internal/usecase/application/any/admin/authentication"
	"example/internal/usecase/application/any/admin/option"
	"example/internal/usecase/application/any/admin/resource"
	"example/internal/usecase/application/any/annoucement"
	"example/internal/usecase/application/any/event"
	"example/internal/usecase/application/any/game"
	"example/internal/usecase/application/any/game/authentication"
	"example/internal/usecase/application/any/logic"
	"example/internal/usecase/application/any/model"
	"example/internal/usecase/application/any/watcher"
	"example/internal/usecase/application/any/watcher/source"
	"example/internal/usecase/port/any/model"
	"example/pkg/cache"
	"example/pkg/gin"
	"example/pkg/nats"
	"example/pkg/utility"
	"github.com/nats-io/nats.go"
)

// Injectors from wire.go:

func InitHttpContainer(ctx context.Context) (*HttpContainer, error) {
	response := pkgGin.NewResponse()
	clock, err := pkgUtility.NewClock(ctx)
	if err != nil {
		return nil, err
	}
	abstractHelper := helper.NewAbstractHelper()
	aesHelper := helper.NewAesHelper(abstractHelper)
	rsaHelper := helper.NewRsaHelper(abstractHelper)
	jwtHelper := helper.NewJwtHelper(abstractHelper)
	clientConn := bootstrap.NewResource(ctx)
	model := client.NewModel(clientConn)
	logic := client.NewLogic(clientConn)
	event := client.NewEvent(clientConn)
	resourceClient := client.NewResourceClient(clientConn, model, logic, event)
	abstractHandler := inputApplicationHttp.NewAbstractHandler(response, aesHelper, jwtHelper)
	abstractResource := outputApplicationResource.NewAbstractResource(ctx, resourceClient)
	adminUserModel := outputApplicationResourceModel.NewAdminUserModel(abstractResource)
	abstractUsecase := usecaseApplicationAnyAdmin.NewAbstractUsecase(aesHelper, jwtHelper)
	authenticatorUsecase := usecaseApplicationAnyAdminAuthentication.NewAuthenticatorUsecase(adminUserModel, abstractUsecase)
	authenticatorHandler := inputApplicationHttpAdminAuthentication.NewAuthenticatorHandler(abstractHandler, authenticatorUsecase)
	gameModel := outputApplicationResourceModel.NewGameModel(abstractResource)
	gameLogic := outputApplicationResourceLogic.NewGameLogic(abstractResource)
	gameUsecase := usecaseApplicationAnyAdminResource.NewGameUsecase(gameModel, gameLogic, abstractUsecase)
	gameHandler := inputApplicationHttpAdminResource.NewGameHandler(abstractHandler, gameUsecase)
	tableModel := outputApplicationResourceModel.NewTableModel(abstractResource)
	tableLogic := outputApplicationResourceLogic.NewTableLogic(abstractResource)
	tableUsecase := usecaseApplicationAnyAdminResource.NewTableUsecase(tableModel, tableLogic, abstractUsecase)
	tableHandler := inputApplicationHttpAdminResource.NewTableHandler(abstractHandler, tableUsecase)
	adminUserUsecase := usecaseApplicationAnyAdminResource.NewAdminUserUsecase(adminUserModel, abstractUsecase)
	adminUserHandler := inputApplicationHttpAdminResource.NewAdminUserHandler(abstractHandler, adminUserUsecase)
	adminRoleModel := outputApplicationResourceModel.NewAdminRoleModel(abstractResource)
	adminRoleUsecase := usecaseApplicationAnyAdminResource.NewAdminRoleUsecase(adminRoleModel, abstractUsecase)
	adminRoleHandler := inputApplicationHttpAdminResource.NewAdminRoleHandler(abstractHandler, adminRoleUsecase)
	gameTypeModel := outputApplicationResourceModel.NewGameTypeModel(abstractResource)
	gameTypeLogic := outputApplicationResourceLogic.NewGameTypeLogic(abstractResource)
	gameTypeUsecase := usecaseApplicationAnyAdminResource.NewGameTypeUsecase(gameTypeModel, gameTypeLogic, gameModel, abstractUsecase)
	gameTypeHandler := inputApplicationHttpAdminResource.NewGameTypeHandler(abstractHandler, gameTypeUsecase)
	usecasePortAnyAdminOptionGameTypeUsecase := usecaseApplicationAnyAdminOption.NewGameTypeUsecase(gameTypeModel, gameTypeLogic, abstractUsecase)
	inputApplicationHttpAdminOptionGameTypeHandler := inputApplicationHttpAdminOption.NewGameTypeHandler(abstractHandler, usecasePortAnyAdminOptionGameTypeUsecase)
	appUserModel := outputApplicationResourceModel.NewAppUserModel(abstractResource)
	usecaseApplicationAnyGameAbstractUsecase := usecaseApplicationAnyGame.NewAbstractUsecase(aesHelper, jwtHelper)
	usecasePortAnyGameAuthenticationAuthenticatorUsecase := usecaseApplicationAnyGameAuthentication.NewAuthenticatorUsecase(appUserModel, usecaseApplicationAnyGameAbstractUsecase)
	inputApplicationHttpGameAuthenticationAuthenticatorHandler := inputApplicationHttpGameAuthentication.NewAuthenticatorHandler(abstractHandler, usecasePortAnyGameAuthenticationAuthenticatorUsecase)
	abstractMiddleware := middlewareHttpAdmin.NewAbstractMiddleware(response, clock, rsaHelper, aesHelper, jwtHelper)
	adminMiddleware := middlewareHttpAdmin.NewAdminMiddleware(abstractMiddleware)
	authenticationMiddleware := middlewareHttpAdmin.NewAuthenticationMiddleware(abstractMiddleware)
	decryptionMiddleware := middlewareHttpAdmin.NewDecryptionMiddleware(abstractMiddleware)
	encryptionMiddleware := middlewareHttpAdmin.NewEncryptionMiddleware(abstractMiddleware)
	errorMiddleware := middlewareHttpAdmin.NewErrorMiddleware(abstractMiddleware)
	loggerMiddleware := middlewareHttpAdmin.NewLoggerMiddleware(abstractMiddleware)
	nonexistentMiddleware := middlewareHttpAdmin.NewNonexistentMiddleware(abstractMiddleware)
	requestMiddleware := middlewareHttpAdmin.NewRequestMiddleware(abstractMiddleware)
	responseMiddleware := middlewareHttpAdmin.NewResponseMiddleware(abstractMiddleware)
	signatureMiddleware := middlewareHttpAdmin.NewSignatureMiddleware(abstractMiddleware)
	middlewareHttpTableAbstractMiddleware := middlewareHttpTable.NewAbstractMiddleware(response, clock, rsaHelper, aesHelper, jwtHelper)
	tableMiddleware := middlewareHttpTable.NewTableMiddleware(middlewareHttpTableAbstractMiddleware)
	middlewareHttpTableAuthenticationMiddleware := middlewareHttpTable.NewAuthenticationMiddleware(middlewareHttpTableAbstractMiddleware)
	middlewareHttpTableDecryptionMiddleware := middlewareHttpTable.NewDecryptionMiddleware(middlewareHttpTableAbstractMiddleware)
	middlewareHttpTableEncryptionMiddleware := middlewareHttpTable.NewEncryptionMiddleware(middlewareHttpTableAbstractMiddleware)
	middlewareHttpTableErrorMiddleware := middlewareHttpTable.NewErrorMiddleware(middlewareHttpTableAbstractMiddleware)
	middlewareHttpTableLoggerMiddleware := middlewareHttpTable.NewLoggerMiddleware(middlewareHttpTableAbstractMiddleware)
	middlewareHttpTableNonexistentMiddleware := middlewareHttpTable.NewNonexistentMiddleware(middlewareHttpTableAbstractMiddleware)
	middlewareHttpTableRequestMiddleware := middlewareHttpTable.NewRequestMiddleware(middlewareHttpTableAbstractMiddleware)
	middlewareHttpTableResponseMiddleware := middlewareHttpTable.NewResponseMiddleware(middlewareHttpTableAbstractMiddleware)
	middlewareHttpTableSignatureMiddleware := middlewareHttpTable.NewSignatureMiddleware(middlewareHttpTableAbstractMiddleware)
	middlewareHttpGameAbstractMiddleware := middlewareHttpGame.NewAbstractMiddleware(response, clock, rsaHelper, aesHelper, jwtHelper)
	gameMiddleware := middlewareHttpGame.NewGameMiddleware(middlewareHttpGameAbstractMiddleware)
	middlewareHttpGameAuthenticationMiddleware := middlewareHttpGame.NewAuthenticationMiddleware(middlewareHttpGameAbstractMiddleware)
	middlewareHttpGameDecryptionMiddleware := middlewareHttpGame.NewDecryptionMiddleware(middlewareHttpGameAbstractMiddleware)
	middlewareHttpGameEncryptionMiddleware := middlewareHttpGame.NewEncryptionMiddleware(middlewareHttpGameAbstractMiddleware)
	middlewareHttpGameErrorMiddleware := middlewareHttpGame.NewErrorMiddleware(middlewareHttpGameAbstractMiddleware)
	middlewareHttpGameLoggerMiddleware := middlewareHttpGame.NewLoggerMiddleware(middlewareHttpGameAbstractMiddleware)
	middlewareHttpGameNonexistentMiddleware := middlewareHttpGame.NewNonexistentMiddleware(middlewareHttpGameAbstractMiddleware)
	middlewareHttpGameRequestMiddleware := middlewareHttpGame.NewRequestMiddleware(middlewareHttpGameAbstractMiddleware)
	middlewareHttpGameResponseMiddleware := middlewareHttpGame.NewResponseMiddleware(middlewareHttpGameAbstractMiddleware)
	middlewareHttpGameSignatureMiddleware := middlewareHttpGame.NewSignatureMiddleware(middlewareHttpGameAbstractMiddleware)
	httpContainer := &HttpContainer{
		Response:                             response,
		Clock:                                clock,
		AbstractHelper:                       abstractHelper,
		AesHelper:                            aesHelper,
		RsaHelper:                            rsaHelper,
		JwtHelper:                            jwtHelper,
		ResourceClient:                       resourceClient,
		HttpAdminAuthenticationAuthenticator: authenticatorHandler,
		HttpAdminResourceGame:                gameHandler,
		HttpAdminResourceTable:               tableHandler,
		HttpAdminResourceAdminUser:           adminUserHandler,
		HttpAdminResourceAdminRole:           adminRoleHandler,
		HttpAdminResourceGameType:            gameTypeHandler,
		HttpAdminOptionGameType:              inputApplicationHttpAdminOptionGameTypeHandler,
		HttpGameAuthenticationAuthenticator:  inputApplicationHttpGameAuthenticationAuthenticatorHandler,
		HttpAdminAbstractMiddleware:          abstractMiddleware,
		HttpAdminAdminMiddleware:             adminMiddleware,
		HttpAdminAuthenticationMiddleware:    authenticationMiddleware,
		HttpAdminDecryptionMiddleware:        decryptionMiddleware,
		HttpAdminEncryptionMiddleware:        encryptionMiddleware,
		HttpAdminErrorMiddleware:             errorMiddleware,
		HttpAdminLoggerMiddleware:            loggerMiddleware,
		HttpAdminNonexistentMiddleware:       nonexistentMiddleware,
		HttpAdminRequestMiddleware:           requestMiddleware,
		HttpAdminResponseMiddleware:          responseMiddleware,
		HttpAdminSignatureMiddleware:         signatureMiddleware,
		HttpTableAbstractMiddleware:          middlewareHttpTableAbstractMiddleware,
		HttpTableTableMiddleware:             tableMiddleware,
		HttpTableAuthenticationMiddleware:    middlewareHttpTableAuthenticationMiddleware,
		HttpTableDecryptionMiddleware:        middlewareHttpTableDecryptionMiddleware,
		HttpTableEncryptionMiddleware:        middlewareHttpTableEncryptionMiddleware,
		HttpTableErrorMiddleware:             middlewareHttpTableErrorMiddleware,
		HttpTableLoggerMiddleware:            middlewareHttpTableLoggerMiddleware,
		HttpTableNonexistentMiddleware:       middlewareHttpTableNonexistentMiddleware,
		HttpTableRequestMiddleware:           middlewareHttpTableRequestMiddleware,
		HttpTableResponseMiddleware:          middlewareHttpTableResponseMiddleware,
		HttpTableSignatureMiddleware:         middlewareHttpTableSignatureMiddleware,
		HttpGameAbstractMiddleware:           middlewareHttpGameAbstractMiddleware,
		HttpGameGameMiddleware:               gameMiddleware,
		HttpGameAuthenticationMiddleware:     middlewareHttpGameAuthenticationMiddleware,
		HttpGameDecryptionMiddleware:         middlewareHttpGameDecryptionMiddleware,
		HttpGameEncryptionMiddleware:         middlewareHttpGameEncryptionMiddleware,
		HttpGameErrorMiddleware:              middlewareHttpGameErrorMiddleware,
		HttpGameLoggerMiddleware:             middlewareHttpGameLoggerMiddleware,
		HttpGameNonexistentMiddleware:        middlewareHttpGameNonexistentMiddleware,
		HttpGameRequestMiddleware:            middlewareHttpGameRequestMiddleware,
		HttpGameResponseMiddleware:           middlewareHttpGameResponseMiddleware,
		HttpGameSignatureMiddleware:          middlewareHttpGameSignatureMiddleware,
	}
	return httpContainer, nil
}

func InitFacadeContainer(ctx context.Context) (*FacadeContainer, error) {
	clock, err := pkgUtility.NewClock(ctx)
	if err != nil {
		return nil, err
	}
	abstractHelper := helper.NewAbstractHelper()
	aesHelper := helper.NewAesHelper(abstractHelper)
	rsaHelper := helper.NewRsaHelper(abstractHelper)
	jwtHelper := helper.NewJwtHelper(abstractHelper)
	clientConn := bootstrap.NewResource(ctx)
	model := client.NewModel(clientConn)
	logic := client.NewLogic(clientConn)
	event := client.NewEvent(clientConn)
	resourceClient := client.NewResourceClient(clientConn, model, logic, event)
	abstractHandler := inputApplicationFacade.NewAbstractHandler(aesHelper)
	scannerHandler := inputApplicationFacadeTable.NewScannerHandler(abstractHandler)
	authenticatorHandler := inputApplicationFacadeRegister.NewAuthenticatorHandler(abstractHandler)
	abstractResource := outputApplicationResource.NewAbstractResource(ctx, resourceClient)
	adminUserModel := outputApplicationResourceModel.NewAdminUserModel(abstractResource)
	abstractUsecase := usecaseApplicationAnyAdmin.NewAbstractUsecase(aesHelper, jwtHelper)
	authenticatorUsecase := usecaseApplicationAnyAdminAuthentication.NewAuthenticatorUsecase(adminUserModel, abstractUsecase)
	inputApplicationFacadeAdminAuthenticationAuthenticatorHandler := inputApplicationFacadeAdminAuthentication.NewAuthenticatorHandler(authenticatorUsecase, abstractHandler)
	gameModel := outputApplicationResourceModel.NewGameModel(abstractResource)
	gameLogic := outputApplicationResourceLogic.NewGameLogic(abstractResource)
	gameUsecase := usecaseApplicationAnyAdminResource.NewGameUsecase(gameModel, gameLogic, abstractUsecase)
	gameHandler := inputApplicationFacadeAdminResource.NewGameHandler(gameUsecase, abstractHandler)
	abstractInterceptor := interceptorFacadeGame.NewAbstractInterceptor(jwtHelper, aesHelper, rsaHelper)
	errorInterceptor := interceptorFacadeGame.NewErrorInterceptor(abstractInterceptor)
	statusInterceptor := interceptorFacadeGame.NewStatusInterceptor(abstractInterceptor)
	loggerInterceptor := interceptorFacadeGame.NewLoggerInterceptor(abstractInterceptor)
	authenticationInterceptor := interceptorFacadeGame.NewAuthenticationInterceptor(abstractInterceptor)
	interceptorFacadeAdminAbstractInterceptor := interceptorFacadeAdmin.NewAbstractInterceptor(jwtHelper, aesHelper, rsaHelper)
	interceptorFacadeAdminErrorInterceptor := interceptorFacadeAdmin.NewErrorInterceptor(interceptorFacadeAdminAbstractInterceptor)
	interceptorFacadeAdminStatusInterceptor := interceptorFacadeAdmin.NewStatusInterceptor(interceptorFacadeAdminAbstractInterceptor)
	interceptorFacadeAdminLoggerInterceptor := interceptorFacadeAdmin.NewLoggerInterceptor(interceptorFacadeAdminAbstractInterceptor)
	signatureInterceptor := interceptorFacadeAdmin.NewSignatureInterceptor(interceptorFacadeAdminAbstractInterceptor)
	decryptionInterceptor := interceptorFacadeAdmin.NewDecryptionInterceptor(interceptorFacadeAdminAbstractInterceptor)
	encryptionInterceptor := interceptorFacadeAdmin.NewEncryptionInterceptor(interceptorFacadeAdminAbstractInterceptor)
	facadeContainer := &FacadeContainer{
		Clock:                                  clock,
		AbstractHelper:                         abstractHelper,
		AesHelper:                              aesHelper,
		RsaHelper:                              rsaHelper,
		JwtHelper:                              jwtHelper,
		ResourceClient:                         resourceClient,
		FacadeAbstract:                         abstractHandler,
		FacadeTableScanner:                     scannerHandler,
		FacadeTableAuthenticator:               authenticatorHandler,
		FacadeAdminAuthenticationAuthenticator: inputApplicationFacadeAdminAuthenticationAuthenticatorHandler,
		FacadeAdminResourceGame:                gameHandler,
		FacadeGameErrorInterceptor:             errorInterceptor,
		FacadeGameStatusInterceptor:            statusInterceptor,
		FacadeGameLoggerInterceptor:            loggerInterceptor,
		FacadeGameAuthenticationInterceptor:    authenticationInterceptor,
		FacadeAdminErrorInterceptor:            interceptorFacadeAdminErrorInterceptor,
		FacadeAdminStatusInterceptor:           interceptorFacadeAdminStatusInterceptor,
		FacadeAdminLoggerInterceptor:           interceptorFacadeAdminLoggerInterceptor,
		FacadeAdminSignatureInterceptor:        signatureInterceptor,
		FacadeAdminDecryptionInterceptor:       decryptionInterceptor,
		FacadeAdminEncryptionInterceptor:       encryptionInterceptor,
	}
	return facadeContainer, nil
}

func InitResourceContainer(ctx context.Context) (*ResourceContainer, error) {
	clock, err := pkgUtility.NewClock(ctx)
	if err != nil {
		return nil, err
	}
	abstractHelper := helper.NewAbstractHelper()
	aesHelper := helper.NewAesHelper(abstractHelper)
	rsaHelper := helper.NewRsaHelper(abstractHelper)
	abstractUsecase := usecaseApplicationAnyModel.NewAbstractUsecase(aesHelper)
	db, err := bootstrap.NewMysql()
	if err != nil {
		return nil, err
	}
	universalClient, err := bootstrap.NewRedis()
	if err != nil {
		return nil, err
	}
	aop := pkgCache.NewAop(ctx, universalClient)
	abstractMysql := outputApplicationMysql.NewAbstractMysql(ctx, db, aop)
	adminUserModel := outputApplicationMysqlModel.NewAdminUserModel(abstractMysql)
	adminUserUsecase := usecaseApplicationAnyModel.NewAdminUserUsecase(adminUserModel, abstractUsecase)
	appUserModel := outputApplicationMysqlModel.NewAppUserModel(abstractMysql)
	appUserUsecase := usecaseApplicationAnyModel.NewAppUserUsecase(appUserModel, abstractUsecase)
	gameModel := outputApplicationMysqlModel.NewGameModel(abstractMysql)
	gameUsecase := usecaseApplicationAnyModel.NewGameUsecase(gameModel, abstractUsecase)
	tableModel := outputApplicationMysqlModel.NewTableModel(abstractMysql)
	tableUsecase := usecaseApplicationAnyModel.NewTableUsecase(tableModel)
	gameTypeModel := outputApplicationMysqlModel.NewGameTypeModel(abstractMysql)
	gameTypeUsecase := usecaseApplicationAnyModel.NewGameTypeUsecase(gameTypeModel, abstractUsecase)
	abstractHandler := inputApplicationResource.NewAbstractHandler()
	adminUserHandler := inputApplicationResourceModel.NewAdminUserHandler(abstractHandler, adminUserUsecase)
	adminRoleModel := outputApplicationMysqlModel.NewAdminRoleModel(abstractMysql)
	adminRoleUsecase := usecaseApplicationAnyModel.NewAdminRoleUsecase(adminRoleModel, abstractUsecase)
	adminRoleHandler := inputApplicationResourceModel.NewAdminRoleHandler(abstractHandler, adminRoleUsecase)
	appUserHandler := inputApplicationResourceModel.NewAppUserHandler(abstractHandler, appUserUsecase)
	gameHandler := inputApplicationResourceModel.NewGameHandler(abstractHandler, gameUsecase)
	tableHandler := inputApplicationResourceModel.NewTableHandler(abstractHandler, tableUsecase)
	gameTypeHandler := inputApplicationResourceModel.NewGameTypeHandler(abstractHandler, gameTypeUsecase)
	usecaseApplicationAnyLogicAbstractUsecase := usecaseApplicationAnyLogic.NewAbstractUsecase(aesHelper)
	gameLogic := outputApplicationMysqlLogic.NewGameLogic(abstractMysql)
	usecasePortAnyLogicGameUsecase := usecaseApplicationAnyLogic.NewGameUsecase(usecaseApplicationAnyLogicAbstractUsecase, gameLogic)
	inputApplicationResourceLogicGameHandler := inputApplicationResourceLogic.NewGameHandler(abstractHandler, usecasePortAnyLogicGameUsecase)
	tableLogic := outputApplicationMysqlLogic.NewTableLogic(abstractMysql)
	usecasePortAnyLogicTableUsecase := usecaseApplicationAnyLogic.NewTableUsecase(usecaseApplicationAnyLogicAbstractUsecase, tableLogic)
	inputApplicationResourceLogicTableHandler := inputApplicationResourceLogic.NewTableHandler(abstractHandler, usecasePortAnyLogicTableUsecase)
	gameTypeLogic := outputApplicationMysqlLogic.NewGameTypeLogic(abstractMysql)
	usecasePortAnyLogicGameTypeUsecase := usecaseApplicationAnyLogic.NewGameTypeUsecase(usecaseApplicationAnyLogicAbstractUsecase, gameTypeLogic)
	inputApplicationResourceLogicGameTypeHandler := inputApplicationResourceLogic.NewGameTypeHandler(abstractHandler, usecasePortAnyLogicGameTypeUsecase)
	connection, err := bootstrap.NewAmqp()
	if err != nil {
		return nil, err
	}
	abstractRabbitmq, err := outputApplicationRabbitmq.NewAbstractRabbitmq(ctx, connection)
	if err != nil {
		return nil, err
	}
	adminUserEvent, err := outputApplicationRabbitmqEvent.NewAdminUserEvent(abstractRabbitmq)
	if err != nil {
		return nil, err
	}
	usecasePortAnyEventAdminUserUsecase := usecaseApplicationAnyEvent.NewAdminUserUsecase(adminUserEvent)
	inputApplicationResourceEventAdminUserHandler := inputApplicationResourceEvent.NewAdminUserHandler(abstractHandler, usecasePortAnyEventAdminUserUsecase)
	abstractInterceptor := interceptorResourceLogic.NewAbstractInterceptor()
	authenticationInterceptor := interceptorResourceLogic.NewAuthenticationInterceptor(abstractInterceptor)
	errorInterceptor := interceptorResourceLogic.NewErrorInterceptor(abstractInterceptor)
	loggerInterceptor := interceptorResourceLogic.NewLoggerInterceptor(abstractInterceptor)
	interceptorResourceModelAbstractInterceptor := interceptorResourceModel.NewAbstractInterceptor()
	interceptorResourceModelAuthenticationInterceptor := interceptorResourceModel.NewAuthenticationInterceptor(interceptorResourceModelAbstractInterceptor)
	interceptorResourceModelErrorInterceptor := interceptorResourceModel.NewErrorInterceptor(interceptorResourceModelAbstractInterceptor)
	interceptorResourceModelLoggerInterceptor := interceptorResourceModel.NewLoggerInterceptor(interceptorResourceModelAbstractInterceptor)
	resourceContainer := &ResourceContainer{
		Clock:                                  clock,
		AbstractHelper:                         abstractHelper,
		AesHelper:                              aesHelper,
		RsaHelper:                              rsaHelper,
		AbstractUsecase:                        abstractUsecase,
		AdminUserUsecase:                       adminUserUsecase,
		AppUserUsecase:                         appUserUsecase,
		GameUsecase:                            gameUsecase,
		TableUsecase:                           tableUsecase,
		GameTypeUsecase:                        gameTypeUsecase,
		ResourceAbstract:                       abstractHandler,
		ResourceModelAdminUser:                 adminUserHandler,
		ResourceModelAdminRole:                 adminRoleHandler,
		ResourceModelAppUser:                   appUserHandler,
		ResourceModelGame:                      gameHandler,
		ResourceModelTable:                     tableHandler,
		ResourceModelGameType:                  gameTypeHandler,
		ResourceLogicGame:                      inputApplicationResourceLogicGameHandler,
		ResourceLogicTable:                     inputApplicationResourceLogicTableHandler,
		ResourceLogicGameType:                  inputApplicationResourceLogicGameTypeHandler,
		ResourceEventAdminUser:                 inputApplicationResourceEventAdminUserHandler,
		ResourceLogicAuthenticationInterceptor: authenticationInterceptor,
		ResourceLogicErrorInterceptor:          errorInterceptor,
		ResourceLogicLoggerInterceptor:         loggerInterceptor,
		ResourceModelAuthenticationInterceptor: interceptorResourceModelAuthenticationInterceptor,
		ResourceModelErrorInterceptor:          interceptorResourceModelErrorInterceptor,
		ResourceModelLoggerInterceptor:         interceptorResourceModelLoggerInterceptor,
		ResourceRabbitmqAdminUserEvent:         adminUserEvent,
	}
	return resourceContainer, nil
}

func InitRabbitmqContainer(ctx context.Context) (*RabbitmqContainer, error) {
	clock, err := pkgUtility.NewClock(ctx)
	if err != nil {
		return nil, err
	}
	abstractHelper := helper.NewAbstractHelper()
	aesHelper := helper.NewAesHelper(abstractHelper)
	connection, err := bootstrap.NewAmqp()
	if err != nil {
		return nil, err
	}
	abstractHandler := inputApplicationRabbitmq.NewAbstractHandler(aesHelper, connection)
	db, err := bootstrap.NewMysql()
	if err != nil {
		return nil, err
	}
	universalClient, err := bootstrap.NewRedis()
	if err != nil {
		return nil, err
	}
	aop := pkgCache.NewAop(ctx, universalClient)
	abstractMysql := outputApplicationMysql.NewAbstractMysql(ctx, db, aop)
	appUserModel := outputApplicationMysqlModel.NewAppUserModel(abstractMysql)
	jwtHelper := helper.NewJwtHelper(abstractHelper)
	abstractUsecase := usecaseApplicationAnyAdmin.NewAbstractUsecase(aesHelper, jwtHelper)
	appUserUsecase := usecaseApplicationAnyAdminResource.NewAppUserUsecase(appUserModel, abstractUsecase)
	appUserHandler := inputApplicationRabbitmqAdminResource.NewAppUserHandler(appUserUsecase, abstractHandler)
	rabbitmqContainer := &RabbitmqContainer{
		Clock:                        clock,
		AbstractHelper:               abstractHelper,
		AesHelper:                    aesHelper,
		AbstractHandler:              abstractHandler,
		ConsumerAdminResourceAppUser: appUserHandler,
	}
	return rabbitmqContainer, nil
}

func InitCronContainer(ctx context.Context) (*CronContainer, error) {
	clock, err := pkgUtility.NewClock(ctx)
	if err != nil {
		return nil, err
	}
	abstractHelper := helper.NewAbstractHelper()
	aesHelper := helper.NewAesHelper(abstractHelper)
	jwtHelper := helper.NewJwtHelper(abstractHelper)
	db, err := bootstrap.NewMysql()
	if err != nil {
		return nil, err
	}
	universalClient, err := bootstrap.NewRedis()
	if err != nil {
		return nil, err
	}
	aop := pkgCache.NewAop(ctx, universalClient)
	abstractMysql := outputApplicationMysql.NewAbstractMysql(ctx, db, aop)
	appUserModel := outputApplicationMysqlModel.NewAppUserModel(abstractMysql)
	abstractUsecase := usecaseApplicationAnyAdmin.NewAbstractUsecase(aesHelper, jwtHelper)
	appUserUsecase := usecaseApplicationAnyAdminResource.NewAppUserUsecase(appUserModel, abstractUsecase)
	abstractHandler := inputApplicationCron.NewAbstractHandler(aesHelper)
	appUserHandler := inputApplicationCronAdminResource.NewAppUserHandler(appUserUsecase, abstractHandler)
	adminUserModel := outputApplicationMysqlModel.NewAdminUserModel(abstractMysql)
	authenticatorUsecase := usecaseApplicationAnyAdminAuthentication.NewAuthenticatorUsecase(adminUserModel, abstractUsecase)
	authenticatorHandler := inputApplicationCronAdminAuthentication.NewAuthenticatorHandler(authenticatorUsecase, abstractHandler)
	cronContainer := &CronContainer{
		Clock:                                clock,
		AbstractHelper:                       abstractHelper,
		AesHelper:                            aesHelper,
		JwtHelper:                            jwtHelper,
		CronAdminResourceAppUser:             appUserHandler,
		CronAdminAuthenticationAuthenticator: authenticatorHandler,
	}
	return cronContainer, nil
}

func InitWebsocketContainer(ctx context.Context) (*WebsocketContainer, error) {
	clock, err := pkgUtility.NewClock(ctx)
	if err != nil {
		return nil, err
	}
	abstractHelper := helper.NewAbstractHelper()
	aesHelper := helper.NewAesHelper(abstractHelper)
	rsaHelper := helper.NewRsaHelper(abstractHelper)
	jwtHelper := helper.NewJwtHelper(abstractHelper)
	clientConn := bootstrap.NewResource(ctx)
	model := client.NewModel(clientConn)
	logic := client.NewLogic(clientConn)
	event := client.NewEvent(clientConn)
	resourceClient := client.NewResourceClient(clientConn, model, logic, event)
	abstractHandler := inputApplicationWebsocket.NewAbstractHandler(aesHelper)
	abstractResource := outputApplicationResource.NewAbstractResource(ctx, resourceClient)
	adminUserModel := outputApplicationResourceModel.NewAdminUserModel(abstractResource)
	abstractUsecase := usecaseApplicationAnyAdmin.NewAbstractUsecase(aesHelper, jwtHelper)
	authenticatorUsecase := usecaseApplicationAnyAdminAuthentication.NewAuthenticatorUsecase(adminUserModel, abstractUsecase)
	authenticatorHandler := inputApplicationWebsocketAdminAuthentication.NewAuthenticatorHandler(authenticatorUsecase, abstractHandler)
	abstractMiddleware := middlewareWebsocketAdmin.NewAbstractMiddleware(clock, rsaHelper, aesHelper, jwtHelper)
	adminMiddleware := middlewareWebsocketAdmin.NewAdminMiddleware(abstractMiddleware)
	errorMiddleware := middlewareWebsocketAdmin.NewErrorMiddleware(abstractMiddleware)
	loggerMiddleware := middlewareWebsocketAdmin.NewLoggerMiddleware(abstractMiddleware)
	nonexistentMiddleware := middlewareWebsocketAdmin.NewNonexistentMiddleware(abstractMiddleware)
	requestMiddleware := middlewareWebsocketAdmin.NewRequestMiddleware(abstractMiddleware)
	websocketContainer := &WebsocketContainer{
		Clock:           clock,
		AbstractHelper:  abstractHelper,
		AesHelper:       aesHelper,
		RsaHelper:       rsaHelper,
		JwtHelper:       jwtHelper,
		ResourceClient:  resourceClient,
		AbstractHandler: abstractHandler,
		WebsocketAdminAuthenticationAuthenticator: authenticatorHandler,
		WebsocketAdminAbstractMiddleware:          abstractMiddleware,
		WebsocketAdminAdminMiddleware:             adminMiddleware,
		WebsocketAdminErrorMiddleware:             errorMiddleware,
		WebsocketAdminLoggerMiddleware:            loggerMiddleware,
		WebsocketAdminNonexistentMiddleware:       nonexistentMiddleware,
		WebsocketAdminRequestMiddleware:           requestMiddleware,
	}
	return websocketContainer, nil
}

func InitCentrifugeContainer(ctx context.Context) (*CentrifugeContainer, error) {
	clock, err := pkgUtility.NewClock(ctx)
	if err != nil {
		return nil, err
	}
	abstractHelper := helper.NewAbstractHelper()
	aesHelper := helper.NewAesHelper(abstractHelper)
	rsaHelper := helper.NewRsaHelper(abstractHelper)
	jwtHelper := helper.NewJwtHelper(abstractHelper)
	clientConn := bootstrap.NewResource(ctx)
	model := client.NewModel(clientConn)
	logic := client.NewLogic(clientConn)
	event := client.NewEvent(clientConn)
	resourceClient := client.NewResourceClient(clientConn, model, logic, event)
	conn, err := bootstrap.NewNats()
	if err != nil {
		return nil, err
	}
	natsBroker := pkgNats.NewNATSBroker(conn)
	centrifugeContainer := &CentrifugeContainer{
		Clock:          clock,
		AbstractHelper: abstractHelper,
		AesHelper:      aesHelper,
		RsaHelper:      rsaHelper,
		JwtHelper:      jwtHelper,
		ResourceClient: resourceClient,
		Nats:           conn,
		NatsBroker:     natsBroker,
	}
	return centrifugeContainer, nil
}

func InitClientContainer(ctx context.Context) (*ClientContainer, error) {
	clock, err := pkgUtility.NewClock(ctx)
	if err != nil {
		return nil, err
	}
	abstractHelper := helper.NewAbstractHelper()
	aesHelper := helper.NewAesHelper(abstractHelper)
	clientContainer := &ClientContainer{
		Clock:          clock,
		AbstractHelper: abstractHelper,
		AesHelper:      aesHelper,
	}
	return clientContainer, nil
}

func InitCommandContainer(ctx context.Context) (*CommandContainer, error) {
	clock, err := pkgUtility.NewClock(ctx)
	if err != nil {
		return nil, err
	}
	abstractHelper := helper.NewAbstractHelper()
	aesHelper := helper.NewAesHelper(abstractHelper)
	jwtHelper := helper.NewJwtHelper(abstractHelper)
	abstractHandler := inputApplicationCommand.NewAbstractHandler(aesHelper)
	db, err := bootstrap.NewMysql()
	if err != nil {
		return nil, err
	}
	universalClient, err := bootstrap.NewRedis()
	if err != nil {
		return nil, err
	}
	aop := pkgCache.NewAop(ctx, universalClient)
	abstractMysql := outputApplicationMysql.NewAbstractMysql(ctx, db, aop)
	appUserModel := outputApplicationMysqlModel.NewAppUserModel(abstractMysql)
	abstractUsecase := usecaseApplicationAnyAdmin.NewAbstractUsecase(aesHelper, jwtHelper)
	appUserUsecase := usecaseApplicationAnyAdminResource.NewAppUserUsecase(appUserModel, abstractUsecase)
	appUserHandler := inputApplicationCommandAdminResource.NewAppUserHandler(appUserUsecase, abstractHandler)
	adminUserModel := outputApplicationMysqlModel.NewAdminUserModel(abstractMysql)
	authenticatorUsecase := usecaseApplicationAnyAdminAuthentication.NewAuthenticatorUsecase(adminUserModel, abstractUsecase)
	authenticatorHandler := inputApplicationCommandAdminAuthentication.NewAuthenticatorHandler(authenticatorUsecase, abstractHandler)
	commandContainer := &CommandContainer{
		Clock:                            clock,
		AbstractHelper:                   abstractHelper,
		AesHelper:                        aesHelper,
		JwtHelper:                        jwtHelper,
		AbstractHandler:                  abstractHandler,
		CommandAdminReourceAppUser:       appUserHandler,
		CommandAdminAuthenticationSignIn: authenticatorHandler,
	}
	return commandContainer, nil
}

func InitTcpContainer(ctx context.Context) (*TcpContainer, error) {
	clock, err := pkgUtility.NewClock(ctx)
	if err != nil {
		return nil, err
	}
	abstractHelper := helper.NewAbstractHelper()
	aesHelper := helper.NewAesHelper(abstractHelper)
	jwtHelper := helper.NewJwtHelper(abstractHelper)
	clientConn := bootstrap.NewResource(ctx)
	model := client.NewModel(clientConn)
	logic := client.NewLogic(clientConn)
	event := client.NewEvent(clientConn)
	resourceClient := client.NewResourceClient(clientConn, model, logic, event)
	abstractHandler := inputApplicationTcp.NewAbstractHandler(aesHelper)
	abstractResource := outputApplicationResource.NewAbstractResource(ctx, resourceClient)
	adminUserModel := outputApplicationResourceModel.NewAdminUserModel(abstractResource)
	abstractUsecase := usecaseApplicationAnyAdmin.NewAbstractUsecase(aesHelper, jwtHelper)
	authenticatorUsecase := usecaseApplicationAnyAdminAuthentication.NewAuthenticatorUsecase(adminUserModel, abstractUsecase)
	authenticatorHandler := inputApplicationTcpAdminAuthentication.NewAuthenticatorHandler(authenticatorUsecase, abstractHandler)
	tcpContainer := &TcpContainer{
		Clock:                        clock,
		AbstractHelper:               abstractHelper,
		AesHelper:                    aesHelper,
		JwtHelper:                    jwtHelper,
		ResourceClient:               resourceClient,
		AbstractHandler:              abstractHandler,
		TcpAdminAuthenticationSignIn: authenticatorHandler,
	}
	return tcpContainer, nil
}

func InitSourceContainer(ctx context.Context) (*SourceContainer, error) {
	clock, err := pkgUtility.NewClock(ctx)
	if err != nil {
		return nil, err
	}
	abstractHelper := helper.NewAbstractHelper()
	aesHelper := helper.NewAesHelper(abstractHelper)
	abstractHandler := inputApplicationSource.NewAbstractHandler()
	abstractUsecase := usecaseApplicationAnyAnnouncement.NewAbstractUsecase(aesHelper)
	abstractMemory := outputApplicationMemory.NewAbstractMemory(ctx)
	lotteryModel := outputApplicationMemoryModel.NewLotteryModel(abstractMemory)
	lotteryUsecase := usecaseApplicationAnyAnnouncement.NewLotteryUsecase(abstractUsecase, lotteryModel)
	lotteryHandler := inputApplicationSourceAnnouncement.NewLotteryHandler(abstractHandler, lotteryUsecase)
	sourceContainer := &SourceContainer{
		Clock:                     clock,
		AbstractHelper:            abstractHelper,
		AesHelper:                 aesHelper,
		SourceAnnouncementLottery: lotteryHandler,
	}
	return sourceContainer, nil
}

func InitDaemonContainer(ctx context.Context) (*DaemonContainer, error) {
	clock, err := pkgUtility.NewClock(ctx)
	if err != nil {
		return nil, err
	}
	abstractHelper := helper.NewAbstractHelper()
	aesHelper := helper.NewAesHelper(abstractHelper)
	clientConn := bootstrap.NewSource(ctx)
	announcement := client.NewAnnouncement(clientConn)
	sourceClient := client.NewSourceClient(clientConn, announcement)
	abstractUsecase := usecaseApplicationAnyWatcher.NewAbstractUsecase(aesHelper)
	universalClient, err := bootstrap.NewRedis()
	if err != nil {
		return nil, err
	}
	cacheHelper := helper.NewCacheHelper(abstractHelper, universalClient)
	abstractCache := outputApplicationCache.NewAbstractCache(ctx, cacheHelper)
	lotteryModel := outputApplicationCacheModel.NewLotteryModel(abstractCache)
	announcementLotteryUsecase := usecaseApplicationAnyWatcherSource.NewAnnouncementLotteryUsecase(abstractUsecase, lotteryModel)
	abstractHandler := inputApplicationDaemon.NewAbstractHandler(aesHelper)
	announcementLotteryHandler := inputApplicationDaemonWatcherSource.NewAnnouncementLotteryHandler(announcementLotteryUsecase, abstractHandler)
	daemonContainer := &DaemonContainer{
		Clock:                                  clock,
		AbstractHelper:                         abstractHelper,
		AesHelper:                              aesHelper,
		SourceClient:                           sourceClient,
		DaemonWatcherSourceAnnouncementLottery: announcementLotteryHandler,
	}
	return daemonContainer, nil
}

// wire.go:

// HttpContainer 只給 `http` Gin 服務使用。
type HttpContainer struct {

	// pkg
	*pkgGin.Response
	Clock *pkgUtility.Clock

	// Helper
	*helper.AbstractHelper
	*helper.AesHelper
	*helper.RsaHelper
	*helper.JwtHelper

	// Clients
	ResourceClient *client.ResourceClient

	// HTTP server -Controller
	HttpAdminAuthenticationAuthenticator *inputApplicationHttpAdminAuthentication.AuthenticatorHandler
	HttpAdminResourceGame                *inputApplicationHttpAdminResource.GameHandler
	HttpAdminResourceTable               *inputApplicationHttpAdminResource.TableHandler
	HttpAdminResourceAdminUser           *inputApplicationHttpAdminResource.AdminUserHandler
	HttpAdminResourceAdminRole           *inputApplicationHttpAdminResource.AdminRoleHandler
	HttpAdminResourceGameType            *inputApplicationHttpAdminResource.GameTypeHandler
	HttpAdminOptionGameType              *inputApplicationHttpAdminOption.GameTypeHandler
	HttpGameAuthenticationAuthenticator  *inputApplicationHttpGameAuthentication.AuthenticatorHandler

	// HTTP server -Middleware
	// Middleware 部分
	HttpAdminAbstractMiddleware       *middlewareHttpAdmin.AbstractMiddleware
	HttpAdminAdminMiddleware          *middlewareHttpAdmin.AdminMiddleware
	HttpAdminAuthenticationMiddleware *middlewareHttpAdmin.AuthenticationMiddleware
	HttpAdminDecryptionMiddleware     *middlewareHttpAdmin.DecryptionMiddleware
	HttpAdminEncryptionMiddleware     *middlewareHttpAdmin.EncryptionMiddleware
	HttpAdminErrorMiddleware          *middlewareHttpAdmin.ErrorMiddleware
	HttpAdminLoggerMiddleware         *middlewareHttpAdmin.LoggerMiddleware
	HttpAdminNonexistentMiddleware    *middlewareHttpAdmin.NonexistentMiddleware
	HttpAdminRequestMiddleware        *middlewareHttpAdmin.RequestMiddleware
	HttpAdminResponseMiddleware       *middlewareHttpAdmin.ResponseMiddleware
	HttpAdminSignatureMiddleware      *middlewareHttpAdmin.SignatureMiddleware

	HttpTableAbstractMiddleware       *middlewareHttpTable.AbstractMiddleware
	HttpTableTableMiddleware          *middlewareHttpTable.TableMiddleware
	HttpTableAuthenticationMiddleware *middlewareHttpTable.AuthenticationMiddleware
	HttpTableDecryptionMiddleware     *middlewareHttpTable.DecryptionMiddleware
	HttpTableEncryptionMiddleware     *middlewareHttpTable.EncryptionMiddleware
	HttpTableErrorMiddleware          *middlewareHttpTable.ErrorMiddleware
	HttpTableLoggerMiddleware         *middlewareHttpTable.LoggerMiddleware
	HttpTableNonexistentMiddleware    *middlewareHttpTable.NonexistentMiddleware
	HttpTableRequestMiddleware        *middlewareHttpTable.RequestMiddleware
	HttpTableResponseMiddleware       *middlewareHttpTable.ResponseMiddleware
	HttpTableSignatureMiddleware      *middlewareHttpTable.SignatureMiddleware

	HttpGameAbstractMiddleware       *middlewareHttpGame.AbstractMiddleware
	HttpGameGameMiddleware           *middlewareHttpGame.GameMiddleware
	HttpGameAuthenticationMiddleware *middlewareHttpGame.AuthenticationMiddleware
	HttpGameDecryptionMiddleware     *middlewareHttpGame.DecryptionMiddleware
	HttpGameEncryptionMiddleware     *middlewareHttpGame.EncryptionMiddleware
	HttpGameErrorMiddleware          *middlewareHttpGame.ErrorMiddleware
	HttpGameLoggerMiddleware         *middlewareHttpGame.LoggerMiddleware
	HttpGameNonexistentMiddleware    *middlewareHttpGame.NonexistentMiddleware
	HttpGameRequestMiddleware        *middlewareHttpGame.RequestMiddleware
	HttpGameResponseMiddleware       *middlewareHttpGame.ResponseMiddleware
	HttpGameSignatureMiddleware      *middlewareHttpGame.SignatureMiddleware
}

type FacadeContainer struct {

	// pkg
	Clock *pkgUtility.Clock

	// Helper
	*helper.AbstractHelper
	*helper.AesHelper
	*helper.RsaHelper
	*helper.JwtHelper

	// Clients
	ResourceClient *client.ResourceClient

	// gRPC Facade service
	FacadeAbstract                         *inputApplicationFacade.AbstractHandler
	FacadeTableScanner                     *inputApplicationFacadeTable.ScannerHandler
	FacadeTableAuthenticator               *inputApplicationFacadeRegister.AuthenticatorHandler
	FacadeAdminAuthenticationAuthenticator *inputApplicationFacadeAdminAuthentication.AuthenticatorHandler
	FacadeAdminResourceGame                *inputApplicationFacadeAdminResource.GameHandler

	// gRPC Facade Interceptor
	FacadeGameErrorInterceptor          *interceptorFacadeGame.ErrorInterceptor
	FacadeGameStatusInterceptor         *interceptorFacadeGame.StatusInterceptor
	FacadeGameLoggerInterceptor         *interceptorFacadeGame.LoggerInterceptor
	FacadeGameAuthenticationInterceptor *interceptorFacadeGame.AuthenticationInterceptor
	FacadeAdminErrorInterceptor         *interceptorFacadeAdmin.ErrorInterceptor
	FacadeAdminStatusInterceptor        *interceptorFacadeAdmin.StatusInterceptor
	FacadeAdminLoggerInterceptor        *interceptorFacadeAdmin.LoggerInterceptor
	FacadeAdminSignatureInterceptor     *interceptorFacadeAdmin.SignatureInterceptor
	FacadeAdminDecryptionInterceptor    *interceptorFacadeAdmin.DecryptionInterceptor
	FacadeAdminEncryptionInterceptor    *interceptorFacadeAdmin.EncryptionInterceptor
}

type ResourceContainer struct {

	// pkg
	Clock *pkgUtility.Clock

	// Helper
	*helper.AbstractHelper
	*helper.AesHelper
	*helper.RsaHelper

	*usecaseApplicationAnyModel.AbstractUsecase
	usecasePortAnyModel.AdminUserUsecase
	usecasePortAnyModel.AppUserUsecase
	usecasePortAnyModel.GameUsecase
	usecasePortAnyModel.TableUsecase
	usecasePortAnyModel.GameTypeUsecase

	// gRPC Resource server
	ResourceAbstract       *inputApplicationResource.AbstractHandler
	ResourceModelAdminUser *inputApplicationResourceModel.AdminUserHandler
	ResourceModelAdminRole *inputApplicationResourceModel.AdminRoleHandler
	ResourceModelAppUser   *inputApplicationResourceModel.AppUserHandler
	ResourceModelGame      *inputApplicationResourceModel.GameHandler
	ResourceModelTable     *inputApplicationResourceModel.TableHandler
	ResourceModelGameType  *inputApplicationResourceModel.GameTypeHandler
	ResourceLogicGame      *inputApplicationResourceLogic.GameHandler
	ResourceLogicTable     *inputApplicationResourceLogic.TableHandler
	ResourceLogicGameType  *inputApplicationResourceLogic.GameTypeHandler
	ResourceEventAdminUser *inputApplicationResourceEvent.AdminUserHandler

	// gRPC Resource Interceptor
	ResourceLogicAuthenticationInterceptor *interceptorResourceLogic.AuthenticationInterceptor
	ResourceLogicErrorInterceptor          *interceptorResourceLogic.ErrorInterceptor
	ResourceLogicLoggerInterceptor         *interceptorResourceLogic.LoggerInterceptor
	ResourceModelAuthenticationInterceptor *interceptorResourceModel.AuthenticationInterceptor
	ResourceModelErrorInterceptor          *interceptorResourceModel.ErrorInterceptor
	ResourceModelLoggerInterceptor         *interceptorResourceModel.LoggerInterceptor

	// MQ 生產者
	ResourceRabbitmqAdminUserEvent outputPortAnyEvent.AdminUserEvent
}

// RabbitmqContainer 只給 `rabbitmq` MQ 消費者服務使用。
type RabbitmqContainer struct {

	// pkg
	Clock *pkgUtility.Clock

	// Helper
	*helper.AbstractHelper
	*helper.AesHelper

	// MQ 消費者
	*inputApplicationRabbitmq.AbstractHandler
	ConsumerAdminResourceAppUser *inputApplicationRabbitmqAdminResource.AppUserHandler
}

// CronContainer 只給 `cron` 排程服務使用。
type CronContainer struct {

	// pkg
	Clock *pkgUtility.Clock

	// Helper
	*helper.AbstractHelper
	*helper.AesHelper
	*helper.JwtHelper

	// 排程 server
	CronAdminResourceAppUser             *inputApplicationCronAdminResource.AppUserHandler
	CronAdminAuthenticationAuthenticator *inputApplicationCronAdminAuthentication.AuthenticatorHandler
}

// WebsocketContainer 只給 `websocket` 服務使用。
type WebsocketContainer struct {

	// pkg
	Clock *pkgUtility.Clock

	// Helper
	*helper.AbstractHelper
	*helper.AesHelper
	*helper.RsaHelper
	*helper.JwtHelper

	// Clients
	ResourceClient *client.ResourceClient

	// websocket
	*inputApplicationWebsocket.AbstractHandler
	WebsocketAdminAuthenticationAuthenticator *inputApplicationWebsocketAdminAuthentication.AuthenticatorHandler

	// Websocket server -Middleware
	WebsocketAdminAbstractMiddleware    *middlewareWebsocketAdmin.AbstractMiddleware
	WebsocketAdminAdminMiddleware       *middlewareWebsocketAdmin.AdminMiddleware
	WebsocketAdminErrorMiddleware       *middlewareWebsocketAdmin.ErrorMiddleware
	WebsocketAdminLoggerMiddleware      *middlewareWebsocketAdmin.LoggerMiddleware
	WebsocketAdminNonexistentMiddleware *middlewareWebsocketAdmin.NonexistentMiddleware
	WebsocketAdminRequestMiddleware     *middlewareWebsocketAdmin.RequestMiddleware
}

type CentrifugeContainer struct {

	// pkg
	Clock *pkgUtility.Clock

	// Helper
	*helper.AbstractHelper
	*helper.AesHelper
	*helper.RsaHelper
	*helper.JwtHelper

	// Clients
	ResourceClient *client.ResourceClient

	// NATS
	Nats       *nats.Conn
	NatsBroker *pkgNats.NATSBroker
}

// ClientContainer 只給 `client` （訂閱外部 gRPC stream）服務使用。
type ClientContainer struct {

	// pkg
	Clock *pkgUtility.Clock

	// Helper
	*helper.AbstractHelper
	*helper.AesHelper
}

// 、
type CommandContainer struct {

	// pkg
	Clock *pkgUtility.Clock

	// Helper
	*helper.AbstractHelper
	*helper.AesHelper
	*helper.JwtHelper

	// command
	*inputApplicationCommand.AbstractHandler
	CommandAdminReourceAppUser       *inputApplicationCommandAdminResource.AppUserHandler
	CommandAdminAuthenticationSignIn *inputApplicationCommandAdminAuthentication.AuthenticatorHandler
}

type TcpContainer struct {

	// pkg
	Clock *pkgUtility.Clock

	// Helper
	*helper.AbstractHelper
	*helper.AesHelper
	*helper.JwtHelper

	// Clients
	ResourceClient *client.ResourceClient

	// tcp
	*inputApplicationTcp.AbstractHandler
	TcpAdminAuthenticationSignIn *inputApplicationTcpAdminAuthentication.AuthenticatorHandler
}

type SourceContainer struct {

	// pkg
	Clock *pkgUtility.Clock

	// Helper
	*helper.AbstractHelper
	*helper.AesHelper

	SourceAnnouncementLottery *inputApplicationSourceAnnouncement.LotteryHandler
}

type DaemonContainer struct {

	// pkg
	Clock *pkgUtility.Clock

	// Helper
	*helper.AbstractHelper
	*helper.AesHelper

	// Clients
	SourceClient *client.SourceClient

	DaemonWatcherSourceAnnouncementLottery *inputApplicationDaemonWatcherSource.AnnouncementLotteryHandler
}
