syntax = "proto3";

package pb.resource.model;

option go_package = "./pb_resource_model";

import "google/protobuf/timestamp.proto";
import "google/protobuf/struct.proto";
import "resource/model/game.proto";

service GameTypeModel {
  rpc AddOne(GameTypeAddOneInput) returns (GameTypeAddOneOutput);
  rpc ShowOneById(GameTypeShowOneByIdInput) returns (GameTypeShowOneByIdOutput);
  rpc ShowOnesByWheresWithOrdersLimit(GameTypeShowOnesByWheresWithOrdersLimitInput) returns (GameTypeShowOnesByWheresWithOrdersLimitOutput);
  rpc EditOneById(GameTypeEditOneByIdInput) returns (GameTypeEditOneByIdOutput);
  rpc RemoveOneById(GameTypeRemoveOneByIdInput) returns (GameTypeRemoveOneByIdOutput);
  rpc TotalByWheres(GameTypeTotalByWheresInput) returns (GameTypeTotalByWheresOutput);
}

message GameTypeWhere {
  string field = 1;
  string operator = 2;
  google.protobuf.Value value = 3;
}

message GameTypeOrder {
  string field = 1;
  string value = 2;
}

message GameTypeLimit {
  uint64 offset = 1;
  uint64 count = 2;
}

message GameTypeAddOneInput {
  optional string key = 1;
  optional string name = 2;
}

message GameTypeAddOneOutput {
  uint32 id = 1;
  string key = 2;
  string name = 3;
  google.protobuf.Timestamp created_at = 4;
  google.protobuf.Timestamp updated_at = 5;
  google.protobuf.Timestamp deleted_at = 6;
}

message GameTypeShowOneByIdInput {
  uint32 id = 1;
}

message GameTypeShowOneByIdOutput {
  uint32 id = 1;
  string key = 2;
  string name = 3;
  google.protobuf.Timestamp created_at = 4;
  google.protobuf.Timestamp updated_at = 5;
  google.protobuf.Timestamp deleted_at = 6;
}

message GameTypeEditOneByIdInput {
  uint32 id = 1;
  optional string key = 2;
  optional string name = 3;
}

message GameTypeEditOneByIdOutput {
  bool status = 1;
}

message GameTypeRemoveOneByIdInput {
  uint32 id = 1;
}

message GameTypeRemoveOneByIdOutput {
  bool status = 1;
}

message GameTypeShowOnesByWheresWithOrdersLimitInput {
  GameTypeLimit limit = 1;
  repeated GameTypeWhere wheres = 2;
  repeated GameTypeOrder orders = 3;
}

message GameTypeShowOnesByWheresWithOrdersLimitOutput {
  repeated GameType game_types = 1;
}

message GameTypeTotalByWheresInput {
  repeated GameTypeWhere wheres = 1;
}

message GameTypeTotalByWheresOutput {
  uint64 total = 1;
}
