// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: facade/admin/resource/game.proto

package pb_facade_admin_resource

import (
	facade "example/pb/facade"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GameValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameTypeId    *uint64                `protobuf:"varint,1,opt,name=game_type_id,json=gameTypeId,proto3,oneof" json:"game_type_id,omitempty"`
	Key           *string                `protobuf:"bytes,2,opt,name=key,proto3,oneof" json:"key,omitempty"`
	Name          *string                `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameValue) Reset() {
	*x = GameValue{}
	mi := &file_facade_admin_resource_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameValue) ProtoMessage() {}

func (x *GameValue) ProtoReflect() protoreflect.Message {
	mi := &file_facade_admin_resource_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameValue.ProtoReflect.Descriptor instead.
func (*GameValue) Descriptor() ([]byte, []int) {
	return file_facade_admin_resource_game_proto_rawDescGZIP(), []int{0}
}

func (x *GameValue) GetGameTypeId() uint64 {
	if x != nil && x.GameTypeId != nil {
		return *x.GameTypeId
	}
	return 0
}

func (x *GameValue) GetKey() string {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return ""
}

func (x *GameValue) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *GameValue) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

type GameAddOneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *GameValue             `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameAddOneRequest) Reset() {
	*x = GameAddOneRequest{}
	mi := &file_facade_admin_resource_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameAddOneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameAddOneRequest) ProtoMessage() {}

func (x *GameAddOneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_facade_admin_resource_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameAddOneRequest.ProtoReflect.Descriptor instead.
func (*GameAddOneRequest) Descriptor() ([]byte, []int) {
	return file_facade_admin_resource_game_proto_rawDescGZIP(), []int{1}
}

func (x *GameAddOneRequest) GetValue() *GameValue {
	if x != nil {
		return x.Value
	}
	return nil
}

type GameAddOneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameAddOneResponse) Reset() {
	*x = GameAddOneResponse{}
	mi := &file_facade_admin_resource_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameAddOneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameAddOneResponse) ProtoMessage() {}

func (x *GameAddOneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_facade_admin_resource_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameAddOneResponse.ProtoReflect.Descriptor instead.
func (*GameAddOneResponse) Descriptor() ([]byte, []int) {
	return file_facade_admin_resource_game_proto_rawDescGZIP(), []int{2}
}

type GameEditOneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filters       []*facade.Filter       `protobuf:"bytes,1,rep,name=filters,proto3" json:"filters,omitempty"`
	Value         *GameValue             `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameEditOneRequest) Reset() {
	*x = GameEditOneRequest{}
	mi := &file_facade_admin_resource_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameEditOneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameEditOneRequest) ProtoMessage() {}

func (x *GameEditOneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_facade_admin_resource_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameEditOneRequest.ProtoReflect.Descriptor instead.
func (*GameEditOneRequest) Descriptor() ([]byte, []int) {
	return file_facade_admin_resource_game_proto_rawDescGZIP(), []int{3}
}

func (x *GameEditOneRequest) GetFilters() []*facade.Filter {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *GameEditOneRequest) GetValue() *GameValue {
	if x != nil {
		return x.Value
	}
	return nil
}

type GameEditOneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameEditOneResponse) Reset() {
	*x = GameEditOneResponse{}
	mi := &file_facade_admin_resource_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameEditOneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameEditOneResponse) ProtoMessage() {}

func (x *GameEditOneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_facade_admin_resource_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameEditOneResponse.ProtoReflect.Descriptor instead.
func (*GameEditOneResponse) Descriptor() ([]byte, []int) {
	return file_facade_admin_resource_game_proto_rawDescGZIP(), []int{4}
}

type GameRemoveOneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filters       []*facade.Filter       `protobuf:"bytes,1,rep,name=filters,proto3" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameRemoveOneRequest) Reset() {
	*x = GameRemoveOneRequest{}
	mi := &file_facade_admin_resource_game_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameRemoveOneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameRemoveOneRequest) ProtoMessage() {}

func (x *GameRemoveOneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_facade_admin_resource_game_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameRemoveOneRequest.ProtoReflect.Descriptor instead.
func (*GameRemoveOneRequest) Descriptor() ([]byte, []int) {
	return file_facade_admin_resource_game_proto_rawDescGZIP(), []int{5}
}

func (x *GameRemoveOneRequest) GetFilters() []*facade.Filter {
	if x != nil {
		return x.Filters
	}
	return nil
}

type GameRemoveOneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameRemoveOneResponse) Reset() {
	*x = GameRemoveOneResponse{}
	mi := &file_facade_admin_resource_game_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameRemoveOneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameRemoveOneResponse) ProtoMessage() {}

func (x *GameRemoveOneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_facade_admin_resource_game_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameRemoveOneResponse.ProtoReflect.Descriptor instead.
func (*GameRemoveOneResponse) Descriptor() ([]byte, []int) {
	return file_facade_admin_resource_game_proto_rawDescGZIP(), []int{6}
}

type GameShowOneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filters       []*facade.Filter       `protobuf:"bytes,1,rep,name=filters,proto3" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameShowOneRequest) Reset() {
	*x = GameShowOneRequest{}
	mi := &file_facade_admin_resource_game_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameShowOneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameShowOneRequest) ProtoMessage() {}

func (x *GameShowOneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_facade_admin_resource_game_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameShowOneRequest.ProtoReflect.Descriptor instead.
func (*GameShowOneRequest) Descriptor() ([]byte, []int) {
	return file_facade_admin_resource_game_proto_rawDescGZIP(), []int{7}
}

func (x *GameShowOneRequest) GetFilters() []*facade.Filter {
	if x != nil {
		return x.Filters
	}
	return nil
}

type GameShowOneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	One           *facade.Game           `protobuf:"bytes,1,opt,name=One,proto3" json:"One,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameShowOneResponse) Reset() {
	*x = GameShowOneResponse{}
	mi := &file_facade_admin_resource_game_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameShowOneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameShowOneResponse) ProtoMessage() {}

func (x *GameShowOneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_facade_admin_resource_game_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameShowOneResponse.ProtoReflect.Descriptor instead.
func (*GameShowOneResponse) Descriptor() ([]byte, []int) {
	return file_facade_admin_resource_game_proto_rawDescGZIP(), []int{8}
}

func (x *GameShowOneResponse) GetOne() *facade.Game {
	if x != nil {
		return x.One
	}
	return nil
}

type GameShowOnesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filters       []*facade.Filter       `protobuf:"bytes,1,rep,name=filters,proto3" json:"filters,omitempty"`
	Sorters       []*facade.Sorter       `protobuf:"bytes,2,rep,name=sorters,proto3" json:"sorters,omitempty"`
	Pagination    *facade.Pagination     `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameShowOnesRequest) Reset() {
	*x = GameShowOnesRequest{}
	mi := &file_facade_admin_resource_game_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameShowOnesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameShowOnesRequest) ProtoMessage() {}

func (x *GameShowOnesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_facade_admin_resource_game_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameShowOnesRequest.ProtoReflect.Descriptor instead.
func (*GameShowOnesRequest) Descriptor() ([]byte, []int) {
	return file_facade_admin_resource_game_proto_rawDescGZIP(), []int{9}
}

func (x *GameShowOnesRequest) GetFilters() []*facade.Filter {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *GameShowOnesRequest) GetSorters() []*facade.Sorter {
	if x != nil {
		return x.Sorters
	}
	return nil
}

func (x *GameShowOnesRequest) GetPagination() *facade.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type GameShowOnesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ones          []*facade.Game         `protobuf:"bytes,1,rep,name=Ones,proto3" json:"Ones,omitempty"`
	Total         uint64                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameShowOnesResponse) Reset() {
	*x = GameShowOnesResponse{}
	mi := &file_facade_admin_resource_game_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameShowOnesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameShowOnesResponse) ProtoMessage() {}

func (x *GameShowOnesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_facade_admin_resource_game_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameShowOnesResponse.ProtoReflect.Descriptor instead.
func (*GameShowOnesResponse) Descriptor() ([]byte, []int) {
	return file_facade_admin_resource_game_proto_rawDescGZIP(), []int{10}
}

func (x *GameShowOnesResponse) GetOnes() []*facade.Game {
	if x != nil {
		return x.Ones
	}
	return nil
}

func (x *GameShowOnesResponse) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_facade_admin_resource_game_proto protoreflect.FileDescriptor

const file_facade_admin_resource_game_proto_rawDesc = "" +
	"\n" +
	" facade/admin/resource/game.proto\x12\x18pb.facade.admin.resource\x1a\x13facade/common.proto\"\xbb\x01\n" +
	"\tGameValue\x12%\n" +
	"\fgame_type_id\x18\x01 \x01(\x04H\x00R\n" +
	"gameTypeId\x88\x01\x01\x12\x15\n" +
	"\x03key\x18\x02 \x01(\tH\x01R\x03key\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x03 \x01(\tH\x02R\x04name\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x03R\vdescription\x88\x01\x01B\x0f\n" +
	"\r_game_type_idB\x06\n" +
	"\x04_keyB\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_description\"N\n" +
	"\x11GameAddOneRequest\x129\n" +
	"\x05value\x18\x01 \x01(\v2#.pb.facade.admin.resource.GameValueR\x05value\"\x14\n" +
	"\x12GameAddOneResponse\"|\n" +
	"\x12GameEditOneRequest\x12+\n" +
	"\afilters\x18\x01 \x03(\v2\x11.pb.facade.FilterR\afilters\x129\n" +
	"\x05value\x18\x02 \x01(\v2#.pb.facade.admin.resource.GameValueR\x05value\"\x15\n" +
	"\x13GameEditOneResponse\"C\n" +
	"\x14GameRemoveOneRequest\x12+\n" +
	"\afilters\x18\x01 \x03(\v2\x11.pb.facade.FilterR\afilters\"\x17\n" +
	"\x15GameRemoveOneResponse\"A\n" +
	"\x12GameShowOneRequest\x12+\n" +
	"\afilters\x18\x01 \x03(\v2\x11.pb.facade.FilterR\afilters\"8\n" +
	"\x13GameShowOneResponse\x12!\n" +
	"\x03One\x18\x01 \x01(\v2\x0f.pb.facade.GameR\x03One\"\xa6\x01\n" +
	"\x13GameShowOnesRequest\x12+\n" +
	"\afilters\x18\x01 \x03(\v2\x11.pb.facade.FilterR\afilters\x12+\n" +
	"\asorters\x18\x02 \x03(\v2\x11.pb.facade.SorterR\asorters\x125\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2\x15.pb.facade.PaginationR\n" +
	"pagination\"Q\n" +
	"\x14GameShowOnesResponse\x12#\n" +
	"\x04Ones\x18\x01 \x03(\v2\x0f.pb.facade.GameR\x04Ones\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x04R\x05total2\x9e\x04\n" +
	"\x0eGameController\x12c\n" +
	"\x06AddOne\x12+.pb.facade.admin.resource.GameAddOneRequest\x1a,.pb.facade.admin.resource.GameAddOneResponse\x12f\n" +
	"\aEditOne\x12,.pb.facade.admin.resource.GameEditOneRequest\x1a-.pb.facade.admin.resource.GameEditOneResponse\x12l\n" +
	"\tRemoveOne\x12..pb.facade.admin.resource.GameRemoveOneRequest\x1a/.pb.facade.admin.resource.GameRemoveOneResponse\x12f\n" +
	"\aShowOne\x12,.pb.facade.admin.resource.GameShowOneRequest\x1a-.pb.facade.admin.resource.GameShowOneResponse\x12i\n" +
	"\bShowOnes\x12-.pb.facade.admin.resource.GameShowOnesRequest\x1a..pb.facade.admin.resource.GameShowOnesResponseB\x1cZ\x1a./pb_facade_admin_resourceb\x06proto3"

var (
	file_facade_admin_resource_game_proto_rawDescOnce sync.Once
	file_facade_admin_resource_game_proto_rawDescData []byte
)

func file_facade_admin_resource_game_proto_rawDescGZIP() []byte {
	file_facade_admin_resource_game_proto_rawDescOnce.Do(func() {
		file_facade_admin_resource_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_facade_admin_resource_game_proto_rawDesc), len(file_facade_admin_resource_game_proto_rawDesc)))
	})
	return file_facade_admin_resource_game_proto_rawDescData
}

var file_facade_admin_resource_game_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_facade_admin_resource_game_proto_goTypes = []any{
	(*GameValue)(nil),             // 0: pb.facade.admin.resource.GameValue
	(*GameAddOneRequest)(nil),     // 1: pb.facade.admin.resource.GameAddOneRequest
	(*GameAddOneResponse)(nil),    // 2: pb.facade.admin.resource.GameAddOneResponse
	(*GameEditOneRequest)(nil),    // 3: pb.facade.admin.resource.GameEditOneRequest
	(*GameEditOneResponse)(nil),   // 4: pb.facade.admin.resource.GameEditOneResponse
	(*GameRemoveOneRequest)(nil),  // 5: pb.facade.admin.resource.GameRemoveOneRequest
	(*GameRemoveOneResponse)(nil), // 6: pb.facade.admin.resource.GameRemoveOneResponse
	(*GameShowOneRequest)(nil),    // 7: pb.facade.admin.resource.GameShowOneRequest
	(*GameShowOneResponse)(nil),   // 8: pb.facade.admin.resource.GameShowOneResponse
	(*GameShowOnesRequest)(nil),   // 9: pb.facade.admin.resource.GameShowOnesRequest
	(*GameShowOnesResponse)(nil),  // 10: pb.facade.admin.resource.GameShowOnesResponse
	(*facade.Filter)(nil),         // 11: pb.facade.Filter
	(*facade.Game)(nil),           // 12: pb.facade.Game
	(*facade.Sorter)(nil),         // 13: pb.facade.Sorter
	(*facade.Pagination)(nil),     // 14: pb.facade.Pagination
}
var file_facade_admin_resource_game_proto_depIdxs = []int32{
	0,  // 0: pb.facade.admin.resource.GameAddOneRequest.value:type_name -> pb.facade.admin.resource.GameValue
	11, // 1: pb.facade.admin.resource.GameEditOneRequest.filters:type_name -> pb.facade.Filter
	0,  // 2: pb.facade.admin.resource.GameEditOneRequest.value:type_name -> pb.facade.admin.resource.GameValue
	11, // 3: pb.facade.admin.resource.GameRemoveOneRequest.filters:type_name -> pb.facade.Filter
	11, // 4: pb.facade.admin.resource.GameShowOneRequest.filters:type_name -> pb.facade.Filter
	12, // 5: pb.facade.admin.resource.GameShowOneResponse.One:type_name -> pb.facade.Game
	11, // 6: pb.facade.admin.resource.GameShowOnesRequest.filters:type_name -> pb.facade.Filter
	13, // 7: pb.facade.admin.resource.GameShowOnesRequest.sorters:type_name -> pb.facade.Sorter
	14, // 8: pb.facade.admin.resource.GameShowOnesRequest.pagination:type_name -> pb.facade.Pagination
	12, // 9: pb.facade.admin.resource.GameShowOnesResponse.Ones:type_name -> pb.facade.Game
	1,  // 10: pb.facade.admin.resource.GameController.AddOne:input_type -> pb.facade.admin.resource.GameAddOneRequest
	3,  // 11: pb.facade.admin.resource.GameController.EditOne:input_type -> pb.facade.admin.resource.GameEditOneRequest
	5,  // 12: pb.facade.admin.resource.GameController.RemoveOne:input_type -> pb.facade.admin.resource.GameRemoveOneRequest
	7,  // 13: pb.facade.admin.resource.GameController.ShowOne:input_type -> pb.facade.admin.resource.GameShowOneRequest
	9,  // 14: pb.facade.admin.resource.GameController.ShowOnes:input_type -> pb.facade.admin.resource.GameShowOnesRequest
	2,  // 15: pb.facade.admin.resource.GameController.AddOne:output_type -> pb.facade.admin.resource.GameAddOneResponse
	4,  // 16: pb.facade.admin.resource.GameController.EditOne:output_type -> pb.facade.admin.resource.GameEditOneResponse
	6,  // 17: pb.facade.admin.resource.GameController.RemoveOne:output_type -> pb.facade.admin.resource.GameRemoveOneResponse
	8,  // 18: pb.facade.admin.resource.GameController.ShowOne:output_type -> pb.facade.admin.resource.GameShowOneResponse
	10, // 19: pb.facade.admin.resource.GameController.ShowOnes:output_type -> pb.facade.admin.resource.GameShowOnesResponse
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_facade_admin_resource_game_proto_init() }
func file_facade_admin_resource_game_proto_init() {
	if File_facade_admin_resource_game_proto != nil {
		return
	}
	file_facade_admin_resource_game_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_facade_admin_resource_game_proto_rawDesc), len(file_facade_admin_resource_game_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_facade_admin_resource_game_proto_goTypes,
		DependencyIndexes: file_facade_admin_resource_game_proto_depIdxs,
		MessageInfos:      file_facade_admin_resource_game_proto_msgTypes,
	}.Build()
	File_facade_admin_resource_game_proto = out.File
	file_facade_admin_resource_game_proto_goTypes = nil
	file_facade_admin_resource_game_proto_depIdxs = nil
}
