// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: facade/register/authenticator.proto

package pb_facade_register

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthenticatorSignInRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticatorSignInRequest) Reset() {
	*x = AuthenticatorSignInRequest{}
	mi := &file_facade_register_authenticator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticatorSignInRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticatorSignInRequest) ProtoMessage() {}

func (x *AuthenticatorSignInRequest) ProtoReflect() protoreflect.Message {
	mi := &file_facade_register_authenticator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticatorSignInRequest.ProtoReflect.Descriptor instead.
func (*AuthenticatorSignInRequest) Descriptor() ([]byte, []int) {
	return file_facade_register_authenticator_proto_rawDescGZIP(), []int{0}
}

func (x *AuthenticatorSignInRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type AuthenticatorSignInResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticatorSignInResponse) Reset() {
	*x = AuthenticatorSignInResponse{}
	mi := &file_facade_register_authenticator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticatorSignInResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticatorSignInResponse) ProtoMessage() {}

func (x *AuthenticatorSignInResponse) ProtoReflect() protoreflect.Message {
	mi := &file_facade_register_authenticator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticatorSignInResponse.ProtoReflect.Descriptor instead.
func (*AuthenticatorSignInResponse) Descriptor() ([]byte, []int) {
	return file_facade_register_authenticator_proto_rawDescGZIP(), []int{1}
}

func (x *AuthenticatorSignInResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_facade_register_authenticator_proto protoreflect.FileDescriptor

const file_facade_register_authenticator_proto_rawDesc = "" +
	"\n" +
	"#facade/register/authenticator.proto\x12\x12pb.facade.register\"0\n" +
	"\x1aAuthenticatorSignInRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"1\n" +
	"\x1bAuthenticatorSignInResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name2\x84\x01\n" +
	"\x17AuthenticatorController\x12i\n" +
	"\x06SignIn\x12..pb.facade.register.AuthenticatorSignInRequest\x1a/.pb.facade.register.AuthenticatorSignInResponseB\x16Z\x14./pb_facade_registerb\x06proto3"

var (
	file_facade_register_authenticator_proto_rawDescOnce sync.Once
	file_facade_register_authenticator_proto_rawDescData []byte
)

func file_facade_register_authenticator_proto_rawDescGZIP() []byte {
	file_facade_register_authenticator_proto_rawDescOnce.Do(func() {
		file_facade_register_authenticator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_facade_register_authenticator_proto_rawDesc), len(file_facade_register_authenticator_proto_rawDesc)))
	})
	return file_facade_register_authenticator_proto_rawDescData
}

var file_facade_register_authenticator_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_facade_register_authenticator_proto_goTypes = []any{
	(*AuthenticatorSignInRequest)(nil),  // 0: pb.facade.register.AuthenticatorSignInRequest
	(*AuthenticatorSignInResponse)(nil), // 1: pb.facade.register.AuthenticatorSignInResponse
}
var file_facade_register_authenticator_proto_depIdxs = []int32{
	0, // 0: pb.facade.register.AuthenticatorController.SignIn:input_type -> pb.facade.register.AuthenticatorSignInRequest
	1, // 1: pb.facade.register.AuthenticatorController.SignIn:output_type -> pb.facade.register.AuthenticatorSignInResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_facade_register_authenticator_proto_init() }
func file_facade_register_authenticator_proto_init() {
	if File_facade_register_authenticator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_facade_register_authenticator_proto_rawDesc), len(file_facade_register_authenticator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_facade_register_authenticator_proto_goTypes,
		DependencyIndexes: file_facade_register_authenticator_proto_depIdxs,
		MessageInfos:      file_facade_register_authenticator_proto_msgTypes,
	}.Build()
	File_facade_register_authenticator_proto = out.File
	file_facade_register_authenticator_proto_goTypes = nil
	file_facade_register_authenticator_proto_depIdxs = nil
}
