// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: resource/model/admin_user.proto

package pb_resource_model

import (
	pb "example/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdminUserShowOneByNameInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUserShowOneByNameInput) Reset() {
	*x = AdminUserShowOneByNameInput{}
	mi := &file_resource_model_admin_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUserShowOneByNameInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUserShowOneByNameInput) ProtoMessage() {}

func (x *AdminUserShowOneByNameInput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_admin_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUserShowOneByNameInput.ProtoReflect.Descriptor instead.
func (*AdminUserShowOneByNameInput) Descriptor() ([]byte, []int) {
	return file_resource_model_admin_user_proto_rawDescGZIP(), []int{0}
}

func (x *AdminUserShowOneByNameInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type AdminUserShowOneByNameOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdminUser     *pb.AdminUser          `protobuf:"bytes,1,opt,name=admin_user,json=adminUser,proto3" json:"admin_user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUserShowOneByNameOutput) Reset() {
	*x = AdminUserShowOneByNameOutput{}
	mi := &file_resource_model_admin_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUserShowOneByNameOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUserShowOneByNameOutput) ProtoMessage() {}

func (x *AdminUserShowOneByNameOutput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_admin_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUserShowOneByNameOutput.ProtoReflect.Descriptor instead.
func (*AdminUserShowOneByNameOutput) Descriptor() ([]byte, []int) {
	return file_resource_model_admin_user_proto_rawDescGZIP(), []int{1}
}

func (x *AdminUserShowOneByNameOutput) GetAdminUser() *pb.AdminUser {
	if x != nil {
		return x.AdminUser
	}
	return nil
}

// 數據模型直接對ID查找
type AdminUserShowOneByIdInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUserShowOneByIdInput) Reset() {
	*x = AdminUserShowOneByIdInput{}
	mi := &file_resource_model_admin_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUserShowOneByIdInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUserShowOneByIdInput) ProtoMessage() {}

func (x *AdminUserShowOneByIdInput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_admin_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUserShowOneByIdInput.ProtoReflect.Descriptor instead.
func (*AdminUserShowOneByIdInput) Descriptor() ([]byte, []int) {
	return file_resource_model_admin_user_proto_rawDescGZIP(), []int{2}
}

func (x *AdminUserShowOneByIdInput) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type AdminUserShowOneByIdOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdminUser     *pb.AdminUser          `protobuf:"bytes,1,opt,name=admin_user,json=adminUser,proto3" json:"admin_user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUserShowOneByIdOutput) Reset() {
	*x = AdminUserShowOneByIdOutput{}
	mi := &file_resource_model_admin_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUserShowOneByIdOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUserShowOneByIdOutput) ProtoMessage() {}

func (x *AdminUserShowOneByIdOutput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_admin_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUserShowOneByIdOutput.ProtoReflect.Descriptor instead.
func (*AdminUserShowOneByIdOutput) Descriptor() ([]byte, []int) {
	return file_resource_model_admin_user_proto_rawDescGZIP(), []int{3}
}

func (x *AdminUserShowOneByIdOutput) GetAdminUser() *pb.AdminUser {
	if x != nil {
		return x.AdminUser
	}
	return nil
}

type AdminUserAddOneInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Variable      *pb.AdminUserVariable  `protobuf:"bytes,1,opt,name=variable,proto3" json:"variable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUserAddOneInput) Reset() {
	*x = AdminUserAddOneInput{}
	mi := &file_resource_model_admin_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUserAddOneInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUserAddOneInput) ProtoMessage() {}

func (x *AdminUserAddOneInput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_admin_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUserAddOneInput.ProtoReflect.Descriptor instead.
func (*AdminUserAddOneInput) Descriptor() ([]byte, []int) {
	return file_resource_model_admin_user_proto_rawDescGZIP(), []int{4}
}

func (x *AdminUserAddOneInput) GetVariable() *pb.AdminUserVariable {
	if x != nil {
		return x.Variable
	}
	return nil
}

type AdminUserAddOneOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUserAddOneOutput) Reset() {
	*x = AdminUserAddOneOutput{}
	mi := &file_resource_model_admin_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUserAddOneOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUserAddOneOutput) ProtoMessage() {}

func (x *AdminUserAddOneOutput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_admin_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUserAddOneOutput.ProtoReflect.Descriptor instead.
func (*AdminUserAddOneOutput) Descriptor() ([]byte, []int) {
	return file_resource_model_admin_user_proto_rawDescGZIP(), []int{5}
}

// 數據模型直接對ID查找
type AdminUserEditOneByIdInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Variable      *pb.AdminUserVariable  `protobuf:"bytes,1,opt,name=variable,proto3" json:"variable,omitempty"`
	Id            uint64                 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUserEditOneByIdInput) Reset() {
	*x = AdminUserEditOneByIdInput{}
	mi := &file_resource_model_admin_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUserEditOneByIdInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUserEditOneByIdInput) ProtoMessage() {}

func (x *AdminUserEditOneByIdInput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_admin_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUserEditOneByIdInput.ProtoReflect.Descriptor instead.
func (*AdminUserEditOneByIdInput) Descriptor() ([]byte, []int) {
	return file_resource_model_admin_user_proto_rawDescGZIP(), []int{6}
}

func (x *AdminUserEditOneByIdInput) GetVariable() *pb.AdminUserVariable {
	if x != nil {
		return x.Variable
	}
	return nil
}

func (x *AdminUserEditOneByIdInput) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type AdminUserEditOneByIdOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUserEditOneByIdOutput) Reset() {
	*x = AdminUserEditOneByIdOutput{}
	mi := &file_resource_model_admin_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUserEditOneByIdOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUserEditOneByIdOutput) ProtoMessage() {}

func (x *AdminUserEditOneByIdOutput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_admin_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUserEditOneByIdOutput.ProtoReflect.Descriptor instead.
func (*AdminUserEditOneByIdOutput) Descriptor() ([]byte, []int) {
	return file_resource_model_admin_user_proto_rawDescGZIP(), []int{7}
}

type AdminUserRemoveOneByIdInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUserRemoveOneByIdInput) Reset() {
	*x = AdminUserRemoveOneByIdInput{}
	mi := &file_resource_model_admin_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUserRemoveOneByIdInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUserRemoveOneByIdInput) ProtoMessage() {}

func (x *AdminUserRemoveOneByIdInput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_admin_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUserRemoveOneByIdInput.ProtoReflect.Descriptor instead.
func (*AdminUserRemoveOneByIdInput) Descriptor() ([]byte, []int) {
	return file_resource_model_admin_user_proto_rawDescGZIP(), []int{8}
}

func (x *AdminUserRemoveOneByIdInput) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type AdminUserRemoveOneByIdOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUserRemoveOneByIdOutput) Reset() {
	*x = AdminUserRemoveOneByIdOutput{}
	mi := &file_resource_model_admin_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUserRemoveOneByIdOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUserRemoveOneByIdOutput) ProtoMessage() {}

func (x *AdminUserRemoveOneByIdOutput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_admin_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUserRemoveOneByIdOutput.ProtoReflect.Descriptor instead.
func (*AdminUserRemoveOneByIdOutput) Descriptor() ([]byte, []int) {
	return file_resource_model_admin_user_proto_rawDescGZIP(), []int{9}
}

type AdminUserShowOnesByFiltersWithSortersPaginationInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filters       []*pb.Filter           `protobuf:"bytes,1,rep,name=filters,proto3" json:"filters,omitempty"`
	Sorters       []*pb.Sorter           `protobuf:"bytes,2,rep,name=sorters,proto3" json:"sorters,omitempty"`
	Pagination    *pb.Pagination         `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUserShowOnesByFiltersWithSortersPaginationInput) Reset() {
	*x = AdminUserShowOnesByFiltersWithSortersPaginationInput{}
	mi := &file_resource_model_admin_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUserShowOnesByFiltersWithSortersPaginationInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUserShowOnesByFiltersWithSortersPaginationInput) ProtoMessage() {}

func (x *AdminUserShowOnesByFiltersWithSortersPaginationInput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_admin_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUserShowOnesByFiltersWithSortersPaginationInput.ProtoReflect.Descriptor instead.
func (*AdminUserShowOnesByFiltersWithSortersPaginationInput) Descriptor() ([]byte, []int) {
	return file_resource_model_admin_user_proto_rawDescGZIP(), []int{10}
}

func (x *AdminUserShowOnesByFiltersWithSortersPaginationInput) GetFilters() []*pb.Filter {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *AdminUserShowOnesByFiltersWithSortersPaginationInput) GetSorters() []*pb.Sorter {
	if x != nil {
		return x.Sorters
	}
	return nil
}

func (x *AdminUserShowOnesByFiltersWithSortersPaginationInput) GetPagination() *pb.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type AdminUserShowOnesByFiltersWithSortersPaginationOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdminUsers    []*pb.AdminUser        `protobuf:"bytes,1,rep,name=admin_users,json=adminUsers,proto3" json:"admin_users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUserShowOnesByFiltersWithSortersPaginationOutput) Reset() {
	*x = AdminUserShowOnesByFiltersWithSortersPaginationOutput{}
	mi := &file_resource_model_admin_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUserShowOnesByFiltersWithSortersPaginationOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUserShowOnesByFiltersWithSortersPaginationOutput) ProtoMessage() {}

func (x *AdminUserShowOnesByFiltersWithSortersPaginationOutput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_admin_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUserShowOnesByFiltersWithSortersPaginationOutput.ProtoReflect.Descriptor instead.
func (*AdminUserShowOnesByFiltersWithSortersPaginationOutput) Descriptor() ([]byte, []int) {
	return file_resource_model_admin_user_proto_rawDescGZIP(), []int{11}
}

func (x *AdminUserShowOnesByFiltersWithSortersPaginationOutput) GetAdminUsers() []*pb.AdminUser {
	if x != nil {
		return x.AdminUsers
	}
	return nil
}

type AdminUserTotalByFiltersInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filters       []*pb.Filter           `protobuf:"bytes,1,rep,name=filters,proto3" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUserTotalByFiltersInput) Reset() {
	*x = AdminUserTotalByFiltersInput{}
	mi := &file_resource_model_admin_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUserTotalByFiltersInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUserTotalByFiltersInput) ProtoMessage() {}

func (x *AdminUserTotalByFiltersInput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_admin_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUserTotalByFiltersInput.ProtoReflect.Descriptor instead.
func (*AdminUserTotalByFiltersInput) Descriptor() ([]byte, []int) {
	return file_resource_model_admin_user_proto_rawDescGZIP(), []int{12}
}

func (x *AdminUserTotalByFiltersInput) GetFilters() []*pb.Filter {
	if x != nil {
		return x.Filters
	}
	return nil
}

type AdminUserTotalByFiltersOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         uint64                 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUserTotalByFiltersOutput) Reset() {
	*x = AdminUserTotalByFiltersOutput{}
	mi := &file_resource_model_admin_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUserTotalByFiltersOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUserTotalByFiltersOutput) ProtoMessage() {}

func (x *AdminUserTotalByFiltersOutput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_admin_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUserTotalByFiltersOutput.ProtoReflect.Descriptor instead.
func (*AdminUserTotalByFiltersOutput) Descriptor() ([]byte, []int) {
	return file_resource_model_admin_user_proto_rawDescGZIP(), []int{13}
}

func (x *AdminUserTotalByFiltersOutput) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_resource_model_admin_user_proto protoreflect.FileDescriptor

const file_resource_model_admin_user_proto_rawDesc = "" +
	"\n" +
	"\x1fresource/model/admin_user.proto\x12\x11pb.resource.model\x1a\fcommon.proto\"1\n" +
	"\x1bAdminUserShowOneByNameInput\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"L\n" +
	"\x1cAdminUserShowOneByNameOutput\x12,\n" +
	"\n" +
	"admin_user\x18\x01 \x01(\v2\r.pb.AdminUserR\tadminUser\"+\n" +
	"\x19AdminUserShowOneByIdInput\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"J\n" +
	"\x1aAdminUserShowOneByIdOutput\x12,\n" +
	"\n" +
	"admin_user\x18\x01 \x01(\v2\r.pb.AdminUserR\tadminUser\"I\n" +
	"\x14AdminUserAddOneInput\x121\n" +
	"\bvariable\x18\x01 \x01(\v2\x15.pb.AdminUserVariableR\bvariable\"\x17\n" +
	"\x15AdminUserAddOneOutput\"^\n" +
	"\x19AdminUserEditOneByIdInput\x121\n" +
	"\bvariable\x18\x01 \x01(\v2\x15.pb.AdminUserVariableR\bvariable\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x04R\x02id\"\x1c\n" +
	"\x1aAdminUserEditOneByIdOutput\"-\n" +
	"\x1bAdminUserRemoveOneByIdInput\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"\x1e\n" +
	"\x1cAdminUserRemoveOneByIdOutput\"\xb2\x01\n" +
	"4AdminUserShowOnesByFiltersWithSortersPaginationInput\x12$\n" +
	"\afilters\x18\x01 \x03(\v2\n" +
	".pb.FilterR\afilters\x12$\n" +
	"\asorters\x18\x02 \x03(\v2\n" +
	".pb.SorterR\asorters\x12.\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2\x0e.pb.PaginationR\n" +
	"pagination\"g\n" +
	"5AdminUserShowOnesByFiltersWithSortersPaginationOutput\x12.\n" +
	"\vadmin_users\x18\x01 \x03(\v2\r.pb.AdminUserR\n" +
	"adminUsers\"D\n" +
	"\x1cAdminUserTotalByFiltersInput\x12$\n" +
	"\afilters\x18\x01 \x03(\v2\n" +
	".pb.FilterR\afilters\"5\n" +
	"\x1dAdminUserTotalByFiltersOutput\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x04R\x05total2\xdc\x06\n" +
	"\x0eAdminUserModel\x12p\n" +
	"\rShowOneByName\x12..pb.resource.model.AdminUserShowOneByNameInput\x1a/.pb.resource.model.AdminUserShowOneByNameOutput\x12j\n" +
	"\vShowOneById\x12,.pb.resource.model.AdminUserShowOneByIdInput\x1a-.pb.resource.model.AdminUserShowOneByIdOutput\x12[\n" +
	"\x06AddOne\x12'.pb.resource.model.AdminUserAddOneInput\x1a(.pb.resource.model.AdminUserAddOneOutput\x12j\n" +
	"\vEditOneById\x12,.pb.resource.model.AdminUserEditOneByIdInput\x1a-.pb.resource.model.AdminUserEditOneByIdOutput\x12p\n" +
	"\rRemoveOneById\x12..pb.resource.model.AdminUserRemoveOneByIdInput\x1a/.pb.resource.model.AdminUserRemoveOneByIdOutput\x12\xbb\x01\n" +
	"&ShowOnesByFiltersWithSortersPagination\x12G.pb.resource.model.AdminUserShowOnesByFiltersWithSortersPaginationInput\x1aH.pb.resource.model.AdminUserShowOnesByFiltersWithSortersPaginationOutput\x12s\n" +
	"\x0eTotalByFilters\x12/.pb.resource.model.AdminUserTotalByFiltersInput\x1a0.pb.resource.model.AdminUserTotalByFiltersOutputB\x15Z\x13./pb_resource_modelb\x06proto3"

var (
	file_resource_model_admin_user_proto_rawDescOnce sync.Once
	file_resource_model_admin_user_proto_rawDescData []byte
)

func file_resource_model_admin_user_proto_rawDescGZIP() []byte {
	file_resource_model_admin_user_proto_rawDescOnce.Do(func() {
		file_resource_model_admin_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_resource_model_admin_user_proto_rawDesc), len(file_resource_model_admin_user_proto_rawDesc)))
	})
	return file_resource_model_admin_user_proto_rawDescData
}

var file_resource_model_admin_user_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_resource_model_admin_user_proto_goTypes = []any{
	(*AdminUserShowOneByNameInput)(nil),                           // 0: pb.resource.model.AdminUserShowOneByNameInput
	(*AdminUserShowOneByNameOutput)(nil),                          // 1: pb.resource.model.AdminUserShowOneByNameOutput
	(*AdminUserShowOneByIdInput)(nil),                             // 2: pb.resource.model.AdminUserShowOneByIdInput
	(*AdminUserShowOneByIdOutput)(nil),                            // 3: pb.resource.model.AdminUserShowOneByIdOutput
	(*AdminUserAddOneInput)(nil),                                  // 4: pb.resource.model.AdminUserAddOneInput
	(*AdminUserAddOneOutput)(nil),                                 // 5: pb.resource.model.AdminUserAddOneOutput
	(*AdminUserEditOneByIdInput)(nil),                             // 6: pb.resource.model.AdminUserEditOneByIdInput
	(*AdminUserEditOneByIdOutput)(nil),                            // 7: pb.resource.model.AdminUserEditOneByIdOutput
	(*AdminUserRemoveOneByIdInput)(nil),                           // 8: pb.resource.model.AdminUserRemoveOneByIdInput
	(*AdminUserRemoveOneByIdOutput)(nil),                          // 9: pb.resource.model.AdminUserRemoveOneByIdOutput
	(*AdminUserShowOnesByFiltersWithSortersPaginationInput)(nil),  // 10: pb.resource.model.AdminUserShowOnesByFiltersWithSortersPaginationInput
	(*AdminUserShowOnesByFiltersWithSortersPaginationOutput)(nil), // 11: pb.resource.model.AdminUserShowOnesByFiltersWithSortersPaginationOutput
	(*AdminUserTotalByFiltersInput)(nil),                          // 12: pb.resource.model.AdminUserTotalByFiltersInput
	(*AdminUserTotalByFiltersOutput)(nil),                         // 13: pb.resource.model.AdminUserTotalByFiltersOutput
	(*pb.AdminUser)(nil),                                          // 14: pb.AdminUser
	(*pb.AdminUserVariable)(nil),                                  // 15: pb.AdminUserVariable
	(*pb.Filter)(nil),                                             // 16: pb.Filter
	(*pb.Sorter)(nil),                                             // 17: pb.Sorter
	(*pb.Pagination)(nil),                                         // 18: pb.Pagination
}
var file_resource_model_admin_user_proto_depIdxs = []int32{
	14, // 0: pb.resource.model.AdminUserShowOneByNameOutput.admin_user:type_name -> pb.AdminUser
	14, // 1: pb.resource.model.AdminUserShowOneByIdOutput.admin_user:type_name -> pb.AdminUser
	15, // 2: pb.resource.model.AdminUserAddOneInput.variable:type_name -> pb.AdminUserVariable
	15, // 3: pb.resource.model.AdminUserEditOneByIdInput.variable:type_name -> pb.AdminUserVariable
	16, // 4: pb.resource.model.AdminUserShowOnesByFiltersWithSortersPaginationInput.filters:type_name -> pb.Filter
	17, // 5: pb.resource.model.AdminUserShowOnesByFiltersWithSortersPaginationInput.sorters:type_name -> pb.Sorter
	18, // 6: pb.resource.model.AdminUserShowOnesByFiltersWithSortersPaginationInput.pagination:type_name -> pb.Pagination
	14, // 7: pb.resource.model.AdminUserShowOnesByFiltersWithSortersPaginationOutput.admin_users:type_name -> pb.AdminUser
	16, // 8: pb.resource.model.AdminUserTotalByFiltersInput.filters:type_name -> pb.Filter
	0,  // 9: pb.resource.model.AdminUserModel.ShowOneByName:input_type -> pb.resource.model.AdminUserShowOneByNameInput
	2,  // 10: pb.resource.model.AdminUserModel.ShowOneById:input_type -> pb.resource.model.AdminUserShowOneByIdInput
	4,  // 11: pb.resource.model.AdminUserModel.AddOne:input_type -> pb.resource.model.AdminUserAddOneInput
	6,  // 12: pb.resource.model.AdminUserModel.EditOneById:input_type -> pb.resource.model.AdminUserEditOneByIdInput
	8,  // 13: pb.resource.model.AdminUserModel.RemoveOneById:input_type -> pb.resource.model.AdminUserRemoveOneByIdInput
	10, // 14: pb.resource.model.AdminUserModel.ShowOnesByFiltersWithSortersPagination:input_type -> pb.resource.model.AdminUserShowOnesByFiltersWithSortersPaginationInput
	12, // 15: pb.resource.model.AdminUserModel.TotalByFilters:input_type -> pb.resource.model.AdminUserTotalByFiltersInput
	1,  // 16: pb.resource.model.AdminUserModel.ShowOneByName:output_type -> pb.resource.model.AdminUserShowOneByNameOutput
	3,  // 17: pb.resource.model.AdminUserModel.ShowOneById:output_type -> pb.resource.model.AdminUserShowOneByIdOutput
	5,  // 18: pb.resource.model.AdminUserModel.AddOne:output_type -> pb.resource.model.AdminUserAddOneOutput
	7,  // 19: pb.resource.model.AdminUserModel.EditOneById:output_type -> pb.resource.model.AdminUserEditOneByIdOutput
	9,  // 20: pb.resource.model.AdminUserModel.RemoveOneById:output_type -> pb.resource.model.AdminUserRemoveOneByIdOutput
	11, // 21: pb.resource.model.AdminUserModel.ShowOnesByFiltersWithSortersPagination:output_type -> pb.resource.model.AdminUserShowOnesByFiltersWithSortersPaginationOutput
	13, // 22: pb.resource.model.AdminUserModel.TotalByFilters:output_type -> pb.resource.model.AdminUserTotalByFiltersOutput
	16, // [16:23] is the sub-list for method output_type
	9,  // [9:16] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_resource_model_admin_user_proto_init() }
func file_resource_model_admin_user_proto_init() {
	if File_resource_model_admin_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_resource_model_admin_user_proto_rawDesc), len(file_resource_model_admin_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_resource_model_admin_user_proto_goTypes,
		DependencyIndexes: file_resource_model_admin_user_proto_depIdxs,
		MessageInfos:      file_resource_model_admin_user_proto_msgTypes,
	}.Build()
	File_resource_model_admin_user_proto = out.File
	file_resource_model_admin_user_proto_goTypes = nil
	file_resource_model_admin_user_proto_depIdxs = nil
}
