// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: resource/model/admin_permission.proto

package pb_resource_model

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdminPermissionModel_AddOne_FullMethodName                                 = "/pb.resource.model.AdminPermissionModel/AddOne"
	AdminPermissionModel_ShowOneById_FullMethodName                            = "/pb.resource.model.AdminPermissionModel/ShowOneById"
	AdminPermissionModel_EditOneById_FullMethodName                            = "/pb.resource.model.AdminPermissionModel/EditOneById"
	AdminPermissionModel_RemoveOneById_FullMethodName                          = "/pb.resource.model.AdminPermissionModel/RemoveOneById"
	AdminPermissionModel_ShowOnesByFiltersWithSortersPagination_FullMethodName = "/pb.resource.model.AdminPermissionModel/ShowOnesByFiltersWithSortersPagination"
	AdminPermissionModel_TotalByFilters_FullMethodName                         = "/pb.resource.model.AdminPermissionModel/TotalByFilters"
)

// AdminPermissionModelClient is the client API for AdminPermissionModel service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminPermissionModelClient interface {
	AddOne(ctx context.Context, in *AdminPermissionAddOneInput, opts ...grpc.CallOption) (*AdminPermissionAddOneOutput, error)
	ShowOneById(ctx context.Context, in *AdminPermissionShowOneByIdInput, opts ...grpc.CallOption) (*AdminPermissionShowOneByIdOutput, error)
	EditOneById(ctx context.Context, in *AdminPermissionEditOneByIdInput, opts ...grpc.CallOption) (*AdminPermissionEditOneByIdOutput, error)
	RemoveOneById(ctx context.Context, in *AdminPermissionRemoveOneByIdInput, opts ...grpc.CallOption) (*AdminPermissionRemoveOneByIdOutput, error)
	ShowOnesByFiltersWithSortersPagination(ctx context.Context, in *AdminPermissionShowOnesByFiltersWithSortersPaginationInput, opts ...grpc.CallOption) (*AdminPermissionShowOnesByFiltersWithSortersPaginationOutput, error)
	TotalByFilters(ctx context.Context, in *AdminPermissionTotalByFiltersInput, opts ...grpc.CallOption) (*AdminPermissionTotalByFiltersOutput, error)
}

type adminPermissionModelClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminPermissionModelClient(cc grpc.ClientConnInterface) AdminPermissionModelClient {
	return &adminPermissionModelClient{cc}
}

func (c *adminPermissionModelClient) AddOne(ctx context.Context, in *AdminPermissionAddOneInput, opts ...grpc.CallOption) (*AdminPermissionAddOneOutput, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminPermissionAddOneOutput)
	err := c.cc.Invoke(ctx, AdminPermissionModel_AddOne_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminPermissionModelClient) ShowOneById(ctx context.Context, in *AdminPermissionShowOneByIdInput, opts ...grpc.CallOption) (*AdminPermissionShowOneByIdOutput, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminPermissionShowOneByIdOutput)
	err := c.cc.Invoke(ctx, AdminPermissionModel_ShowOneById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminPermissionModelClient) EditOneById(ctx context.Context, in *AdminPermissionEditOneByIdInput, opts ...grpc.CallOption) (*AdminPermissionEditOneByIdOutput, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminPermissionEditOneByIdOutput)
	err := c.cc.Invoke(ctx, AdminPermissionModel_EditOneById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminPermissionModelClient) RemoveOneById(ctx context.Context, in *AdminPermissionRemoveOneByIdInput, opts ...grpc.CallOption) (*AdminPermissionRemoveOneByIdOutput, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminPermissionRemoveOneByIdOutput)
	err := c.cc.Invoke(ctx, AdminPermissionModel_RemoveOneById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminPermissionModelClient) ShowOnesByFiltersWithSortersPagination(ctx context.Context, in *AdminPermissionShowOnesByFiltersWithSortersPaginationInput, opts ...grpc.CallOption) (*AdminPermissionShowOnesByFiltersWithSortersPaginationOutput, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminPermissionShowOnesByFiltersWithSortersPaginationOutput)
	err := c.cc.Invoke(ctx, AdminPermissionModel_ShowOnesByFiltersWithSortersPagination_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminPermissionModelClient) TotalByFilters(ctx context.Context, in *AdminPermissionTotalByFiltersInput, opts ...grpc.CallOption) (*AdminPermissionTotalByFiltersOutput, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminPermissionTotalByFiltersOutput)
	err := c.cc.Invoke(ctx, AdminPermissionModel_TotalByFilters_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminPermissionModelServer is the server API for AdminPermissionModel service.
// All implementations must embed UnimplementedAdminPermissionModelServer
// for forward compatibility.
type AdminPermissionModelServer interface {
	AddOne(context.Context, *AdminPermissionAddOneInput) (*AdminPermissionAddOneOutput, error)
	ShowOneById(context.Context, *AdminPermissionShowOneByIdInput) (*AdminPermissionShowOneByIdOutput, error)
	EditOneById(context.Context, *AdminPermissionEditOneByIdInput) (*AdminPermissionEditOneByIdOutput, error)
	RemoveOneById(context.Context, *AdminPermissionRemoveOneByIdInput) (*AdminPermissionRemoveOneByIdOutput, error)
	ShowOnesByFiltersWithSortersPagination(context.Context, *AdminPermissionShowOnesByFiltersWithSortersPaginationInput) (*AdminPermissionShowOnesByFiltersWithSortersPaginationOutput, error)
	TotalByFilters(context.Context, *AdminPermissionTotalByFiltersInput) (*AdminPermissionTotalByFiltersOutput, error)
	mustEmbedUnimplementedAdminPermissionModelServer()
}

// UnimplementedAdminPermissionModelServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminPermissionModelServer struct{}

func (UnimplementedAdminPermissionModelServer) AddOne(context.Context, *AdminPermissionAddOneInput) (*AdminPermissionAddOneOutput, error) {
	return nil, status.Error(codes.Unimplemented, "method AddOne not implemented")
}
func (UnimplementedAdminPermissionModelServer) ShowOneById(context.Context, *AdminPermissionShowOneByIdInput) (*AdminPermissionShowOneByIdOutput, error) {
	return nil, status.Error(codes.Unimplemented, "method ShowOneById not implemented")
}
func (UnimplementedAdminPermissionModelServer) EditOneById(context.Context, *AdminPermissionEditOneByIdInput) (*AdminPermissionEditOneByIdOutput, error) {
	return nil, status.Error(codes.Unimplemented, "method EditOneById not implemented")
}
func (UnimplementedAdminPermissionModelServer) RemoveOneById(context.Context, *AdminPermissionRemoveOneByIdInput) (*AdminPermissionRemoveOneByIdOutput, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveOneById not implemented")
}
func (UnimplementedAdminPermissionModelServer) ShowOnesByFiltersWithSortersPagination(context.Context, *AdminPermissionShowOnesByFiltersWithSortersPaginationInput) (*AdminPermissionShowOnesByFiltersWithSortersPaginationOutput, error) {
	return nil, status.Error(codes.Unimplemented, "method ShowOnesByFiltersWithSortersPagination not implemented")
}
func (UnimplementedAdminPermissionModelServer) TotalByFilters(context.Context, *AdminPermissionTotalByFiltersInput) (*AdminPermissionTotalByFiltersOutput, error) {
	return nil, status.Error(codes.Unimplemented, "method TotalByFilters not implemented")
}
func (UnimplementedAdminPermissionModelServer) mustEmbedUnimplementedAdminPermissionModelServer() {}
func (UnimplementedAdminPermissionModelServer) testEmbeddedByValue()                              {}

// UnsafeAdminPermissionModelServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminPermissionModelServer will
// result in compilation errors.
type UnsafeAdminPermissionModelServer interface {
	mustEmbedUnimplementedAdminPermissionModelServer()
}

func RegisterAdminPermissionModelServer(s grpc.ServiceRegistrar, srv AdminPermissionModelServer) {
	// If the following call panics, it indicates UnimplementedAdminPermissionModelServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminPermissionModel_ServiceDesc, srv)
}

func _AdminPermissionModel_AddOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminPermissionAddOneInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminPermissionModelServer).AddOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminPermissionModel_AddOne_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminPermissionModelServer).AddOne(ctx, req.(*AdminPermissionAddOneInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminPermissionModel_ShowOneById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminPermissionShowOneByIdInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminPermissionModelServer).ShowOneById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminPermissionModel_ShowOneById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminPermissionModelServer).ShowOneById(ctx, req.(*AdminPermissionShowOneByIdInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminPermissionModel_EditOneById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminPermissionEditOneByIdInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminPermissionModelServer).EditOneById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminPermissionModel_EditOneById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminPermissionModelServer).EditOneById(ctx, req.(*AdminPermissionEditOneByIdInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminPermissionModel_RemoveOneById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminPermissionRemoveOneByIdInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminPermissionModelServer).RemoveOneById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminPermissionModel_RemoveOneById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminPermissionModelServer).RemoveOneById(ctx, req.(*AdminPermissionRemoveOneByIdInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminPermissionModel_ShowOnesByFiltersWithSortersPagination_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminPermissionShowOnesByFiltersWithSortersPaginationInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminPermissionModelServer).ShowOnesByFiltersWithSortersPagination(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminPermissionModel_ShowOnesByFiltersWithSortersPagination_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminPermissionModelServer).ShowOnesByFiltersWithSortersPagination(ctx, req.(*AdminPermissionShowOnesByFiltersWithSortersPaginationInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminPermissionModel_TotalByFilters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminPermissionTotalByFiltersInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminPermissionModelServer).TotalByFilters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminPermissionModel_TotalByFilters_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminPermissionModelServer).TotalByFilters(ctx, req.(*AdminPermissionTotalByFiltersInput))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminPermissionModel_ServiceDesc is the grpc.ServiceDesc for AdminPermissionModel service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminPermissionModel_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.resource.model.AdminPermissionModel",
	HandlerType: (*AdminPermissionModelServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddOne",
			Handler:    _AdminPermissionModel_AddOne_Handler,
		},
		{
			MethodName: "ShowOneById",
			Handler:    _AdminPermissionModel_ShowOneById_Handler,
		},
		{
			MethodName: "EditOneById",
			Handler:    _AdminPermissionModel_EditOneById_Handler,
		},
		{
			MethodName: "RemoveOneById",
			Handler:    _AdminPermissionModel_RemoveOneById_Handler,
		},
		{
			MethodName: "ShowOnesByFiltersWithSortersPagination",
			Handler:    _AdminPermissionModel_ShowOnesByFiltersWithSortersPagination_Handler,
		},
		{
			MethodName: "TotalByFilters",
			Handler:    _AdminPermissionModel_TotalByFilters_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "resource/model/admin_permission.proto",
}
