// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: resource/model/admin_permission.proto

package pb_resource_model

import (
	resource "example/pb/resource"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdminPermissionVariable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *uint64                `protobuf:"varint,1,opt,name=type,proto3,oneof" json:"type,omitempty"`
	Key           *string                `protobuf:"bytes,2,opt,name=key,proto3,oneof" json:"key,omitempty"`
	Name          *string                `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminPermissionVariable) Reset() {
	*x = AdminPermissionVariable{}
	mi := &file_resource_model_admin_permission_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminPermissionVariable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminPermissionVariable) ProtoMessage() {}

func (x *AdminPermissionVariable) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_admin_permission_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminPermissionVariable.ProtoReflect.Descriptor instead.
func (*AdminPermissionVariable) Descriptor() ([]byte, []int) {
	return file_resource_model_admin_permission_proto_rawDescGZIP(), []int{0}
}

func (x *AdminPermissionVariable) GetType() uint64 {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return 0
}

func (x *AdminPermissionVariable) GetKey() string {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return ""
}

func (x *AdminPermissionVariable) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

type AdminPermissionAddOneInput struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Variable      *AdminPermissionVariable `protobuf:"bytes,1,opt,name=variable,proto3" json:"variable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminPermissionAddOneInput) Reset() {
	*x = AdminPermissionAddOneInput{}
	mi := &file_resource_model_admin_permission_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminPermissionAddOneInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminPermissionAddOneInput) ProtoMessage() {}

func (x *AdminPermissionAddOneInput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_admin_permission_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminPermissionAddOneInput.ProtoReflect.Descriptor instead.
func (*AdminPermissionAddOneInput) Descriptor() ([]byte, []int) {
	return file_resource_model_admin_permission_proto_rawDescGZIP(), []int{1}
}

func (x *AdminPermissionAddOneInput) GetVariable() *AdminPermissionVariable {
	if x != nil {
		return x.Variable
	}
	return nil
}

type AdminPermissionAddOneOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminPermissionAddOneOutput) Reset() {
	*x = AdminPermissionAddOneOutput{}
	mi := &file_resource_model_admin_permission_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminPermissionAddOneOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminPermissionAddOneOutput) ProtoMessage() {}

func (x *AdminPermissionAddOneOutput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_admin_permission_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminPermissionAddOneOutput.ProtoReflect.Descriptor instead.
func (*AdminPermissionAddOneOutput) Descriptor() ([]byte, []int) {
	return file_resource_model_admin_permission_proto_rawDescGZIP(), []int{2}
}

func (x *AdminPermissionAddOneOutput) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type AdminPermissionShowOneByIdInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminPermissionShowOneByIdInput) Reset() {
	*x = AdminPermissionShowOneByIdInput{}
	mi := &file_resource_model_admin_permission_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminPermissionShowOneByIdInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminPermissionShowOneByIdInput) ProtoMessage() {}

func (x *AdminPermissionShowOneByIdInput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_admin_permission_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminPermissionShowOneByIdInput.ProtoReflect.Descriptor instead.
func (*AdminPermissionShowOneByIdInput) Descriptor() ([]byte, []int) {
	return file_resource_model_admin_permission_proto_rawDescGZIP(), []int{3}
}

func (x *AdminPermissionShowOneByIdInput) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type AdminPermissionShowOneByIdOutput struct {
	state           protoimpl.MessageState    `protogen:"open.v1"`
	AdminPermission *resource.AdminPermission `protobuf:"bytes,1,opt,name=admin_permission,json=adminPermission,proto3" json:"admin_permission,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AdminPermissionShowOneByIdOutput) Reset() {
	*x = AdminPermissionShowOneByIdOutput{}
	mi := &file_resource_model_admin_permission_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminPermissionShowOneByIdOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminPermissionShowOneByIdOutput) ProtoMessage() {}

func (x *AdminPermissionShowOneByIdOutput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_admin_permission_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminPermissionShowOneByIdOutput.ProtoReflect.Descriptor instead.
func (*AdminPermissionShowOneByIdOutput) Descriptor() ([]byte, []int) {
	return file_resource_model_admin_permission_proto_rawDescGZIP(), []int{4}
}

func (x *AdminPermissionShowOneByIdOutput) GetAdminPermission() *resource.AdminPermission {
	if x != nil {
		return x.AdminPermission
	}
	return nil
}

type AdminPermissionEditOneByIdInput struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Variable      *AdminPermissionVariable `protobuf:"bytes,1,opt,name=variable,proto3" json:"variable,omitempty"`
	Id            uint64                   `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminPermissionEditOneByIdInput) Reset() {
	*x = AdminPermissionEditOneByIdInput{}
	mi := &file_resource_model_admin_permission_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminPermissionEditOneByIdInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminPermissionEditOneByIdInput) ProtoMessage() {}

func (x *AdminPermissionEditOneByIdInput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_admin_permission_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminPermissionEditOneByIdInput.ProtoReflect.Descriptor instead.
func (*AdminPermissionEditOneByIdInput) Descriptor() ([]byte, []int) {
	return file_resource_model_admin_permission_proto_rawDescGZIP(), []int{5}
}

func (x *AdminPermissionEditOneByIdInput) GetVariable() *AdminPermissionVariable {
	if x != nil {
		return x.Variable
	}
	return nil
}

func (x *AdminPermissionEditOneByIdInput) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type AdminPermissionEditOneByIdOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminPermissionEditOneByIdOutput) Reset() {
	*x = AdminPermissionEditOneByIdOutput{}
	mi := &file_resource_model_admin_permission_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminPermissionEditOneByIdOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminPermissionEditOneByIdOutput) ProtoMessage() {}

func (x *AdminPermissionEditOneByIdOutput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_admin_permission_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminPermissionEditOneByIdOutput.ProtoReflect.Descriptor instead.
func (*AdminPermissionEditOneByIdOutput) Descriptor() ([]byte, []int) {
	return file_resource_model_admin_permission_proto_rawDescGZIP(), []int{6}
}

func (x *AdminPermissionEditOneByIdOutput) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type AdminPermissionRemoveOneByIdInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminPermissionRemoveOneByIdInput) Reset() {
	*x = AdminPermissionRemoveOneByIdInput{}
	mi := &file_resource_model_admin_permission_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminPermissionRemoveOneByIdInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminPermissionRemoveOneByIdInput) ProtoMessage() {}

func (x *AdminPermissionRemoveOneByIdInput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_admin_permission_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminPermissionRemoveOneByIdInput.ProtoReflect.Descriptor instead.
func (*AdminPermissionRemoveOneByIdInput) Descriptor() ([]byte, []int) {
	return file_resource_model_admin_permission_proto_rawDescGZIP(), []int{7}
}

func (x *AdminPermissionRemoveOneByIdInput) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type AdminPermissionRemoveOneByIdOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminPermissionRemoveOneByIdOutput) Reset() {
	*x = AdminPermissionRemoveOneByIdOutput{}
	mi := &file_resource_model_admin_permission_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminPermissionRemoveOneByIdOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminPermissionRemoveOneByIdOutput) ProtoMessage() {}

func (x *AdminPermissionRemoveOneByIdOutput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_admin_permission_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminPermissionRemoveOneByIdOutput.ProtoReflect.Descriptor instead.
func (*AdminPermissionRemoveOneByIdOutput) Descriptor() ([]byte, []int) {
	return file_resource_model_admin_permission_proto_rawDescGZIP(), []int{8}
}

func (x *AdminPermissionRemoveOneByIdOutput) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type AdminPermissionShowOnesByFiltersWithSortersPaginationInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filters       []*resource.Filter     `protobuf:"bytes,1,rep,name=filters,proto3" json:"filters,omitempty"`
	Sorters       []*resource.Sorter     `protobuf:"bytes,2,rep,name=sorters,proto3" json:"sorters,omitempty"`
	Pagination    *resource.Pagination   `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminPermissionShowOnesByFiltersWithSortersPaginationInput) Reset() {
	*x = AdminPermissionShowOnesByFiltersWithSortersPaginationInput{}
	mi := &file_resource_model_admin_permission_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminPermissionShowOnesByFiltersWithSortersPaginationInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminPermissionShowOnesByFiltersWithSortersPaginationInput) ProtoMessage() {}

func (x *AdminPermissionShowOnesByFiltersWithSortersPaginationInput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_admin_permission_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminPermissionShowOnesByFiltersWithSortersPaginationInput.ProtoReflect.Descriptor instead.
func (*AdminPermissionShowOnesByFiltersWithSortersPaginationInput) Descriptor() ([]byte, []int) {
	return file_resource_model_admin_permission_proto_rawDescGZIP(), []int{9}
}

func (x *AdminPermissionShowOnesByFiltersWithSortersPaginationInput) GetFilters() []*resource.Filter {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *AdminPermissionShowOnesByFiltersWithSortersPaginationInput) GetSorters() []*resource.Sorter {
	if x != nil {
		return x.Sorters
	}
	return nil
}

func (x *AdminPermissionShowOnesByFiltersWithSortersPaginationInput) GetPagination() *resource.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type AdminPermissionShowOnesByFiltersWithSortersPaginationOutput struct {
	state            protoimpl.MessageState      `protogen:"open.v1"`
	AdminPermissions []*resource.AdminPermission `protobuf:"bytes,1,rep,name=admin_permissions,json=adminPermissions,proto3" json:"admin_permissions,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AdminPermissionShowOnesByFiltersWithSortersPaginationOutput) Reset() {
	*x = AdminPermissionShowOnesByFiltersWithSortersPaginationOutput{}
	mi := &file_resource_model_admin_permission_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminPermissionShowOnesByFiltersWithSortersPaginationOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminPermissionShowOnesByFiltersWithSortersPaginationOutput) ProtoMessage() {}

func (x *AdminPermissionShowOnesByFiltersWithSortersPaginationOutput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_admin_permission_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminPermissionShowOnesByFiltersWithSortersPaginationOutput.ProtoReflect.Descriptor instead.
func (*AdminPermissionShowOnesByFiltersWithSortersPaginationOutput) Descriptor() ([]byte, []int) {
	return file_resource_model_admin_permission_proto_rawDescGZIP(), []int{10}
}

func (x *AdminPermissionShowOnesByFiltersWithSortersPaginationOutput) GetAdminPermissions() []*resource.AdminPermission {
	if x != nil {
		return x.AdminPermissions
	}
	return nil
}

type AdminPermissionTotalByFiltersInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filters       []*resource.Filter     `protobuf:"bytes,1,rep,name=filters,proto3" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminPermissionTotalByFiltersInput) Reset() {
	*x = AdminPermissionTotalByFiltersInput{}
	mi := &file_resource_model_admin_permission_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminPermissionTotalByFiltersInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminPermissionTotalByFiltersInput) ProtoMessage() {}

func (x *AdminPermissionTotalByFiltersInput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_admin_permission_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminPermissionTotalByFiltersInput.ProtoReflect.Descriptor instead.
func (*AdminPermissionTotalByFiltersInput) Descriptor() ([]byte, []int) {
	return file_resource_model_admin_permission_proto_rawDescGZIP(), []int{11}
}

func (x *AdminPermissionTotalByFiltersInput) GetFilters() []*resource.Filter {
	if x != nil {
		return x.Filters
	}
	return nil
}

type AdminPermissionTotalByFiltersOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         uint64                 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminPermissionTotalByFiltersOutput) Reset() {
	*x = AdminPermissionTotalByFiltersOutput{}
	mi := &file_resource_model_admin_permission_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminPermissionTotalByFiltersOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminPermissionTotalByFiltersOutput) ProtoMessage() {}

func (x *AdminPermissionTotalByFiltersOutput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_admin_permission_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminPermissionTotalByFiltersOutput.ProtoReflect.Descriptor instead.
func (*AdminPermissionTotalByFiltersOutput) Descriptor() ([]byte, []int) {
	return file_resource_model_admin_permission_proto_rawDescGZIP(), []int{12}
}

func (x *AdminPermissionTotalByFiltersOutput) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_resource_model_admin_permission_proto protoreflect.FileDescriptor

const file_resource_model_admin_permission_proto_rawDesc = "" +
	"\n" +
	"%resource/model/admin_permission.proto\x12\x11pb.resource.model\x1a\x15resource/common.proto\"|\n" +
	"\x17AdminPermissionVariable\x12\x17\n" +
	"\x04type\x18\x01 \x01(\x04H\x00R\x04type\x88\x01\x01\x12\x15\n" +
	"\x03key\x18\x02 \x01(\tH\x01R\x03key\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x03 \x01(\tH\x02R\x04name\x88\x01\x01B\a\n" +
	"\x05_typeB\x06\n" +
	"\x04_keyB\a\n" +
	"\x05_name\"d\n" +
	"\x1aAdminPermissionAddOneInput\x12F\n" +
	"\bvariable\x18\x01 \x01(\v2*.pb.resource.model.AdminPermissionVariableR\bvariable\"5\n" +
	"\x1bAdminPermissionAddOneOutput\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\"1\n" +
	"\x1fAdminPermissionShowOneByIdInput\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"k\n" +
	" AdminPermissionShowOneByIdOutput\x12G\n" +
	"\x10admin_permission\x18\x01 \x01(\v2\x1c.pb.resource.AdminPermissionR\x0fadminPermission\"y\n" +
	"\x1fAdminPermissionEditOneByIdInput\x12F\n" +
	"\bvariable\x18\x01 \x01(\v2*.pb.resource.model.AdminPermissionVariableR\bvariable\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x04R\x02id\":\n" +
	" AdminPermissionEditOneByIdOutput\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\"3\n" +
	"!AdminPermissionRemoveOneByIdInput\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"<\n" +
	"\"AdminPermissionRemoveOneByIdOutput\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\"\xd3\x01\n" +
	":AdminPermissionShowOnesByFiltersWithSortersPaginationInput\x12-\n" +
	"\afilters\x18\x01 \x03(\v2\x13.pb.resource.FilterR\afilters\x12-\n" +
	"\asorters\x18\x02 \x03(\v2\x13.pb.resource.SorterR\asorters\x127\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2\x17.pb.resource.PaginationR\n" +
	"pagination\"\x88\x01\n" +
	";AdminPermissionShowOnesByFiltersWithSortersPaginationOutput\x12I\n" +
	"\x11admin_permissions\x18\x01 \x03(\v2\x1c.pb.resource.AdminPermissionR\x10adminPermissions\"S\n" +
	"\"AdminPermissionTotalByFiltersInput\x12-\n" +
	"\afilters\x18\x01 \x03(\v2\x13.pb.resource.FilterR\afilters\";\n" +
	"#AdminPermissionTotalByFiltersOutput\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x04R\x05total2\xb8\x06\n" +
	"\x14AdminPermissionModel\x12g\n" +
	"\x06AddOne\x12-.pb.resource.model.AdminPermissionAddOneInput\x1a..pb.resource.model.AdminPermissionAddOneOutput\x12v\n" +
	"\vShowOneById\x122.pb.resource.model.AdminPermissionShowOneByIdInput\x1a3.pb.resource.model.AdminPermissionShowOneByIdOutput\x12v\n" +
	"\vEditOneById\x122.pb.resource.model.AdminPermissionEditOneByIdInput\x1a3.pb.resource.model.AdminPermissionEditOneByIdOutput\x12|\n" +
	"\rRemoveOneById\x124.pb.resource.model.AdminPermissionRemoveOneByIdInput\x1a5.pb.resource.model.AdminPermissionRemoveOneByIdOutput\x12\xc7\x01\n" +
	"&ShowOnesByFiltersWithSortersPagination\x12M.pb.resource.model.AdminPermissionShowOnesByFiltersWithSortersPaginationInput\x1aN.pb.resource.model.AdminPermissionShowOnesByFiltersWithSortersPaginationOutput\x12\x7f\n" +
	"\x0eTotalByFilters\x125.pb.resource.model.AdminPermissionTotalByFiltersInput\x1a6.pb.resource.model.AdminPermissionTotalByFiltersOutputB\x15Z\x13./pb_resource_modelb\x06proto3"

var (
	file_resource_model_admin_permission_proto_rawDescOnce sync.Once
	file_resource_model_admin_permission_proto_rawDescData []byte
)

func file_resource_model_admin_permission_proto_rawDescGZIP() []byte {
	file_resource_model_admin_permission_proto_rawDescOnce.Do(func() {
		file_resource_model_admin_permission_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_resource_model_admin_permission_proto_rawDesc), len(file_resource_model_admin_permission_proto_rawDesc)))
	})
	return file_resource_model_admin_permission_proto_rawDescData
}

var file_resource_model_admin_permission_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_resource_model_admin_permission_proto_goTypes = []any{
	(*AdminPermissionVariable)(nil),                                     // 0: pb.resource.model.AdminPermissionVariable
	(*AdminPermissionAddOneInput)(nil),                                  // 1: pb.resource.model.AdminPermissionAddOneInput
	(*AdminPermissionAddOneOutput)(nil),                                 // 2: pb.resource.model.AdminPermissionAddOneOutput
	(*AdminPermissionShowOneByIdInput)(nil),                             // 3: pb.resource.model.AdminPermissionShowOneByIdInput
	(*AdminPermissionShowOneByIdOutput)(nil),                            // 4: pb.resource.model.AdminPermissionShowOneByIdOutput
	(*AdminPermissionEditOneByIdInput)(nil),                             // 5: pb.resource.model.AdminPermissionEditOneByIdInput
	(*AdminPermissionEditOneByIdOutput)(nil),                            // 6: pb.resource.model.AdminPermissionEditOneByIdOutput
	(*AdminPermissionRemoveOneByIdInput)(nil),                           // 7: pb.resource.model.AdminPermissionRemoveOneByIdInput
	(*AdminPermissionRemoveOneByIdOutput)(nil),                          // 8: pb.resource.model.AdminPermissionRemoveOneByIdOutput
	(*AdminPermissionShowOnesByFiltersWithSortersPaginationInput)(nil),  // 9: pb.resource.model.AdminPermissionShowOnesByFiltersWithSortersPaginationInput
	(*AdminPermissionShowOnesByFiltersWithSortersPaginationOutput)(nil), // 10: pb.resource.model.AdminPermissionShowOnesByFiltersWithSortersPaginationOutput
	(*AdminPermissionTotalByFiltersInput)(nil),                          // 11: pb.resource.model.AdminPermissionTotalByFiltersInput
	(*AdminPermissionTotalByFiltersOutput)(nil),                         // 12: pb.resource.model.AdminPermissionTotalByFiltersOutput
	(*resource.AdminPermission)(nil),                                    // 13: pb.resource.AdminPermission
	(*resource.Filter)(nil),                                             // 14: pb.resource.Filter
	(*resource.Sorter)(nil),                                             // 15: pb.resource.Sorter
	(*resource.Pagination)(nil),                                         // 16: pb.resource.Pagination
}
var file_resource_model_admin_permission_proto_depIdxs = []int32{
	0,  // 0: pb.resource.model.AdminPermissionAddOneInput.variable:type_name -> pb.resource.model.AdminPermissionVariable
	13, // 1: pb.resource.model.AdminPermissionShowOneByIdOutput.admin_permission:type_name -> pb.resource.AdminPermission
	0,  // 2: pb.resource.model.AdminPermissionEditOneByIdInput.variable:type_name -> pb.resource.model.AdminPermissionVariable
	14, // 3: pb.resource.model.AdminPermissionShowOnesByFiltersWithSortersPaginationInput.filters:type_name -> pb.resource.Filter
	15, // 4: pb.resource.model.AdminPermissionShowOnesByFiltersWithSortersPaginationInput.sorters:type_name -> pb.resource.Sorter
	16, // 5: pb.resource.model.AdminPermissionShowOnesByFiltersWithSortersPaginationInput.pagination:type_name -> pb.resource.Pagination
	13, // 6: pb.resource.model.AdminPermissionShowOnesByFiltersWithSortersPaginationOutput.admin_permissions:type_name -> pb.resource.AdminPermission
	14, // 7: pb.resource.model.AdminPermissionTotalByFiltersInput.filters:type_name -> pb.resource.Filter
	1,  // 8: pb.resource.model.AdminPermissionModel.AddOne:input_type -> pb.resource.model.AdminPermissionAddOneInput
	3,  // 9: pb.resource.model.AdminPermissionModel.ShowOneById:input_type -> pb.resource.model.AdminPermissionShowOneByIdInput
	5,  // 10: pb.resource.model.AdminPermissionModel.EditOneById:input_type -> pb.resource.model.AdminPermissionEditOneByIdInput
	7,  // 11: pb.resource.model.AdminPermissionModel.RemoveOneById:input_type -> pb.resource.model.AdminPermissionRemoveOneByIdInput
	9,  // 12: pb.resource.model.AdminPermissionModel.ShowOnesByFiltersWithSortersPagination:input_type -> pb.resource.model.AdminPermissionShowOnesByFiltersWithSortersPaginationInput
	11, // 13: pb.resource.model.AdminPermissionModel.TotalByFilters:input_type -> pb.resource.model.AdminPermissionTotalByFiltersInput
	2,  // 14: pb.resource.model.AdminPermissionModel.AddOne:output_type -> pb.resource.model.AdminPermissionAddOneOutput
	4,  // 15: pb.resource.model.AdminPermissionModel.ShowOneById:output_type -> pb.resource.model.AdminPermissionShowOneByIdOutput
	6,  // 16: pb.resource.model.AdminPermissionModel.EditOneById:output_type -> pb.resource.model.AdminPermissionEditOneByIdOutput
	8,  // 17: pb.resource.model.AdminPermissionModel.RemoveOneById:output_type -> pb.resource.model.AdminPermissionRemoveOneByIdOutput
	10, // 18: pb.resource.model.AdminPermissionModel.ShowOnesByFiltersWithSortersPagination:output_type -> pb.resource.model.AdminPermissionShowOnesByFiltersWithSortersPaginationOutput
	12, // 19: pb.resource.model.AdminPermissionModel.TotalByFilters:output_type -> pb.resource.model.AdminPermissionTotalByFiltersOutput
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_resource_model_admin_permission_proto_init() }
func file_resource_model_admin_permission_proto_init() {
	if File_resource_model_admin_permission_proto != nil {
		return
	}
	file_resource_model_admin_permission_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_resource_model_admin_permission_proto_rawDesc), len(file_resource_model_admin_permission_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_resource_model_admin_permission_proto_goTypes,
		DependencyIndexes: file_resource_model_admin_permission_proto_depIdxs,
		MessageInfos:      file_resource_model_admin_permission_proto_msgTypes,
	}.Build()
	File_resource_model_admin_permission_proto = out.File
	file_resource_model_admin_permission_proto_goTypes = nil
	file_resource_model_admin_permission_proto_depIdxs = nil
}
