// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: resource/model/admin_user.proto

package pb_resource_model

import (
	resource "example/pb/resource"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdminUserVariable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Password      *string                `protobuf:"bytes,2,opt,name=password,proto3,oneof" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUserVariable) Reset() {
	*x = AdminUserVariable{}
	mi := &file_resource_model_admin_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUserVariable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUserVariable) ProtoMessage() {}

func (x *AdminUserVariable) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_admin_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUserVariable.ProtoReflect.Descriptor instead.
func (*AdminUserVariable) Descriptor() ([]byte, []int) {
	return file_resource_model_admin_user_proto_rawDescGZIP(), []int{0}
}

func (x *AdminUserVariable) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *AdminUserVariable) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

type AdminUserShowOneByNameInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUserShowOneByNameInput) Reset() {
	*x = AdminUserShowOneByNameInput{}
	mi := &file_resource_model_admin_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUserShowOneByNameInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUserShowOneByNameInput) ProtoMessage() {}

func (x *AdminUserShowOneByNameInput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_admin_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUserShowOneByNameInput.ProtoReflect.Descriptor instead.
func (*AdminUserShowOneByNameInput) Descriptor() ([]byte, []int) {
	return file_resource_model_admin_user_proto_rawDescGZIP(), []int{1}
}

func (x *AdminUserShowOneByNameInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type AdminUserShowOneByNameOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdminUser     *resource.AdminUser    `protobuf:"bytes,1,opt,name=admin_user,json=adminUser,proto3" json:"admin_user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUserShowOneByNameOutput) Reset() {
	*x = AdminUserShowOneByNameOutput{}
	mi := &file_resource_model_admin_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUserShowOneByNameOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUserShowOneByNameOutput) ProtoMessage() {}

func (x *AdminUserShowOneByNameOutput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_admin_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUserShowOneByNameOutput.ProtoReflect.Descriptor instead.
func (*AdminUserShowOneByNameOutput) Descriptor() ([]byte, []int) {
	return file_resource_model_admin_user_proto_rawDescGZIP(), []int{2}
}

func (x *AdminUserShowOneByNameOutput) GetAdminUser() *resource.AdminUser {
	if x != nil {
		return x.AdminUser
	}
	return nil
}

type AdminUserShowOneByIdInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUserShowOneByIdInput) Reset() {
	*x = AdminUserShowOneByIdInput{}
	mi := &file_resource_model_admin_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUserShowOneByIdInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUserShowOneByIdInput) ProtoMessage() {}

func (x *AdminUserShowOneByIdInput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_admin_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUserShowOneByIdInput.ProtoReflect.Descriptor instead.
func (*AdminUserShowOneByIdInput) Descriptor() ([]byte, []int) {
	return file_resource_model_admin_user_proto_rawDescGZIP(), []int{3}
}

func (x *AdminUserShowOneByIdInput) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type AdminUserShowOneByIdOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdminUser     *resource.AdminUser    `protobuf:"bytes,1,opt,name=admin_user,json=adminUser,proto3" json:"admin_user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUserShowOneByIdOutput) Reset() {
	*x = AdminUserShowOneByIdOutput{}
	mi := &file_resource_model_admin_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUserShowOneByIdOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUserShowOneByIdOutput) ProtoMessage() {}

func (x *AdminUserShowOneByIdOutput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_admin_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUserShowOneByIdOutput.ProtoReflect.Descriptor instead.
func (*AdminUserShowOneByIdOutput) Descriptor() ([]byte, []int) {
	return file_resource_model_admin_user_proto_rawDescGZIP(), []int{4}
}

func (x *AdminUserShowOneByIdOutput) GetAdminUser() *resource.AdminUser {
	if x != nil {
		return x.AdminUser
	}
	return nil
}

type AdminUserAddOneInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Variable      *AdminUserVariable     `protobuf:"bytes,1,opt,name=variable,proto3" json:"variable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUserAddOneInput) Reset() {
	*x = AdminUserAddOneInput{}
	mi := &file_resource_model_admin_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUserAddOneInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUserAddOneInput) ProtoMessage() {}

func (x *AdminUserAddOneInput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_admin_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUserAddOneInput.ProtoReflect.Descriptor instead.
func (*AdminUserAddOneInput) Descriptor() ([]byte, []int) {
	return file_resource_model_admin_user_proto_rawDescGZIP(), []int{5}
}

func (x *AdminUserAddOneInput) GetVariable() *AdminUserVariable {
	if x != nil {
		return x.Variable
	}
	return nil
}

type AdminUserAddOneOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUserAddOneOutput) Reset() {
	*x = AdminUserAddOneOutput{}
	mi := &file_resource_model_admin_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUserAddOneOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUserAddOneOutput) ProtoMessage() {}

func (x *AdminUserAddOneOutput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_admin_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUserAddOneOutput.ProtoReflect.Descriptor instead.
func (*AdminUserAddOneOutput) Descriptor() ([]byte, []int) {
	return file_resource_model_admin_user_proto_rawDescGZIP(), []int{6}
}

func (x *AdminUserAddOneOutput) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type AdminUserEditOneByIdInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Variable      *AdminUserVariable     `protobuf:"bytes,1,opt,name=variable,proto3" json:"variable,omitempty"`
	Id            uint32                 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUserEditOneByIdInput) Reset() {
	*x = AdminUserEditOneByIdInput{}
	mi := &file_resource_model_admin_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUserEditOneByIdInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUserEditOneByIdInput) ProtoMessage() {}

func (x *AdminUserEditOneByIdInput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_admin_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUserEditOneByIdInput.ProtoReflect.Descriptor instead.
func (*AdminUserEditOneByIdInput) Descriptor() ([]byte, []int) {
	return file_resource_model_admin_user_proto_rawDescGZIP(), []int{7}
}

func (x *AdminUserEditOneByIdInput) GetVariable() *AdminUserVariable {
	if x != nil {
		return x.Variable
	}
	return nil
}

func (x *AdminUserEditOneByIdInput) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type AdminUserEditOneByIdOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUserEditOneByIdOutput) Reset() {
	*x = AdminUserEditOneByIdOutput{}
	mi := &file_resource_model_admin_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUserEditOneByIdOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUserEditOneByIdOutput) ProtoMessage() {}

func (x *AdminUserEditOneByIdOutput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_admin_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUserEditOneByIdOutput.ProtoReflect.Descriptor instead.
func (*AdminUserEditOneByIdOutput) Descriptor() ([]byte, []int) {
	return file_resource_model_admin_user_proto_rawDescGZIP(), []int{8}
}

func (x *AdminUserEditOneByIdOutput) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

var File_resource_model_admin_user_proto protoreflect.FileDescriptor

const file_resource_model_admin_user_proto_rawDesc = "" +
	"\n" +
	"\x1fresource/model/admin_user.proto\x12\x11pb.resource.model\x1a\x15resource/common.proto\"c\n" +
	"\x11AdminUserVariable\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x1f\n" +
	"\bpassword\x18\x02 \x01(\tH\x01R\bpassword\x88\x01\x01B\a\n" +
	"\x05_nameB\v\n" +
	"\t_password\"1\n" +
	"\x1bAdminUserShowOneByNameInput\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"U\n" +
	"\x1cAdminUserShowOneByNameOutput\x125\n" +
	"\n" +
	"admin_user\x18\x01 \x01(\v2\x16.pb.resource.AdminUserR\tadminUser\"+\n" +
	"\x19AdminUserShowOneByIdInput\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"S\n" +
	"\x1aAdminUserShowOneByIdOutput\x125\n" +
	"\n" +
	"admin_user\x18\x01 \x01(\v2\x16.pb.resource.AdminUserR\tadminUser\"X\n" +
	"\x14AdminUserAddOneInput\x12@\n" +
	"\bvariable\x18\x01 \x01(\v2$.pb.resource.model.AdminUserVariableR\bvariable\"/\n" +
	"\x15AdminUserAddOneOutput\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\"m\n" +
	"\x19AdminUserEditOneByIdInput\x12@\n" +
	"\bvariable\x18\x01 \x01(\v2$.pb.resource.model.AdminUserVariableR\bvariable\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\rR\x02id\"4\n" +
	"\x1aAdminUserEditOneByIdOutput\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status2\xb7\x03\n" +
	"\x0eAdminUserModel\x12p\n" +
	"\rShowOneByName\x12..pb.resource.model.AdminUserShowOneByNameInput\x1a/.pb.resource.model.AdminUserShowOneByNameOutput\x12j\n" +
	"\vShowOneById\x12,.pb.resource.model.AdminUserShowOneByIdInput\x1a-.pb.resource.model.AdminUserShowOneByIdOutput\x12[\n" +
	"\x06AddOne\x12'.pb.resource.model.AdminUserAddOneInput\x1a(.pb.resource.model.AdminUserAddOneOutput\x12j\n" +
	"\vEditOneById\x12,.pb.resource.model.AdminUserEditOneByIdInput\x1a-.pb.resource.model.AdminUserEditOneByIdOutputB\x15Z\x13./pb_resource_modelb\x06proto3"

var (
	file_resource_model_admin_user_proto_rawDescOnce sync.Once
	file_resource_model_admin_user_proto_rawDescData []byte
)

func file_resource_model_admin_user_proto_rawDescGZIP() []byte {
	file_resource_model_admin_user_proto_rawDescOnce.Do(func() {
		file_resource_model_admin_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_resource_model_admin_user_proto_rawDesc), len(file_resource_model_admin_user_proto_rawDesc)))
	})
	return file_resource_model_admin_user_proto_rawDescData
}

var file_resource_model_admin_user_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_resource_model_admin_user_proto_goTypes = []any{
	(*AdminUserVariable)(nil),            // 0: pb.resource.model.AdminUserVariable
	(*AdminUserShowOneByNameInput)(nil),  // 1: pb.resource.model.AdminUserShowOneByNameInput
	(*AdminUserShowOneByNameOutput)(nil), // 2: pb.resource.model.AdminUserShowOneByNameOutput
	(*AdminUserShowOneByIdInput)(nil),    // 3: pb.resource.model.AdminUserShowOneByIdInput
	(*AdminUserShowOneByIdOutput)(nil),   // 4: pb.resource.model.AdminUserShowOneByIdOutput
	(*AdminUserAddOneInput)(nil),         // 5: pb.resource.model.AdminUserAddOneInput
	(*AdminUserAddOneOutput)(nil),        // 6: pb.resource.model.AdminUserAddOneOutput
	(*AdminUserEditOneByIdInput)(nil),    // 7: pb.resource.model.AdminUserEditOneByIdInput
	(*AdminUserEditOneByIdOutput)(nil),   // 8: pb.resource.model.AdminUserEditOneByIdOutput
	(*resource.AdminUser)(nil),           // 9: pb.resource.AdminUser
}
var file_resource_model_admin_user_proto_depIdxs = []int32{
	9, // 0: pb.resource.model.AdminUserShowOneByNameOutput.admin_user:type_name -> pb.resource.AdminUser
	9, // 1: pb.resource.model.AdminUserShowOneByIdOutput.admin_user:type_name -> pb.resource.AdminUser
	0, // 2: pb.resource.model.AdminUserAddOneInput.variable:type_name -> pb.resource.model.AdminUserVariable
	0, // 3: pb.resource.model.AdminUserEditOneByIdInput.variable:type_name -> pb.resource.model.AdminUserVariable
	1, // 4: pb.resource.model.AdminUserModel.ShowOneByName:input_type -> pb.resource.model.AdminUserShowOneByNameInput
	3, // 5: pb.resource.model.AdminUserModel.ShowOneById:input_type -> pb.resource.model.AdminUserShowOneByIdInput
	5, // 6: pb.resource.model.AdminUserModel.AddOne:input_type -> pb.resource.model.AdminUserAddOneInput
	7, // 7: pb.resource.model.AdminUserModel.EditOneById:input_type -> pb.resource.model.AdminUserEditOneByIdInput
	2, // 8: pb.resource.model.AdminUserModel.ShowOneByName:output_type -> pb.resource.model.AdminUserShowOneByNameOutput
	4, // 9: pb.resource.model.AdminUserModel.ShowOneById:output_type -> pb.resource.model.AdminUserShowOneByIdOutput
	6, // 10: pb.resource.model.AdminUserModel.AddOne:output_type -> pb.resource.model.AdminUserAddOneOutput
	8, // 11: pb.resource.model.AdminUserModel.EditOneById:output_type -> pb.resource.model.AdminUserEditOneByIdOutput
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_resource_model_admin_user_proto_init() }
func file_resource_model_admin_user_proto_init() {
	if File_resource_model_admin_user_proto != nil {
		return
	}
	file_resource_model_admin_user_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_resource_model_admin_user_proto_rawDesc), len(file_resource_model_admin_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_resource_model_admin_user_proto_goTypes,
		DependencyIndexes: file_resource_model_admin_user_proto_depIdxs,
		MessageInfos:      file_resource_model_admin_user_proto_msgTypes,
	}.Build()
	File_resource_model_admin_user_proto = out.File
	file_resource_model_admin_user_proto_goTypes = nil
	file_resource_model_admin_user_proto_depIdxs = nil
}
