// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: resource/model/app_user.proto

package pb_resource_model

import (
	resource "example/pb/resource"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AppUserVariable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Password      *string                `protobuf:"bytes,2,opt,name=password,proto3,oneof" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppUserVariable) Reset() {
	*x = AppUserVariable{}
	mi := &file_resource_model_app_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppUserVariable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppUserVariable) ProtoMessage() {}

func (x *AppUserVariable) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_app_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppUserVariable.ProtoReflect.Descriptor instead.
func (*AppUserVariable) Descriptor() ([]byte, []int) {
	return file_resource_model_app_user_proto_rawDescGZIP(), []int{0}
}

func (x *AppUserVariable) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *AppUserVariable) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

type AppUserAddOneInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Variable      *AppUserVariable       `protobuf:"bytes,1,opt,name=variable,proto3" json:"variable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppUserAddOneInput) Reset() {
	*x = AppUserAddOneInput{}
	mi := &file_resource_model_app_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppUserAddOneInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppUserAddOneInput) ProtoMessage() {}

func (x *AppUserAddOneInput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_app_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppUserAddOneInput.ProtoReflect.Descriptor instead.
func (*AppUserAddOneInput) Descriptor() ([]byte, []int) {
	return file_resource_model_app_user_proto_rawDescGZIP(), []int{1}
}

func (x *AppUserAddOneInput) GetVariable() *AppUserVariable {
	if x != nil {
		return x.Variable
	}
	return nil
}

type AppUserAddOneOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppUserAddOneOutput) Reset() {
	*x = AppUserAddOneOutput{}
	mi := &file_resource_model_app_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppUserAddOneOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppUserAddOneOutput) ProtoMessage() {}

func (x *AppUserAddOneOutput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_app_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppUserAddOneOutput.ProtoReflect.Descriptor instead.
func (*AppUserAddOneOutput) Descriptor() ([]byte, []int) {
	return file_resource_model_app_user_proto_rawDescGZIP(), []int{2}
}

func (x *AppUserAddOneOutput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type AppUserShowOneByNameInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppUserShowOneByNameInput) Reset() {
	*x = AppUserShowOneByNameInput{}
	mi := &file_resource_model_app_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppUserShowOneByNameInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppUserShowOneByNameInput) ProtoMessage() {}

func (x *AppUserShowOneByNameInput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_app_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppUserShowOneByNameInput.ProtoReflect.Descriptor instead.
func (*AppUserShowOneByNameInput) Descriptor() ([]byte, []int) {
	return file_resource_model_app_user_proto_rawDescGZIP(), []int{3}
}

func (x *AppUserShowOneByNameInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type AppUserShowOneByNameOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppUser       *resource.AppUser      `protobuf:"bytes,1,opt,name=app_user,json=appUser,proto3" json:"app_user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppUserShowOneByNameOutput) Reset() {
	*x = AppUserShowOneByNameOutput{}
	mi := &file_resource_model_app_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppUserShowOneByNameOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppUserShowOneByNameOutput) ProtoMessage() {}

func (x *AppUserShowOneByNameOutput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_app_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppUserShowOneByNameOutput.ProtoReflect.Descriptor instead.
func (*AppUserShowOneByNameOutput) Descriptor() ([]byte, []int) {
	return file_resource_model_app_user_proto_rawDescGZIP(), []int{4}
}

func (x *AppUserShowOneByNameOutput) GetAppUser() *resource.AppUser {
	if x != nil {
		return x.AppUser
	}
	return nil
}

type AppUserShowOneByIdInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppUserShowOneByIdInput) Reset() {
	*x = AppUserShowOneByIdInput{}
	mi := &file_resource_model_app_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppUserShowOneByIdInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppUserShowOneByIdInput) ProtoMessage() {}

func (x *AppUserShowOneByIdInput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_app_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppUserShowOneByIdInput.ProtoReflect.Descriptor instead.
func (*AppUserShowOneByIdInput) Descriptor() ([]byte, []int) {
	return file_resource_model_app_user_proto_rawDescGZIP(), []int{5}
}

func (x *AppUserShowOneByIdInput) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type AppUserShowOneByIdOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppUser       *resource.AppUser      `protobuf:"bytes,1,opt,name=app_user,json=appUser,proto3" json:"app_user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppUserShowOneByIdOutput) Reset() {
	*x = AppUserShowOneByIdOutput{}
	mi := &file_resource_model_app_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppUserShowOneByIdOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppUserShowOneByIdOutput) ProtoMessage() {}

func (x *AppUserShowOneByIdOutput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_app_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppUserShowOneByIdOutput.ProtoReflect.Descriptor instead.
func (*AppUserShowOneByIdOutput) Descriptor() ([]byte, []int) {
	return file_resource_model_app_user_proto_rawDescGZIP(), []int{6}
}

func (x *AppUserShowOneByIdOutput) GetAppUser() *resource.AppUser {
	if x != nil {
		return x.AppUser
	}
	return nil
}

type AppUserIncreaseBalanceInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Amount        uint32                 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppUserIncreaseBalanceInput) Reset() {
	*x = AppUserIncreaseBalanceInput{}
	mi := &file_resource_model_app_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppUserIncreaseBalanceInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppUserIncreaseBalanceInput) ProtoMessage() {}

func (x *AppUserIncreaseBalanceInput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_app_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppUserIncreaseBalanceInput.ProtoReflect.Descriptor instead.
func (*AppUserIncreaseBalanceInput) Descriptor() ([]byte, []int) {
	return file_resource_model_app_user_proto_rawDescGZIP(), []int{7}
}

func (x *AppUserIncreaseBalanceInput) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AppUserIncreaseBalanceInput) GetAmount() uint32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type AppUserIncreaseBalanceOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppUserIncreaseBalanceOutput) Reset() {
	*x = AppUserIncreaseBalanceOutput{}
	mi := &file_resource_model_app_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppUserIncreaseBalanceOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppUserIncreaseBalanceOutput) ProtoMessage() {}

func (x *AppUserIncreaseBalanceOutput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_app_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppUserIncreaseBalanceOutput.ProtoReflect.Descriptor instead.
func (*AppUserIncreaseBalanceOutput) Descriptor() ([]byte, []int) {
	return file_resource_model_app_user_proto_rawDescGZIP(), []int{8}
}

func (x *AppUserIncreaseBalanceOutput) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

var File_resource_model_app_user_proto protoreflect.FileDescriptor

const file_resource_model_app_user_proto_rawDesc = "" +
	"\n" +
	"\x1dresource/model/app_user.proto\x12\x11pb.resource.model\x1a\x15resource/common.proto\"a\n" +
	"\x0fAppUserVariable\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x1f\n" +
	"\bpassword\x18\x02 \x01(\tH\x01R\bpassword\x88\x01\x01B\a\n" +
	"\x05_nameB\v\n" +
	"\t_password\"T\n" +
	"\x12AppUserAddOneInput\x12>\n" +
	"\bvariable\x18\x01 \x01(\v2\".pb.resource.model.AppUserVariableR\bvariable\")\n" +
	"\x13AppUserAddOneOutput\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"/\n" +
	"\x19AppUserShowOneByNameInput\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"M\n" +
	"\x1aAppUserShowOneByNameOutput\x12/\n" +
	"\bapp_user\x18\x01 \x01(\v2\x14.pb.resource.AppUserR\aappUser\")\n" +
	"\x17AppUserShowOneByIdInput\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"K\n" +
	"\x18AppUserShowOneByIdOutput\x12/\n" +
	"\bapp_user\x18\x01 \x01(\v2\x14.pb.resource.AppUserR\aappUser\"E\n" +
	"\x1bAppUserIncreaseBalanceInput\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\rR\x06amount\"6\n" +
	"\x1cAppUserIncreaseBalanceOutput\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status2\xb5\x03\n" +
	"\fAppUserModel\x12[\n" +
	"\n" +
	"AddAppUser\x12%.pb.resource.model.AppUserAddOneInput\x1a&.pb.resource.model.AppUserAddOneOutput\x12l\n" +
	"\rShowOneByName\x12,.pb.resource.model.AppUserShowOneByNameInput\x1a-.pb.resource.model.AppUserShowOneByNameOutput\x12f\n" +
	"\vShowOneById\x12*.pb.resource.model.AppUserShowOneByIdInput\x1a+.pb.resource.model.AppUserShowOneByIdOutput\x12r\n" +
	"\x0fIncreaseBalance\x12..pb.resource.model.AppUserIncreaseBalanceInput\x1a/.pb.resource.model.AppUserIncreaseBalanceOutputB\x15Z\x13./pb_resource_modelb\x06proto3"

var (
	file_resource_model_app_user_proto_rawDescOnce sync.Once
	file_resource_model_app_user_proto_rawDescData []byte
)

func file_resource_model_app_user_proto_rawDescGZIP() []byte {
	file_resource_model_app_user_proto_rawDescOnce.Do(func() {
		file_resource_model_app_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_resource_model_app_user_proto_rawDesc), len(file_resource_model_app_user_proto_rawDesc)))
	})
	return file_resource_model_app_user_proto_rawDescData
}

var file_resource_model_app_user_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_resource_model_app_user_proto_goTypes = []any{
	(*AppUserVariable)(nil),              // 0: pb.resource.model.AppUserVariable
	(*AppUserAddOneInput)(nil),           // 1: pb.resource.model.AppUserAddOneInput
	(*AppUserAddOneOutput)(nil),          // 2: pb.resource.model.AppUserAddOneOutput
	(*AppUserShowOneByNameInput)(nil),    // 3: pb.resource.model.AppUserShowOneByNameInput
	(*AppUserShowOneByNameOutput)(nil),   // 4: pb.resource.model.AppUserShowOneByNameOutput
	(*AppUserShowOneByIdInput)(nil),      // 5: pb.resource.model.AppUserShowOneByIdInput
	(*AppUserShowOneByIdOutput)(nil),     // 6: pb.resource.model.AppUserShowOneByIdOutput
	(*AppUserIncreaseBalanceInput)(nil),  // 7: pb.resource.model.AppUserIncreaseBalanceInput
	(*AppUserIncreaseBalanceOutput)(nil), // 8: pb.resource.model.AppUserIncreaseBalanceOutput
	(*resource.AppUser)(nil),             // 9: pb.resource.AppUser
}
var file_resource_model_app_user_proto_depIdxs = []int32{
	0, // 0: pb.resource.model.AppUserAddOneInput.variable:type_name -> pb.resource.model.AppUserVariable
	9, // 1: pb.resource.model.AppUserShowOneByNameOutput.app_user:type_name -> pb.resource.AppUser
	9, // 2: pb.resource.model.AppUserShowOneByIdOutput.app_user:type_name -> pb.resource.AppUser
	1, // 3: pb.resource.model.AppUserModel.AddAppUser:input_type -> pb.resource.model.AppUserAddOneInput
	3, // 4: pb.resource.model.AppUserModel.ShowOneByName:input_type -> pb.resource.model.AppUserShowOneByNameInput
	5, // 5: pb.resource.model.AppUserModel.ShowOneById:input_type -> pb.resource.model.AppUserShowOneByIdInput
	7, // 6: pb.resource.model.AppUserModel.IncreaseBalance:input_type -> pb.resource.model.AppUserIncreaseBalanceInput
	2, // 7: pb.resource.model.AppUserModel.AddAppUser:output_type -> pb.resource.model.AppUserAddOneOutput
	4, // 8: pb.resource.model.AppUserModel.ShowOneByName:output_type -> pb.resource.model.AppUserShowOneByNameOutput
	6, // 9: pb.resource.model.AppUserModel.ShowOneById:output_type -> pb.resource.model.AppUserShowOneByIdOutput
	8, // 10: pb.resource.model.AppUserModel.IncreaseBalance:output_type -> pb.resource.model.AppUserIncreaseBalanceOutput
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_resource_model_app_user_proto_init() }
func file_resource_model_app_user_proto_init() {
	if File_resource_model_app_user_proto != nil {
		return
	}
	file_resource_model_app_user_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_resource_model_app_user_proto_rawDesc), len(file_resource_model_app_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_resource_model_app_user_proto_goTypes,
		DependencyIndexes: file_resource_model_app_user_proto_depIdxs,
		MessageInfos:      file_resource_model_app_user_proto_msgTypes,
	}.Build()
	File_resource_model_app_user_proto = out.File
	file_resource_model_app_user_proto_goTypes = nil
	file_resource_model_app_user_proto_depIdxs = nil
}
