// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: resource/model/game.proto

package pb_resource_model

import (
	resource "example/pb/resource"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GameValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameTypeId    *uint64                `protobuf:"varint,1,opt,name=game_type_id,json=gameTypeId,proto3,oneof" json:"game_type_id,omitempty"`
	Key           *string                `protobuf:"bytes,2,opt,name=key,proto3,oneof" json:"key,omitempty"`
	Name          *string                `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameValue) Reset() {
	*x = GameValue{}
	mi := &file_resource_model_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameValue) ProtoMessage() {}

func (x *GameValue) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameValue.ProtoReflect.Descriptor instead.
func (*GameValue) Descriptor() ([]byte, []int) {
	return file_resource_model_game_proto_rawDescGZIP(), []int{0}
}

func (x *GameValue) GetGameTypeId() uint64 {
	if x != nil && x.GameTypeId != nil {
		return *x.GameTypeId
	}
	return 0
}

func (x *GameValue) GetKey() string {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return ""
}

func (x *GameValue) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *GameValue) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

type GameAddOneInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *GameValue             `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameAddOneInput) Reset() {
	*x = GameAddOneInput{}
	mi := &file_resource_model_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameAddOneInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameAddOneInput) ProtoMessage() {}

func (x *GameAddOneInput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameAddOneInput.ProtoReflect.Descriptor instead.
func (*GameAddOneInput) Descriptor() ([]byte, []int) {
	return file_resource_model_game_proto_rawDescGZIP(), []int{1}
}

func (x *GameAddOneInput) GetValue() *GameValue {
	if x != nil {
		return x.Value
	}
	return nil
}

type GameAddOneOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Game          *resource.Game         `protobuf:"bytes,1,opt,name=game,proto3" json:"game,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameAddOneOutput) Reset() {
	*x = GameAddOneOutput{}
	mi := &file_resource_model_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameAddOneOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameAddOneOutput) ProtoMessage() {}

func (x *GameAddOneOutput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameAddOneOutput.ProtoReflect.Descriptor instead.
func (*GameAddOneOutput) Descriptor() ([]byte, []int) {
	return file_resource_model_game_proto_rawDescGZIP(), []int{2}
}

func (x *GameAddOneOutput) GetGame() *resource.Game {
	if x != nil {
		return x.Game
	}
	return nil
}

type GameShowOneByKeyInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameShowOneByKeyInput) Reset() {
	*x = GameShowOneByKeyInput{}
	mi := &file_resource_model_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameShowOneByKeyInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameShowOneByKeyInput) ProtoMessage() {}

func (x *GameShowOneByKeyInput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameShowOneByKeyInput.ProtoReflect.Descriptor instead.
func (*GameShowOneByKeyInput) Descriptor() ([]byte, []int) {
	return file_resource_model_game_proto_rawDescGZIP(), []int{3}
}

func (x *GameShowOneByKeyInput) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GameShowOneByKeyOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Game          *resource.Game         `protobuf:"bytes,1,opt,name=game,proto3" json:"game,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameShowOneByKeyOutput) Reset() {
	*x = GameShowOneByKeyOutput{}
	mi := &file_resource_model_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameShowOneByKeyOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameShowOneByKeyOutput) ProtoMessage() {}

func (x *GameShowOneByKeyOutput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameShowOneByKeyOutput.ProtoReflect.Descriptor instead.
func (*GameShowOneByKeyOutput) Descriptor() ([]byte, []int) {
	return file_resource_model_game_proto_rawDescGZIP(), []int{4}
}

func (x *GameShowOneByKeyOutput) GetGame() *resource.Game {
	if x != nil {
		return x.Game
	}
	return nil
}

type GameEditOneByIdInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *GameValue             `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Id            uint64                 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameEditOneByIdInput) Reset() {
	*x = GameEditOneByIdInput{}
	mi := &file_resource_model_game_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameEditOneByIdInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameEditOneByIdInput) ProtoMessage() {}

func (x *GameEditOneByIdInput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_game_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameEditOneByIdInput.ProtoReflect.Descriptor instead.
func (*GameEditOneByIdInput) Descriptor() ([]byte, []int) {
	return file_resource_model_game_proto_rawDescGZIP(), []int{5}
}

func (x *GameEditOneByIdInput) GetValue() *GameValue {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GameEditOneByIdInput) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GameEditOneByIdOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameEditOneByIdOutput) Reset() {
	*x = GameEditOneByIdOutput{}
	mi := &file_resource_model_game_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameEditOneByIdOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameEditOneByIdOutput) ProtoMessage() {}

func (x *GameEditOneByIdOutput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_game_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameEditOneByIdOutput.ProtoReflect.Descriptor instead.
func (*GameEditOneByIdOutput) Descriptor() ([]byte, []int) {
	return file_resource_model_game_proto_rawDescGZIP(), []int{6}
}

func (x *GameEditOneByIdOutput) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type GameRemoveOneByIdInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameRemoveOneByIdInput) Reset() {
	*x = GameRemoveOneByIdInput{}
	mi := &file_resource_model_game_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameRemoveOneByIdInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameRemoveOneByIdInput) ProtoMessage() {}

func (x *GameRemoveOneByIdInput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_game_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameRemoveOneByIdInput.ProtoReflect.Descriptor instead.
func (*GameRemoveOneByIdInput) Descriptor() ([]byte, []int) {
	return file_resource_model_game_proto_rawDescGZIP(), []int{7}
}

func (x *GameRemoveOneByIdInput) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GameRemoveOneByIdOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameRemoveOneByIdOutput) Reset() {
	*x = GameRemoveOneByIdOutput{}
	mi := &file_resource_model_game_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameRemoveOneByIdOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameRemoveOneByIdOutput) ProtoMessage() {}

func (x *GameRemoveOneByIdOutput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_game_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameRemoveOneByIdOutput.ProtoReflect.Descriptor instead.
func (*GameRemoveOneByIdOutput) Descriptor() ([]byte, []int) {
	return file_resource_model_game_proto_rawDescGZIP(), []int{8}
}

func (x *GameRemoveOneByIdOutput) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type GameTotalByFiltersInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filters       []*resource.Filter     `protobuf:"bytes,1,rep,name=filters,proto3" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameTotalByFiltersInput) Reset() {
	*x = GameTotalByFiltersInput{}
	mi := &file_resource_model_game_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameTotalByFiltersInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameTotalByFiltersInput) ProtoMessage() {}

func (x *GameTotalByFiltersInput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_game_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameTotalByFiltersInput.ProtoReflect.Descriptor instead.
func (*GameTotalByFiltersInput) Descriptor() ([]byte, []int) {
	return file_resource_model_game_proto_rawDescGZIP(), []int{9}
}

func (x *GameTotalByFiltersInput) GetFilters() []*resource.Filter {
	if x != nil {
		return x.Filters
	}
	return nil
}

type GameTotalByFiltersOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         uint64                 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameTotalByFiltersOutput) Reset() {
	*x = GameTotalByFiltersOutput{}
	mi := &file_resource_model_game_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameTotalByFiltersOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameTotalByFiltersOutput) ProtoMessage() {}

func (x *GameTotalByFiltersOutput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_game_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameTotalByFiltersOutput.ProtoReflect.Descriptor instead.
func (*GameTotalByFiltersOutput) Descriptor() ([]byte, []int) {
	return file_resource_model_game_proto_rawDescGZIP(), []int{10}
}

func (x *GameTotalByFiltersOutput) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_resource_model_game_proto protoreflect.FileDescriptor

const file_resource_model_game_proto_rawDesc = "" +
	"\n" +
	"\x19resource/model/game.proto\x12\x11pb.resource.model\x1a\x15resource/common.proto\"\xbb\x01\n" +
	"\tGameValue\x12%\n" +
	"\fgame_type_id\x18\x01 \x01(\x04H\x00R\n" +
	"gameTypeId\x88\x01\x01\x12\x15\n" +
	"\x03key\x18\x02 \x01(\tH\x01R\x03key\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x03 \x01(\tH\x02R\x04name\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x03R\vdescription\x88\x01\x01B\x0f\n" +
	"\r_game_type_idB\x06\n" +
	"\x04_keyB\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_description\"E\n" +
	"\x0fGameAddOneInput\x122\n" +
	"\x05value\x18\x01 \x01(\v2\x1c.pb.resource.model.GameValueR\x05value\"9\n" +
	"\x10GameAddOneOutput\x12%\n" +
	"\x04game\x18\x01 \x01(\v2\x11.pb.resource.GameR\x04game\")\n" +
	"\x15GameShowOneByKeyInput\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"?\n" +
	"\x16GameShowOneByKeyOutput\x12%\n" +
	"\x04game\x18\x01 \x01(\v2\x11.pb.resource.GameR\x04game\"Z\n" +
	"\x14GameEditOneByIdInput\x122\n" +
	"\x05value\x18\x01 \x01(\v2\x1c.pb.resource.model.GameValueR\x05value\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x04R\x02id\"/\n" +
	"\x15GameEditOneByIdOutput\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\"(\n" +
	"\x16GameRemoveOneByIdInput\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"1\n" +
	"\x17GameRemoveOneByIdOutput\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\"H\n" +
	"\x17GameTotalByFiltersInput\x12-\n" +
	"\afilters\x18\x01 \x03(\v2\x13.pb.resource.FilterR\afilters\"0\n" +
	"\x18GameTotalByFiltersOutput\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x04R\x05total2\xf8\x03\n" +
	"\tGameModel\x12Q\n" +
	"\x06AddOne\x12\".pb.resource.model.GameAddOneInput\x1a#.pb.resource.model.GameAddOneOutput\x12c\n" +
	"\fShowOneByKey\x12(.pb.resource.model.GameShowOneByKeyInput\x1a).pb.resource.model.GameShowOneByKeyOutput\x12`\n" +
	"\vEditOneById\x12'.pb.resource.model.GameEditOneByIdInput\x1a(.pb.resource.model.GameEditOneByIdOutput\x12f\n" +
	"\rRemoveOneById\x12).pb.resource.model.GameRemoveOneByIdInput\x1a*.pb.resource.model.GameRemoveOneByIdOutput\x12i\n" +
	"\x0eTotalByFilters\x12*.pb.resource.model.GameTotalByFiltersInput\x1a+.pb.resource.model.GameTotalByFiltersOutputB\x15Z\x13./pb_resource_modelb\x06proto3"

var (
	file_resource_model_game_proto_rawDescOnce sync.Once
	file_resource_model_game_proto_rawDescData []byte
)

func file_resource_model_game_proto_rawDescGZIP() []byte {
	file_resource_model_game_proto_rawDescOnce.Do(func() {
		file_resource_model_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_resource_model_game_proto_rawDesc), len(file_resource_model_game_proto_rawDesc)))
	})
	return file_resource_model_game_proto_rawDescData
}

var file_resource_model_game_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_resource_model_game_proto_goTypes = []any{
	(*GameValue)(nil),                // 0: pb.resource.model.GameValue
	(*GameAddOneInput)(nil),          // 1: pb.resource.model.GameAddOneInput
	(*GameAddOneOutput)(nil),         // 2: pb.resource.model.GameAddOneOutput
	(*GameShowOneByKeyInput)(nil),    // 3: pb.resource.model.GameShowOneByKeyInput
	(*GameShowOneByKeyOutput)(nil),   // 4: pb.resource.model.GameShowOneByKeyOutput
	(*GameEditOneByIdInput)(nil),     // 5: pb.resource.model.GameEditOneByIdInput
	(*GameEditOneByIdOutput)(nil),    // 6: pb.resource.model.GameEditOneByIdOutput
	(*GameRemoveOneByIdInput)(nil),   // 7: pb.resource.model.GameRemoveOneByIdInput
	(*GameRemoveOneByIdOutput)(nil),  // 8: pb.resource.model.GameRemoveOneByIdOutput
	(*GameTotalByFiltersInput)(nil),  // 9: pb.resource.model.GameTotalByFiltersInput
	(*GameTotalByFiltersOutput)(nil), // 10: pb.resource.model.GameTotalByFiltersOutput
	(*resource.Game)(nil),            // 11: pb.resource.Game
	(*resource.Filter)(nil),          // 12: pb.resource.Filter
}
var file_resource_model_game_proto_depIdxs = []int32{
	0,  // 0: pb.resource.model.GameAddOneInput.value:type_name -> pb.resource.model.GameValue
	11, // 1: pb.resource.model.GameAddOneOutput.game:type_name -> pb.resource.Game
	11, // 2: pb.resource.model.GameShowOneByKeyOutput.game:type_name -> pb.resource.Game
	0,  // 3: pb.resource.model.GameEditOneByIdInput.value:type_name -> pb.resource.model.GameValue
	12, // 4: pb.resource.model.GameTotalByFiltersInput.filters:type_name -> pb.resource.Filter
	1,  // 5: pb.resource.model.GameModel.AddOne:input_type -> pb.resource.model.GameAddOneInput
	3,  // 6: pb.resource.model.GameModel.ShowOneByKey:input_type -> pb.resource.model.GameShowOneByKeyInput
	5,  // 7: pb.resource.model.GameModel.EditOneById:input_type -> pb.resource.model.GameEditOneByIdInput
	7,  // 8: pb.resource.model.GameModel.RemoveOneById:input_type -> pb.resource.model.GameRemoveOneByIdInput
	9,  // 9: pb.resource.model.GameModel.TotalByFilters:input_type -> pb.resource.model.GameTotalByFiltersInput
	2,  // 10: pb.resource.model.GameModel.AddOne:output_type -> pb.resource.model.GameAddOneOutput
	4,  // 11: pb.resource.model.GameModel.ShowOneByKey:output_type -> pb.resource.model.GameShowOneByKeyOutput
	6,  // 12: pb.resource.model.GameModel.EditOneById:output_type -> pb.resource.model.GameEditOneByIdOutput
	8,  // 13: pb.resource.model.GameModel.RemoveOneById:output_type -> pb.resource.model.GameRemoveOneByIdOutput
	10, // 14: pb.resource.model.GameModel.TotalByFilters:output_type -> pb.resource.model.GameTotalByFiltersOutput
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_resource_model_game_proto_init() }
func file_resource_model_game_proto_init() {
	if File_resource_model_game_proto != nil {
		return
	}
	file_resource_model_game_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_resource_model_game_proto_rawDesc), len(file_resource_model_game_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_resource_model_game_proto_goTypes,
		DependencyIndexes: file_resource_model_game_proto_depIdxs,
		MessageInfos:      file_resource_model_game_proto_msgTypes,
	}.Build()
	File_resource_model_game_proto = out.File
	file_resource_model_game_proto_goTypes = nil
	file_resource_model_game_proto_depIdxs = nil
}
