// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: resource/model/game_type.proto

package pb_resource_model

import (
	resource "example/pb/resource"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GameTypeVariable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *string                `protobuf:"bytes,1,opt,name=key,proto3,oneof" json:"key,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameTypeVariable) Reset() {
	*x = GameTypeVariable{}
	mi := &file_resource_model_game_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameTypeVariable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameTypeVariable) ProtoMessage() {}

func (x *GameTypeVariable) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_game_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameTypeVariable.ProtoReflect.Descriptor instead.
func (*GameTypeVariable) Descriptor() ([]byte, []int) {
	return file_resource_model_game_type_proto_rawDescGZIP(), []int{0}
}

func (x *GameTypeVariable) GetKey() string {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return ""
}

func (x *GameTypeVariable) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

type GameTypeAddOneInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Variable      *GameTypeVariable      `protobuf:"bytes,1,opt,name=variable,proto3" json:"variable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameTypeAddOneInput) Reset() {
	*x = GameTypeAddOneInput{}
	mi := &file_resource_model_game_type_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameTypeAddOneInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameTypeAddOneInput) ProtoMessage() {}

func (x *GameTypeAddOneInput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_game_type_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameTypeAddOneInput.ProtoReflect.Descriptor instead.
func (*GameTypeAddOneInput) Descriptor() ([]byte, []int) {
	return file_resource_model_game_type_proto_rawDescGZIP(), []int{1}
}

func (x *GameTypeAddOneInput) GetVariable() *GameTypeVariable {
	if x != nil {
		return x.Variable
	}
	return nil
}

type GameTypeAddOneOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameType      *resource.GameType     `protobuf:"bytes,1,opt,name=game_type,json=gameType,proto3" json:"game_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameTypeAddOneOutput) Reset() {
	*x = GameTypeAddOneOutput{}
	mi := &file_resource_model_game_type_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameTypeAddOneOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameTypeAddOneOutput) ProtoMessage() {}

func (x *GameTypeAddOneOutput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_game_type_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameTypeAddOneOutput.ProtoReflect.Descriptor instead.
func (*GameTypeAddOneOutput) Descriptor() ([]byte, []int) {
	return file_resource_model_game_type_proto_rawDescGZIP(), []int{2}
}

func (x *GameTypeAddOneOutput) GetGameType() *resource.GameType {
	if x != nil {
		return x.GameType
	}
	return nil
}

type GameTypeShowOneByIdInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameTypeShowOneByIdInput) Reset() {
	*x = GameTypeShowOneByIdInput{}
	mi := &file_resource_model_game_type_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameTypeShowOneByIdInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameTypeShowOneByIdInput) ProtoMessage() {}

func (x *GameTypeShowOneByIdInput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_game_type_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameTypeShowOneByIdInput.ProtoReflect.Descriptor instead.
func (*GameTypeShowOneByIdInput) Descriptor() ([]byte, []int) {
	return file_resource_model_game_type_proto_rawDescGZIP(), []int{3}
}

func (x *GameTypeShowOneByIdInput) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GameTypeShowOneByIdOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameType      *resource.GameType     `protobuf:"bytes,1,opt,name=game_type,json=gameType,proto3" json:"game_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameTypeShowOneByIdOutput) Reset() {
	*x = GameTypeShowOneByIdOutput{}
	mi := &file_resource_model_game_type_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameTypeShowOneByIdOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameTypeShowOneByIdOutput) ProtoMessage() {}

func (x *GameTypeShowOneByIdOutput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_game_type_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameTypeShowOneByIdOutput.ProtoReflect.Descriptor instead.
func (*GameTypeShowOneByIdOutput) Descriptor() ([]byte, []int) {
	return file_resource_model_game_type_proto_rawDescGZIP(), []int{4}
}

func (x *GameTypeShowOneByIdOutput) GetGameType() *resource.GameType {
	if x != nil {
		return x.GameType
	}
	return nil
}

type GameTypeEditOneByIdInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Variable      *GameTypeVariable      `protobuf:"bytes,1,opt,name=variable,proto3" json:"variable,omitempty"`
	Id            uint64                 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameTypeEditOneByIdInput) Reset() {
	*x = GameTypeEditOneByIdInput{}
	mi := &file_resource_model_game_type_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameTypeEditOneByIdInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameTypeEditOneByIdInput) ProtoMessage() {}

func (x *GameTypeEditOneByIdInput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_game_type_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameTypeEditOneByIdInput.ProtoReflect.Descriptor instead.
func (*GameTypeEditOneByIdInput) Descriptor() ([]byte, []int) {
	return file_resource_model_game_type_proto_rawDescGZIP(), []int{5}
}

func (x *GameTypeEditOneByIdInput) GetVariable() *GameTypeVariable {
	if x != nil {
		return x.Variable
	}
	return nil
}

func (x *GameTypeEditOneByIdInput) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GameTypeEditOneByIdOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameTypeEditOneByIdOutput) Reset() {
	*x = GameTypeEditOneByIdOutput{}
	mi := &file_resource_model_game_type_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameTypeEditOneByIdOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameTypeEditOneByIdOutput) ProtoMessage() {}

func (x *GameTypeEditOneByIdOutput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_game_type_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameTypeEditOneByIdOutput.ProtoReflect.Descriptor instead.
func (*GameTypeEditOneByIdOutput) Descriptor() ([]byte, []int) {
	return file_resource_model_game_type_proto_rawDescGZIP(), []int{6}
}

func (x *GameTypeEditOneByIdOutput) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

// 數據模型直接對ID查找
type GameTypeRemoveOneByIdInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameTypeRemoveOneByIdInput) Reset() {
	*x = GameTypeRemoveOneByIdInput{}
	mi := &file_resource_model_game_type_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameTypeRemoveOneByIdInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameTypeRemoveOneByIdInput) ProtoMessage() {}

func (x *GameTypeRemoveOneByIdInput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_game_type_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameTypeRemoveOneByIdInput.ProtoReflect.Descriptor instead.
func (*GameTypeRemoveOneByIdInput) Descriptor() ([]byte, []int) {
	return file_resource_model_game_type_proto_rawDescGZIP(), []int{7}
}

func (x *GameTypeRemoveOneByIdInput) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GameTypeRemoveOneByIdOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameTypeRemoveOneByIdOutput) Reset() {
	*x = GameTypeRemoveOneByIdOutput{}
	mi := &file_resource_model_game_type_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameTypeRemoveOneByIdOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameTypeRemoveOneByIdOutput) ProtoMessage() {}

func (x *GameTypeRemoveOneByIdOutput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_game_type_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameTypeRemoveOneByIdOutput.ProtoReflect.Descriptor instead.
func (*GameTypeRemoveOneByIdOutput) Descriptor() ([]byte, []int) {
	return file_resource_model_game_type_proto_rawDescGZIP(), []int{8}
}

func (x *GameTypeRemoveOneByIdOutput) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type GameTypeShowOnesByFiltersWithSortersPaginationInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *resource.Pagination   `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Filters       []*resource.Filter     `protobuf:"bytes,2,rep,name=filters,proto3" json:"filters,omitempty"`
	Sorters       []*resource.Sorter     `protobuf:"bytes,3,rep,name=sorters,proto3" json:"sorters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameTypeShowOnesByFiltersWithSortersPaginationInput) Reset() {
	*x = GameTypeShowOnesByFiltersWithSortersPaginationInput{}
	mi := &file_resource_model_game_type_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameTypeShowOnesByFiltersWithSortersPaginationInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameTypeShowOnesByFiltersWithSortersPaginationInput) ProtoMessage() {}

func (x *GameTypeShowOnesByFiltersWithSortersPaginationInput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_game_type_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameTypeShowOnesByFiltersWithSortersPaginationInput.ProtoReflect.Descriptor instead.
func (*GameTypeShowOnesByFiltersWithSortersPaginationInput) Descriptor() ([]byte, []int) {
	return file_resource_model_game_type_proto_rawDescGZIP(), []int{9}
}

func (x *GameTypeShowOnesByFiltersWithSortersPaginationInput) GetPagination() *resource.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *GameTypeShowOnesByFiltersWithSortersPaginationInput) GetFilters() []*resource.Filter {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *GameTypeShowOnesByFiltersWithSortersPaginationInput) GetSorters() []*resource.Sorter {
	if x != nil {
		return x.Sorters
	}
	return nil
}

type GameTypeShowOnesByFiltersWithSortersPaginationOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameTypes     []*resource.GameType   `protobuf:"bytes,1,rep,name=game_types,json=gameTypes,proto3" json:"game_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameTypeShowOnesByFiltersWithSortersPaginationOutput) Reset() {
	*x = GameTypeShowOnesByFiltersWithSortersPaginationOutput{}
	mi := &file_resource_model_game_type_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameTypeShowOnesByFiltersWithSortersPaginationOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameTypeShowOnesByFiltersWithSortersPaginationOutput) ProtoMessage() {}

func (x *GameTypeShowOnesByFiltersWithSortersPaginationOutput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_game_type_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameTypeShowOnesByFiltersWithSortersPaginationOutput.ProtoReflect.Descriptor instead.
func (*GameTypeShowOnesByFiltersWithSortersPaginationOutput) Descriptor() ([]byte, []int) {
	return file_resource_model_game_type_proto_rawDescGZIP(), []int{10}
}

func (x *GameTypeShowOnesByFiltersWithSortersPaginationOutput) GetGameTypes() []*resource.GameType {
	if x != nil {
		return x.GameTypes
	}
	return nil
}

type GameTypeTotalByFiltersInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filters       []*resource.Filter     `protobuf:"bytes,1,rep,name=filters,proto3" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameTypeTotalByFiltersInput) Reset() {
	*x = GameTypeTotalByFiltersInput{}
	mi := &file_resource_model_game_type_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameTypeTotalByFiltersInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameTypeTotalByFiltersInput) ProtoMessage() {}

func (x *GameTypeTotalByFiltersInput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_game_type_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameTypeTotalByFiltersInput.ProtoReflect.Descriptor instead.
func (*GameTypeTotalByFiltersInput) Descriptor() ([]byte, []int) {
	return file_resource_model_game_type_proto_rawDescGZIP(), []int{11}
}

func (x *GameTypeTotalByFiltersInput) GetFilters() []*resource.Filter {
	if x != nil {
		return x.Filters
	}
	return nil
}

type GameTypeTotalByFiltersOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         uint64                 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameTypeTotalByFiltersOutput) Reset() {
	*x = GameTypeTotalByFiltersOutput{}
	mi := &file_resource_model_game_type_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameTypeTotalByFiltersOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameTypeTotalByFiltersOutput) ProtoMessage() {}

func (x *GameTypeTotalByFiltersOutput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_game_type_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameTypeTotalByFiltersOutput.ProtoReflect.Descriptor instead.
func (*GameTypeTotalByFiltersOutput) Descriptor() ([]byte, []int) {
	return file_resource_model_game_type_proto_rawDescGZIP(), []int{12}
}

func (x *GameTypeTotalByFiltersOutput) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_resource_model_game_type_proto protoreflect.FileDescriptor

const file_resource_model_game_type_proto_rawDesc = "" +
	"\n" +
	"\x1eresource/model/game_type.proto\x12\x11pb.resource.model\x1a\x15resource/common.proto\"S\n" +
	"\x10GameTypeVariable\x12\x15\n" +
	"\x03key\x18\x01 \x01(\tH\x00R\x03key\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x01R\x04name\x88\x01\x01B\x06\n" +
	"\x04_keyB\a\n" +
	"\x05_name\"V\n" +
	"\x13GameTypeAddOneInput\x12?\n" +
	"\bvariable\x18\x01 \x01(\v2#.pb.resource.model.GameTypeVariableR\bvariable\"J\n" +
	"\x14GameTypeAddOneOutput\x122\n" +
	"\tgame_type\x18\x01 \x01(\v2\x15.pb.resource.GameTypeR\bgameType\"*\n" +
	"\x18GameTypeShowOneByIdInput\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"O\n" +
	"\x19GameTypeShowOneByIdOutput\x122\n" +
	"\tgame_type\x18\x01 \x01(\v2\x15.pb.resource.GameTypeR\bgameType\"k\n" +
	"\x18GameTypeEditOneByIdInput\x12?\n" +
	"\bvariable\x18\x01 \x01(\v2#.pb.resource.model.GameTypeVariableR\bvariable\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x04R\x02id\"3\n" +
	"\x19GameTypeEditOneByIdOutput\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\",\n" +
	"\x1aGameTypeRemoveOneByIdInput\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"5\n" +
	"\x1bGameTypeRemoveOneByIdOutput\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\"\xcc\x01\n" +
	"3GameTypeShowOnesByFiltersWithSortersPaginationInput\x127\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x17.pb.resource.PaginationR\n" +
	"pagination\x12-\n" +
	"\afilters\x18\x02 \x03(\v2\x13.pb.resource.FilterR\afilters\x12-\n" +
	"\asorters\x18\x03 \x03(\v2\x13.pb.resource.SorterR\asorters\"l\n" +
	"4GameTypeShowOnesByFiltersWithSortersPaginationOutput\x124\n" +
	"\n" +
	"game_types\x18\x01 \x03(\v2\x15.pb.resource.GameTypeR\tgameTypes\"L\n" +
	"\x1bGameTypeTotalByFiltersInput\x12-\n" +
	"\afilters\x18\x01 \x03(\v2\x13.pb.resource.FilterR\afilters\"4\n" +
	"\x1cGameTypeTotalByFiltersOutput\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x04R\x05total2\xdd\x05\n" +
	"\rGameTypeModel\x12Y\n" +
	"\x06AddOne\x12&.pb.resource.model.GameTypeAddOneInput\x1a'.pb.resource.model.GameTypeAddOneOutput\x12h\n" +
	"\vShowOneById\x12+.pb.resource.model.GameTypeShowOneByIdInput\x1a,.pb.resource.model.GameTypeShowOneByIdOutput\x12\xb9\x01\n" +
	"&ShowOnesByFiltersWithSortersPagination\x12F.pb.resource.model.GameTypeShowOnesByFiltersWithSortersPaginationInput\x1aG.pb.resource.model.GameTypeShowOnesByFiltersWithSortersPaginationOutput\x12h\n" +
	"\vEditOneById\x12+.pb.resource.model.GameTypeEditOneByIdInput\x1a,.pb.resource.model.GameTypeEditOneByIdOutput\x12n\n" +
	"\rRemoveOneById\x12-.pb.resource.model.GameTypeRemoveOneByIdInput\x1a..pb.resource.model.GameTypeRemoveOneByIdOutput\x12q\n" +
	"\x0eTotalByFilters\x12..pb.resource.model.GameTypeTotalByFiltersInput\x1a/.pb.resource.model.GameTypeTotalByFiltersOutputB\x15Z\x13./pb_resource_modelb\x06proto3"

var (
	file_resource_model_game_type_proto_rawDescOnce sync.Once
	file_resource_model_game_type_proto_rawDescData []byte
)

func file_resource_model_game_type_proto_rawDescGZIP() []byte {
	file_resource_model_game_type_proto_rawDescOnce.Do(func() {
		file_resource_model_game_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_resource_model_game_type_proto_rawDesc), len(file_resource_model_game_type_proto_rawDesc)))
	})
	return file_resource_model_game_type_proto_rawDescData
}

var file_resource_model_game_type_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_resource_model_game_type_proto_goTypes = []any{
	(*GameTypeVariable)(nil),                                     // 0: pb.resource.model.GameTypeVariable
	(*GameTypeAddOneInput)(nil),                                  // 1: pb.resource.model.GameTypeAddOneInput
	(*GameTypeAddOneOutput)(nil),                                 // 2: pb.resource.model.GameTypeAddOneOutput
	(*GameTypeShowOneByIdInput)(nil),                             // 3: pb.resource.model.GameTypeShowOneByIdInput
	(*GameTypeShowOneByIdOutput)(nil),                            // 4: pb.resource.model.GameTypeShowOneByIdOutput
	(*GameTypeEditOneByIdInput)(nil),                             // 5: pb.resource.model.GameTypeEditOneByIdInput
	(*GameTypeEditOneByIdOutput)(nil),                            // 6: pb.resource.model.GameTypeEditOneByIdOutput
	(*GameTypeRemoveOneByIdInput)(nil),                           // 7: pb.resource.model.GameTypeRemoveOneByIdInput
	(*GameTypeRemoveOneByIdOutput)(nil),                          // 8: pb.resource.model.GameTypeRemoveOneByIdOutput
	(*GameTypeShowOnesByFiltersWithSortersPaginationInput)(nil),  // 9: pb.resource.model.GameTypeShowOnesByFiltersWithSortersPaginationInput
	(*GameTypeShowOnesByFiltersWithSortersPaginationOutput)(nil), // 10: pb.resource.model.GameTypeShowOnesByFiltersWithSortersPaginationOutput
	(*GameTypeTotalByFiltersInput)(nil),                          // 11: pb.resource.model.GameTypeTotalByFiltersInput
	(*GameTypeTotalByFiltersOutput)(nil),                         // 12: pb.resource.model.GameTypeTotalByFiltersOutput
	(*resource.GameType)(nil),                                    // 13: pb.resource.GameType
	(*resource.Pagination)(nil),                                  // 14: pb.resource.Pagination
	(*resource.Filter)(nil),                                      // 15: pb.resource.Filter
	(*resource.Sorter)(nil),                                      // 16: pb.resource.Sorter
}
var file_resource_model_game_type_proto_depIdxs = []int32{
	0,  // 0: pb.resource.model.GameTypeAddOneInput.variable:type_name -> pb.resource.model.GameTypeVariable
	13, // 1: pb.resource.model.GameTypeAddOneOutput.game_type:type_name -> pb.resource.GameType
	13, // 2: pb.resource.model.GameTypeShowOneByIdOutput.game_type:type_name -> pb.resource.GameType
	0,  // 3: pb.resource.model.GameTypeEditOneByIdInput.variable:type_name -> pb.resource.model.GameTypeVariable
	14, // 4: pb.resource.model.GameTypeShowOnesByFiltersWithSortersPaginationInput.pagination:type_name -> pb.resource.Pagination
	15, // 5: pb.resource.model.GameTypeShowOnesByFiltersWithSortersPaginationInput.filters:type_name -> pb.resource.Filter
	16, // 6: pb.resource.model.GameTypeShowOnesByFiltersWithSortersPaginationInput.sorters:type_name -> pb.resource.Sorter
	13, // 7: pb.resource.model.GameTypeShowOnesByFiltersWithSortersPaginationOutput.game_types:type_name -> pb.resource.GameType
	15, // 8: pb.resource.model.GameTypeTotalByFiltersInput.filters:type_name -> pb.resource.Filter
	1,  // 9: pb.resource.model.GameTypeModel.AddOne:input_type -> pb.resource.model.GameTypeAddOneInput
	3,  // 10: pb.resource.model.GameTypeModel.ShowOneById:input_type -> pb.resource.model.GameTypeShowOneByIdInput
	9,  // 11: pb.resource.model.GameTypeModel.ShowOnesByFiltersWithSortersPagination:input_type -> pb.resource.model.GameTypeShowOnesByFiltersWithSortersPaginationInput
	5,  // 12: pb.resource.model.GameTypeModel.EditOneById:input_type -> pb.resource.model.GameTypeEditOneByIdInput
	7,  // 13: pb.resource.model.GameTypeModel.RemoveOneById:input_type -> pb.resource.model.GameTypeRemoveOneByIdInput
	11, // 14: pb.resource.model.GameTypeModel.TotalByFilters:input_type -> pb.resource.model.GameTypeTotalByFiltersInput
	2,  // 15: pb.resource.model.GameTypeModel.AddOne:output_type -> pb.resource.model.GameTypeAddOneOutput
	4,  // 16: pb.resource.model.GameTypeModel.ShowOneById:output_type -> pb.resource.model.GameTypeShowOneByIdOutput
	10, // 17: pb.resource.model.GameTypeModel.ShowOnesByFiltersWithSortersPagination:output_type -> pb.resource.model.GameTypeShowOnesByFiltersWithSortersPaginationOutput
	6,  // 18: pb.resource.model.GameTypeModel.EditOneById:output_type -> pb.resource.model.GameTypeEditOneByIdOutput
	8,  // 19: pb.resource.model.GameTypeModel.RemoveOneById:output_type -> pb.resource.model.GameTypeRemoveOneByIdOutput
	12, // 20: pb.resource.model.GameTypeModel.TotalByFilters:output_type -> pb.resource.model.GameTypeTotalByFiltersOutput
	15, // [15:21] is the sub-list for method output_type
	9,  // [9:15] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_resource_model_game_type_proto_init() }
func file_resource_model_game_type_proto_init() {
	if File_resource_model_game_type_proto != nil {
		return
	}
	file_resource_model_game_type_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_resource_model_game_type_proto_rawDesc), len(file_resource_model_game_type_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_resource_model_game_type_proto_goTypes,
		DependencyIndexes: file_resource_model_game_type_proto_depIdxs,
		MessageInfos:      file_resource_model_game_type_proto_msgTypes,
	}.Build()
	File_resource_model_game_type_proto = out.File
	file_resource_model_game_type_proto_goTypes = nil
	file_resource_model_game_type_proto_depIdxs = nil
}
