// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: resource/model/game.proto

package pb_resource_model

import (
	pb "example/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GameAddOneInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Variable      *pb.GameVariable       `protobuf:"bytes,1,opt,name=variable,proto3" json:"variable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameAddOneInput) Reset() {
	*x = GameAddOneInput{}
	mi := &file_resource_model_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameAddOneInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameAddOneInput) ProtoMessage() {}

func (x *GameAddOneInput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameAddOneInput.ProtoReflect.Descriptor instead.
func (*GameAddOneInput) Descriptor() ([]byte, []int) {
	return file_resource_model_game_proto_rawDescGZIP(), []int{0}
}

func (x *GameAddOneInput) GetVariable() *pb.GameVariable {
	if x != nil {
		return x.Variable
	}
	return nil
}

type GameAddOneOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Game          *pb.Game               `protobuf:"bytes,1,opt,name=game,proto3" json:"game,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameAddOneOutput) Reset() {
	*x = GameAddOneOutput{}
	mi := &file_resource_model_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameAddOneOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameAddOneOutput) ProtoMessage() {}

func (x *GameAddOneOutput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameAddOneOutput.ProtoReflect.Descriptor instead.
func (*GameAddOneOutput) Descriptor() ([]byte, []int) {
	return file_resource_model_game_proto_rawDescGZIP(), []int{1}
}

func (x *GameAddOneOutput) GetGame() *pb.Game {
	if x != nil {
		return x.Game
	}
	return nil
}

type GameShowOneByKeyInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameShowOneByKeyInput) Reset() {
	*x = GameShowOneByKeyInput{}
	mi := &file_resource_model_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameShowOneByKeyInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameShowOneByKeyInput) ProtoMessage() {}

func (x *GameShowOneByKeyInput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameShowOneByKeyInput.ProtoReflect.Descriptor instead.
func (*GameShowOneByKeyInput) Descriptor() ([]byte, []int) {
	return file_resource_model_game_proto_rawDescGZIP(), []int{2}
}

func (x *GameShowOneByKeyInput) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GameShowOneByKeyOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Game          *pb.Game               `protobuf:"bytes,1,opt,name=game,proto3" json:"game,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameShowOneByKeyOutput) Reset() {
	*x = GameShowOneByKeyOutput{}
	mi := &file_resource_model_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameShowOneByKeyOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameShowOneByKeyOutput) ProtoMessage() {}

func (x *GameShowOneByKeyOutput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameShowOneByKeyOutput.ProtoReflect.Descriptor instead.
func (*GameShowOneByKeyOutput) Descriptor() ([]byte, []int) {
	return file_resource_model_game_proto_rawDescGZIP(), []int{3}
}

func (x *GameShowOneByKeyOutput) GetGame() *pb.Game {
	if x != nil {
		return x.Game
	}
	return nil
}

type GameEditOneByIdInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Variable      *pb.GameVariable       `protobuf:"bytes,1,opt,name=variable,proto3" json:"variable,omitempty"`
	Id            uint64                 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameEditOneByIdInput) Reset() {
	*x = GameEditOneByIdInput{}
	mi := &file_resource_model_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameEditOneByIdInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameEditOneByIdInput) ProtoMessage() {}

func (x *GameEditOneByIdInput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameEditOneByIdInput.ProtoReflect.Descriptor instead.
func (*GameEditOneByIdInput) Descriptor() ([]byte, []int) {
	return file_resource_model_game_proto_rawDescGZIP(), []int{4}
}

func (x *GameEditOneByIdInput) GetVariable() *pb.GameVariable {
	if x != nil {
		return x.Variable
	}
	return nil
}

func (x *GameEditOneByIdInput) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GameEditOneByIdOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameEditOneByIdOutput) Reset() {
	*x = GameEditOneByIdOutput{}
	mi := &file_resource_model_game_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameEditOneByIdOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameEditOneByIdOutput) ProtoMessage() {}

func (x *GameEditOneByIdOutput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_game_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameEditOneByIdOutput.ProtoReflect.Descriptor instead.
func (*GameEditOneByIdOutput) Descriptor() ([]byte, []int) {
	return file_resource_model_game_proto_rawDescGZIP(), []int{5}
}

type GameRemoveOneByIdInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameRemoveOneByIdInput) Reset() {
	*x = GameRemoveOneByIdInput{}
	mi := &file_resource_model_game_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameRemoveOneByIdInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameRemoveOneByIdInput) ProtoMessage() {}

func (x *GameRemoveOneByIdInput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_game_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameRemoveOneByIdInput.ProtoReflect.Descriptor instead.
func (*GameRemoveOneByIdInput) Descriptor() ([]byte, []int) {
	return file_resource_model_game_proto_rawDescGZIP(), []int{6}
}

func (x *GameRemoveOneByIdInput) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GameRemoveOneByIdOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameRemoveOneByIdOutput) Reset() {
	*x = GameRemoveOneByIdOutput{}
	mi := &file_resource_model_game_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameRemoveOneByIdOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameRemoveOneByIdOutput) ProtoMessage() {}

func (x *GameRemoveOneByIdOutput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_game_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameRemoveOneByIdOutput.ProtoReflect.Descriptor instead.
func (*GameRemoveOneByIdOutput) Descriptor() ([]byte, []int) {
	return file_resource_model_game_proto_rawDescGZIP(), []int{7}
}

type GameTotalByFiltersInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filters       []*pb.Filter           `protobuf:"bytes,1,rep,name=filters,proto3" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameTotalByFiltersInput) Reset() {
	*x = GameTotalByFiltersInput{}
	mi := &file_resource_model_game_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameTotalByFiltersInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameTotalByFiltersInput) ProtoMessage() {}

func (x *GameTotalByFiltersInput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_game_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameTotalByFiltersInput.ProtoReflect.Descriptor instead.
func (*GameTotalByFiltersInput) Descriptor() ([]byte, []int) {
	return file_resource_model_game_proto_rawDescGZIP(), []int{8}
}

func (x *GameTotalByFiltersInput) GetFilters() []*pb.Filter {
	if x != nil {
		return x.Filters
	}
	return nil
}

type GameTotalByFiltersOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         uint64                 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameTotalByFiltersOutput) Reset() {
	*x = GameTotalByFiltersOutput{}
	mi := &file_resource_model_game_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameTotalByFiltersOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameTotalByFiltersOutput) ProtoMessage() {}

func (x *GameTotalByFiltersOutput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_game_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameTotalByFiltersOutput.ProtoReflect.Descriptor instead.
func (*GameTotalByFiltersOutput) Descriptor() ([]byte, []int) {
	return file_resource_model_game_proto_rawDescGZIP(), []int{9}
}

func (x *GameTotalByFiltersOutput) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_resource_model_game_proto protoreflect.FileDescriptor

const file_resource_model_game_proto_rawDesc = "" +
	"\n" +
	"\x19resource/model/game.proto\x12\x11pb.resource.model\x1a\fcommon.proto\"?\n" +
	"\x0fGameAddOneInput\x12,\n" +
	"\bvariable\x18\x01 \x01(\v2\x10.pb.GameVariableR\bvariable\"0\n" +
	"\x10GameAddOneOutput\x12\x1c\n" +
	"\x04game\x18\x01 \x01(\v2\b.pb.GameR\x04game\")\n" +
	"\x15GameShowOneByKeyInput\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"6\n" +
	"\x16GameShowOneByKeyOutput\x12\x1c\n" +
	"\x04game\x18\x01 \x01(\v2\b.pb.GameR\x04game\"T\n" +
	"\x14GameEditOneByIdInput\x12,\n" +
	"\bvariable\x18\x01 \x01(\v2\x10.pb.GameVariableR\bvariable\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x04R\x02id\"\x17\n" +
	"\x15GameEditOneByIdOutput\"(\n" +
	"\x16GameRemoveOneByIdInput\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"\x19\n" +
	"\x17GameRemoveOneByIdOutput\"?\n" +
	"\x17GameTotalByFiltersInput\x12$\n" +
	"\afilters\x18\x01 \x03(\v2\n" +
	".pb.FilterR\afilters\"0\n" +
	"\x18GameTotalByFiltersOutput\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x04R\x05total2\xf8\x03\n" +
	"\tGameModel\x12Q\n" +
	"\x06AddOne\x12\".pb.resource.model.GameAddOneInput\x1a#.pb.resource.model.GameAddOneOutput\x12c\n" +
	"\fShowOneByKey\x12(.pb.resource.model.GameShowOneByKeyInput\x1a).pb.resource.model.GameShowOneByKeyOutput\x12`\n" +
	"\vEditOneById\x12'.pb.resource.model.GameEditOneByIdInput\x1a(.pb.resource.model.GameEditOneByIdOutput\x12f\n" +
	"\rRemoveOneById\x12).pb.resource.model.GameRemoveOneByIdInput\x1a*.pb.resource.model.GameRemoveOneByIdOutput\x12i\n" +
	"\x0eTotalByFilters\x12*.pb.resource.model.GameTotalByFiltersInput\x1a+.pb.resource.model.GameTotalByFiltersOutputB\x15Z\x13./pb_resource_modelb\x06proto3"

var (
	file_resource_model_game_proto_rawDescOnce sync.Once
	file_resource_model_game_proto_rawDescData []byte
)

func file_resource_model_game_proto_rawDescGZIP() []byte {
	file_resource_model_game_proto_rawDescOnce.Do(func() {
		file_resource_model_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_resource_model_game_proto_rawDesc), len(file_resource_model_game_proto_rawDesc)))
	})
	return file_resource_model_game_proto_rawDescData
}

var file_resource_model_game_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_resource_model_game_proto_goTypes = []any{
	(*GameAddOneInput)(nil),          // 0: pb.resource.model.GameAddOneInput
	(*GameAddOneOutput)(nil),         // 1: pb.resource.model.GameAddOneOutput
	(*GameShowOneByKeyInput)(nil),    // 2: pb.resource.model.GameShowOneByKeyInput
	(*GameShowOneByKeyOutput)(nil),   // 3: pb.resource.model.GameShowOneByKeyOutput
	(*GameEditOneByIdInput)(nil),     // 4: pb.resource.model.GameEditOneByIdInput
	(*GameEditOneByIdOutput)(nil),    // 5: pb.resource.model.GameEditOneByIdOutput
	(*GameRemoveOneByIdInput)(nil),   // 6: pb.resource.model.GameRemoveOneByIdInput
	(*GameRemoveOneByIdOutput)(nil),  // 7: pb.resource.model.GameRemoveOneByIdOutput
	(*GameTotalByFiltersInput)(nil),  // 8: pb.resource.model.GameTotalByFiltersInput
	(*GameTotalByFiltersOutput)(nil), // 9: pb.resource.model.GameTotalByFiltersOutput
	(*pb.GameVariable)(nil),          // 10: pb.GameVariable
	(*pb.Game)(nil),                  // 11: pb.Game
	(*pb.Filter)(nil),                // 12: pb.Filter
}
var file_resource_model_game_proto_depIdxs = []int32{
	10, // 0: pb.resource.model.GameAddOneInput.variable:type_name -> pb.GameVariable
	11, // 1: pb.resource.model.GameAddOneOutput.game:type_name -> pb.Game
	11, // 2: pb.resource.model.GameShowOneByKeyOutput.game:type_name -> pb.Game
	10, // 3: pb.resource.model.GameEditOneByIdInput.variable:type_name -> pb.GameVariable
	12, // 4: pb.resource.model.GameTotalByFiltersInput.filters:type_name -> pb.Filter
	0,  // 5: pb.resource.model.GameModel.AddOne:input_type -> pb.resource.model.GameAddOneInput
	2,  // 6: pb.resource.model.GameModel.ShowOneByKey:input_type -> pb.resource.model.GameShowOneByKeyInput
	4,  // 7: pb.resource.model.GameModel.EditOneById:input_type -> pb.resource.model.GameEditOneByIdInput
	6,  // 8: pb.resource.model.GameModel.RemoveOneById:input_type -> pb.resource.model.GameRemoveOneByIdInput
	8,  // 9: pb.resource.model.GameModel.TotalByFilters:input_type -> pb.resource.model.GameTotalByFiltersInput
	1,  // 10: pb.resource.model.GameModel.AddOne:output_type -> pb.resource.model.GameAddOneOutput
	3,  // 11: pb.resource.model.GameModel.ShowOneByKey:output_type -> pb.resource.model.GameShowOneByKeyOutput
	5,  // 12: pb.resource.model.GameModel.EditOneById:output_type -> pb.resource.model.GameEditOneByIdOutput
	7,  // 13: pb.resource.model.GameModel.RemoveOneById:output_type -> pb.resource.model.GameRemoveOneByIdOutput
	9,  // 14: pb.resource.model.GameModel.TotalByFilters:output_type -> pb.resource.model.GameTotalByFiltersOutput
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_resource_model_game_proto_init() }
func file_resource_model_game_proto_init() {
	if File_resource_model_game_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_resource_model_game_proto_rawDesc), len(file_resource_model_game_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_resource_model_game_proto_goTypes,
		DependencyIndexes: file_resource_model_game_proto_depIdxs,
		MessageInfos:      file_resource_model_game_proto_msgTypes,
	}.Build()
	File_resource_model_game_proto = out.File
	file_resource_model_game_proto_goTypes = nil
	file_resource_model_game_proto_depIdxs = nil
}
