// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: resource/model/game.proto

package pb_resource_model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GameWhere struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Operator      string                 `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"`
	Value         *structpb.Value        `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameWhere) Reset() {
	*x = GameWhere{}
	mi := &file_resource_model_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameWhere) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameWhere) ProtoMessage() {}

func (x *GameWhere) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameWhere.ProtoReflect.Descriptor instead.
func (*GameWhere) Descriptor() ([]byte, []int) {
	return file_resource_model_game_proto_rawDescGZIP(), []int{0}
}

func (x *GameWhere) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *GameWhere) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *GameWhere) GetValue() *structpb.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

type GameOrder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameOrder) Reset() {
	*x = GameOrder{}
	mi := &file_resource_model_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameOrder) ProtoMessage() {}

func (x *GameOrder) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameOrder.ProtoReflect.Descriptor instead.
func (*GameOrder) Descriptor() ([]byte, []int) {
	return file_resource_model_game_proto_rawDescGZIP(), []int{1}
}

func (x *GameOrder) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *GameOrder) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type GameLimit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        uint64                 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Count         uint64                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameLimit) Reset() {
	*x = GameLimit{}
	mi := &file_resource_model_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameLimit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameLimit) ProtoMessage() {}

func (x *GameLimit) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameLimit.ProtoReflect.Descriptor instead.
func (*GameLimit) Descriptor() ([]byte, []int) {
	return file_resource_model_game_proto_rawDescGZIP(), []int{2}
}

func (x *GameLimit) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GameLimit) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GameType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameType) Reset() {
	*x = GameType{}
	mi := &file_resource_model_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameType) ProtoMessage() {}

func (x *GameType) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameType.ProtoReflect.Descriptor instead.
func (*GameType) Descriptor() ([]byte, []int) {
	return file_resource_model_game_proto_rawDescGZIP(), []int{3}
}

func (x *GameType) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GameType) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GameType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GameType) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GameType) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *GameType) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type Game struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	GameTypeId    uint32                 `protobuf:"varint,2,opt,name=game_type_id,json=gameTypeId,proto3" json:"game_type_id,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	GameType      *GameType              `protobuf:"bytes,9,opt,name=game_type,json=gameType,proto3" json:"game_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Game) Reset() {
	*x = Game{}
	mi := &file_resource_model_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Game) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Game) ProtoMessage() {}

func (x *Game) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Game.ProtoReflect.Descriptor instead.
func (*Game) Descriptor() ([]byte, []int) {
	return file_resource_model_game_proto_rawDescGZIP(), []int{4}
}

func (x *Game) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Game) GetGameTypeId() uint32 {
	if x != nil {
		return x.GameTypeId
	}
	return 0
}

func (x *Game) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Game) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Game) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Game) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Game) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Game) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *Game) GetGameType() *GameType {
	if x != nil {
		return x.GameType
	}
	return nil
}

type GameAddOneInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameTypeId    *uint32                `protobuf:"varint,1,opt,name=game_type_id,json=gameTypeId,proto3,oneof" json:"game_type_id,omitempty"`
	Key           *string                `protobuf:"bytes,2,opt,name=key,proto3,oneof" json:"key,omitempty"`
	Name          *string                `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameAddOneInput) Reset() {
	*x = GameAddOneInput{}
	mi := &file_resource_model_game_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameAddOneInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameAddOneInput) ProtoMessage() {}

func (x *GameAddOneInput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_game_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameAddOneInput.ProtoReflect.Descriptor instead.
func (*GameAddOneInput) Descriptor() ([]byte, []int) {
	return file_resource_model_game_proto_rawDescGZIP(), []int{5}
}

func (x *GameAddOneInput) GetGameTypeId() uint32 {
	if x != nil && x.GameTypeId != nil {
		return *x.GameTypeId
	}
	return 0
}

func (x *GameAddOneInput) GetKey() string {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return ""
}

func (x *GameAddOneInput) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *GameAddOneInput) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

type GameAddOneOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	GameTypeId    uint32                 `protobuf:"varint,2,opt,name=game_type_id,json=gameTypeId,proto3" json:"game_type_id,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameAddOneOutput) Reset() {
	*x = GameAddOneOutput{}
	mi := &file_resource_model_game_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameAddOneOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameAddOneOutput) ProtoMessage() {}

func (x *GameAddOneOutput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_game_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameAddOneOutput.ProtoReflect.Descriptor instead.
func (*GameAddOneOutput) Descriptor() ([]byte, []int) {
	return file_resource_model_game_proto_rawDescGZIP(), []int{6}
}

func (x *GameAddOneOutput) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GameAddOneOutput) GetGameTypeId() uint32 {
	if x != nil {
		return x.GameTypeId
	}
	return 0
}

func (x *GameAddOneOutput) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GameAddOneOutput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GameAddOneOutput) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GameAddOneOutput) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GameAddOneOutput) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *GameAddOneOutput) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type GameShowOneByIdInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameShowOneByIdInput) Reset() {
	*x = GameShowOneByIdInput{}
	mi := &file_resource_model_game_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameShowOneByIdInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameShowOneByIdInput) ProtoMessage() {}

func (x *GameShowOneByIdInput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_game_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameShowOneByIdInput.ProtoReflect.Descriptor instead.
func (*GameShowOneByIdInput) Descriptor() ([]byte, []int) {
	return file_resource_model_game_proto_rawDescGZIP(), []int{7}
}

func (x *GameShowOneByIdInput) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GameShowOneByIdOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	GameTypeId    uint32                 `protobuf:"varint,2,opt,name=game_type_id,json=gameTypeId,proto3" json:"game_type_id,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	GameType      *GameType              `protobuf:"bytes,9,opt,name=game_type,json=gameType,proto3" json:"game_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameShowOneByIdOutput) Reset() {
	*x = GameShowOneByIdOutput{}
	mi := &file_resource_model_game_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameShowOneByIdOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameShowOneByIdOutput) ProtoMessage() {}

func (x *GameShowOneByIdOutput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_game_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameShowOneByIdOutput.ProtoReflect.Descriptor instead.
func (*GameShowOneByIdOutput) Descriptor() ([]byte, []int) {
	return file_resource_model_game_proto_rawDescGZIP(), []int{8}
}

func (x *GameShowOneByIdOutput) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GameShowOneByIdOutput) GetGameTypeId() uint32 {
	if x != nil {
		return x.GameTypeId
	}
	return 0
}

func (x *GameShowOneByIdOutput) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GameShowOneByIdOutput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GameShowOneByIdOutput) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GameShowOneByIdOutput) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GameShowOneByIdOutput) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *GameShowOneByIdOutput) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *GameShowOneByIdOutput) GetGameType() *GameType {
	if x != nil {
		return x.GameType
	}
	return nil
}

type GameEditOneByIdInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	GameTypeId    *uint32                `protobuf:"varint,2,opt,name=game_type_id,json=gameTypeId,proto3,oneof" json:"game_type_id,omitempty"`
	Key           *string                `protobuf:"bytes,3,opt,name=key,proto3,oneof" json:"key,omitempty"`
	Name          *string                `protobuf:"bytes,4,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,5,opt,name=description,proto3,oneof" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameEditOneByIdInput) Reset() {
	*x = GameEditOneByIdInput{}
	mi := &file_resource_model_game_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameEditOneByIdInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameEditOneByIdInput) ProtoMessage() {}

func (x *GameEditOneByIdInput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_game_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameEditOneByIdInput.ProtoReflect.Descriptor instead.
func (*GameEditOneByIdInput) Descriptor() ([]byte, []int) {
	return file_resource_model_game_proto_rawDescGZIP(), []int{9}
}

func (x *GameEditOneByIdInput) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GameEditOneByIdInput) GetGameTypeId() uint32 {
	if x != nil && x.GameTypeId != nil {
		return *x.GameTypeId
	}
	return 0
}

func (x *GameEditOneByIdInput) GetKey() string {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return ""
}

func (x *GameEditOneByIdInput) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *GameEditOneByIdInput) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

type GameEditOneByIdOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameEditOneByIdOutput) Reset() {
	*x = GameEditOneByIdOutput{}
	mi := &file_resource_model_game_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameEditOneByIdOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameEditOneByIdOutput) ProtoMessage() {}

func (x *GameEditOneByIdOutput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_game_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameEditOneByIdOutput.ProtoReflect.Descriptor instead.
func (*GameEditOneByIdOutput) Descriptor() ([]byte, []int) {
	return file_resource_model_game_proto_rawDescGZIP(), []int{10}
}

func (x *GameEditOneByIdOutput) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type GameRemoveOneByIdInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameRemoveOneByIdInput) Reset() {
	*x = GameRemoveOneByIdInput{}
	mi := &file_resource_model_game_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameRemoveOneByIdInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameRemoveOneByIdInput) ProtoMessage() {}

func (x *GameRemoveOneByIdInput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_game_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameRemoveOneByIdInput.ProtoReflect.Descriptor instead.
func (*GameRemoveOneByIdInput) Descriptor() ([]byte, []int) {
	return file_resource_model_game_proto_rawDescGZIP(), []int{11}
}

func (x *GameRemoveOneByIdInput) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GameRemoveOneByIdOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameRemoveOneByIdOutput) Reset() {
	*x = GameRemoveOneByIdOutput{}
	mi := &file_resource_model_game_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameRemoveOneByIdOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameRemoveOneByIdOutput) ProtoMessage() {}

func (x *GameRemoveOneByIdOutput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_game_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameRemoveOneByIdOutput.ProtoReflect.Descriptor instead.
func (*GameRemoveOneByIdOutput) Descriptor() ([]byte, []int) {
	return file_resource_model_game_proto_rawDescGZIP(), []int{12}
}

func (x *GameRemoveOneByIdOutput) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type GameShowOnesByWheresWithOrdersLimitInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wheres        []*GameWhere           `protobuf:"bytes,2,rep,name=wheres,proto3" json:"wheres,omitempty"`
	Orders        []*GameOrder           `protobuf:"bytes,3,rep,name=orders,proto3" json:"orders,omitempty"`
	Limit         *GameLimit             `protobuf:"bytes,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameShowOnesByWheresWithOrdersLimitInput) Reset() {
	*x = GameShowOnesByWheresWithOrdersLimitInput{}
	mi := &file_resource_model_game_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameShowOnesByWheresWithOrdersLimitInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameShowOnesByWheresWithOrdersLimitInput) ProtoMessage() {}

func (x *GameShowOnesByWheresWithOrdersLimitInput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_game_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameShowOnesByWheresWithOrdersLimitInput.ProtoReflect.Descriptor instead.
func (*GameShowOnesByWheresWithOrdersLimitInput) Descriptor() ([]byte, []int) {
	return file_resource_model_game_proto_rawDescGZIP(), []int{13}
}

func (x *GameShowOnesByWheresWithOrdersLimitInput) GetWheres() []*GameWhere {
	if x != nil {
		return x.Wheres
	}
	return nil
}

func (x *GameShowOnesByWheresWithOrdersLimitInput) GetOrders() []*GameOrder {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *GameShowOnesByWheresWithOrdersLimitInput) GetLimit() *GameLimit {
	if x != nil {
		return x.Limit
	}
	return nil
}

type GameShowOnesByWheresWithOrdersLimitOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Games         []*Game                `protobuf:"bytes,1,rep,name=games,proto3" json:"games,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameShowOnesByWheresWithOrdersLimitOutput) Reset() {
	*x = GameShowOnesByWheresWithOrdersLimitOutput{}
	mi := &file_resource_model_game_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameShowOnesByWheresWithOrdersLimitOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameShowOnesByWheresWithOrdersLimitOutput) ProtoMessage() {}

func (x *GameShowOnesByWheresWithOrdersLimitOutput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_game_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameShowOnesByWheresWithOrdersLimitOutput.ProtoReflect.Descriptor instead.
func (*GameShowOnesByWheresWithOrdersLimitOutput) Descriptor() ([]byte, []int) {
	return file_resource_model_game_proto_rawDescGZIP(), []int{14}
}

func (x *GameShowOnesByWheresWithOrdersLimitOutput) GetGames() []*Game {
	if x != nil {
		return x.Games
	}
	return nil
}

type GameTotalByWheresInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wheres        []*GameWhere           `protobuf:"bytes,1,rep,name=wheres,proto3" json:"wheres,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameTotalByWheresInput) Reset() {
	*x = GameTotalByWheresInput{}
	mi := &file_resource_model_game_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameTotalByWheresInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameTotalByWheresInput) ProtoMessage() {}

func (x *GameTotalByWheresInput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_game_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameTotalByWheresInput.ProtoReflect.Descriptor instead.
func (*GameTotalByWheresInput) Descriptor() ([]byte, []int) {
	return file_resource_model_game_proto_rawDescGZIP(), []int{15}
}

func (x *GameTotalByWheresInput) GetWheres() []*GameWhere {
	if x != nil {
		return x.Wheres
	}
	return nil
}

type GameTotalByWheresOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         uint64                 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameTotalByWheresOutput) Reset() {
	*x = GameTotalByWheresOutput{}
	mi := &file_resource_model_game_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameTotalByWheresOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameTotalByWheresOutput) ProtoMessage() {}

func (x *GameTotalByWheresOutput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_model_game_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameTotalByWheresOutput.ProtoReflect.Descriptor instead.
func (*GameTotalByWheresOutput) Descriptor() ([]byte, []int) {
	return file_resource_model_game_proto_rawDescGZIP(), []int{16}
}

func (x *GameTotalByWheresOutput) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_resource_model_game_proto protoreflect.FileDescriptor

const file_resource_model_game_proto_rawDesc = "" +
	"\n" +
	"\x19resource/model/game.proto\x12\x11pb.resource.model\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"k\n" +
	"\tGameWhere\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x1a\n" +
	"\boperator\x18\x02 \x01(\tR\boperator\x12,\n" +
	"\x05value\x18\x03 \x01(\v2\x16.google.protobuf.ValueR\x05value\"7\n" +
	"\tGameOrder\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"9\n" +
	"\tGameLimit\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x04R\x06offset\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x04R\x05count\"\xf1\x01\n" +
	"\bGameType\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\"\xeb\x02\n" +
	"\x04Game\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12 \n" +
	"\fgame_type_id\x18\x02 \x01(\rR\n" +
	"gameTypeId\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\x128\n" +
	"\tgame_type\x18\t \x01(\v2\x1b.pb.resource.model.GameTypeR\bgameType\"\xc1\x01\n" +
	"\x0fGameAddOneInput\x12%\n" +
	"\fgame_type_id\x18\x01 \x01(\rH\x00R\n" +
	"gameTypeId\x88\x01\x01\x12\x15\n" +
	"\x03key\x18\x02 \x01(\tH\x01R\x03key\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x03 \x01(\tH\x02R\x04name\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x03R\vdescription\x88\x01\x01B\x0f\n" +
	"\r_game_type_idB\x06\n" +
	"\x04_keyB\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_description\"\xbd\x02\n" +
	"\x10GameAddOneOutput\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12 \n" +
	"\fgame_type_id\x18\x02 \x01(\rR\n" +
	"gameTypeId\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\"&\n" +
	"\x14GameShowOneByIdInput\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"\xfc\x02\n" +
	"\x15GameShowOneByIdOutput\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12 \n" +
	"\fgame_type_id\x18\x02 \x01(\rR\n" +
	"gameTypeId\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\x128\n" +
	"\tgame_type\x18\t \x01(\v2\x1b.pb.resource.model.GameTypeR\bgameType\"\xd6\x01\n" +
	"\x14GameEditOneByIdInput\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12%\n" +
	"\fgame_type_id\x18\x02 \x01(\rH\x00R\n" +
	"gameTypeId\x88\x01\x01\x12\x15\n" +
	"\x03key\x18\x03 \x01(\tH\x01R\x03key\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x04 \x01(\tH\x02R\x04name\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x05 \x01(\tH\x03R\vdescription\x88\x01\x01B\x0f\n" +
	"\r_game_type_idB\x06\n" +
	"\x04_keyB\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_description\"/\n" +
	"\x15GameEditOneByIdOutput\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\"(\n" +
	"\x16GameRemoveOneByIdInput\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"1\n" +
	"\x17GameRemoveOneByIdOutput\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\"\xca\x01\n" +
	"(GameShowOnesByWheresWithOrdersLimitInput\x124\n" +
	"\x06wheres\x18\x02 \x03(\v2\x1c.pb.resource.model.GameWhereR\x06wheres\x124\n" +
	"\x06orders\x18\x03 \x03(\v2\x1c.pb.resource.model.GameOrderR\x06orders\x122\n" +
	"\x05limit\x18\x01 \x01(\v2\x1c.pb.resource.model.GameLimitR\x05limit\"Z\n" +
	")GameShowOnesByWheresWithOrdersLimitOutput\x12-\n" +
	"\x05games\x18\x01 \x03(\v2\x17.pb.resource.model.GameR\x05games\"N\n" +
	"\x16GameTotalByWheresInput\x124\n" +
	"\x06wheres\x18\x01 \x03(\v2\x1c.pb.resource.model.GameWhereR\x06wheres\"/\n" +
	"\x17GameTotalByWheresOutput\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x04R\x05total2\x91\x05\n" +
	"\tGameModel\x12Q\n" +
	"\x06AddOne\x12\".pb.resource.model.GameAddOneInput\x1a#.pb.resource.model.GameAddOneOutput\x12`\n" +
	"\vShowOneById\x12'.pb.resource.model.GameShowOneByIdInput\x1a(.pb.resource.model.GameShowOneByIdOutput\x12\x9c\x01\n" +
	"\x1fShowOnesByWheresWithOrdersLimit\x12;.pb.resource.model.GameShowOnesByWheresWithOrdersLimitInput\x1a<.pb.resource.model.GameShowOnesByWheresWithOrdersLimitOutput\x12`\n" +
	"\vEditOneById\x12'.pb.resource.model.GameEditOneByIdInput\x1a(.pb.resource.model.GameEditOneByIdOutput\x12f\n" +
	"\rRemoveOneById\x12).pb.resource.model.GameRemoveOneByIdInput\x1a*.pb.resource.model.GameRemoveOneByIdOutput\x12f\n" +
	"\rTotalByWheres\x12).pb.resource.model.GameTotalByWheresInput\x1a*.pb.resource.model.GameTotalByWheresOutputB\x15Z\x13./pb_resource_modelb\x06proto3"

var (
	file_resource_model_game_proto_rawDescOnce sync.Once
	file_resource_model_game_proto_rawDescData []byte
)

func file_resource_model_game_proto_rawDescGZIP() []byte {
	file_resource_model_game_proto_rawDescOnce.Do(func() {
		file_resource_model_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_resource_model_game_proto_rawDesc), len(file_resource_model_game_proto_rawDesc)))
	})
	return file_resource_model_game_proto_rawDescData
}

var file_resource_model_game_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_resource_model_game_proto_goTypes = []any{
	(*GameWhere)(nil),                                 // 0: pb.resource.model.GameWhere
	(*GameOrder)(nil),                                 // 1: pb.resource.model.GameOrder
	(*GameLimit)(nil),                                 // 2: pb.resource.model.GameLimit
	(*GameType)(nil),                                  // 3: pb.resource.model.GameType
	(*Game)(nil),                                      // 4: pb.resource.model.Game
	(*GameAddOneInput)(nil),                           // 5: pb.resource.model.GameAddOneInput
	(*GameAddOneOutput)(nil),                          // 6: pb.resource.model.GameAddOneOutput
	(*GameShowOneByIdInput)(nil),                      // 7: pb.resource.model.GameShowOneByIdInput
	(*GameShowOneByIdOutput)(nil),                     // 8: pb.resource.model.GameShowOneByIdOutput
	(*GameEditOneByIdInput)(nil),                      // 9: pb.resource.model.GameEditOneByIdInput
	(*GameEditOneByIdOutput)(nil),                     // 10: pb.resource.model.GameEditOneByIdOutput
	(*GameRemoveOneByIdInput)(nil),                    // 11: pb.resource.model.GameRemoveOneByIdInput
	(*GameRemoveOneByIdOutput)(nil),                   // 12: pb.resource.model.GameRemoveOneByIdOutput
	(*GameShowOnesByWheresWithOrdersLimitInput)(nil),  // 13: pb.resource.model.GameShowOnesByWheresWithOrdersLimitInput
	(*GameShowOnesByWheresWithOrdersLimitOutput)(nil), // 14: pb.resource.model.GameShowOnesByWheresWithOrdersLimitOutput
	(*GameTotalByWheresInput)(nil),                    // 15: pb.resource.model.GameTotalByWheresInput
	(*GameTotalByWheresOutput)(nil),                   // 16: pb.resource.model.GameTotalByWheresOutput
	(*structpb.Value)(nil),                            // 17: google.protobuf.Value
	(*timestamppb.Timestamp)(nil),                     // 18: google.protobuf.Timestamp
}
var file_resource_model_game_proto_depIdxs = []int32{
	17, // 0: pb.resource.model.GameWhere.value:type_name -> google.protobuf.Value
	18, // 1: pb.resource.model.GameType.created_at:type_name -> google.protobuf.Timestamp
	18, // 2: pb.resource.model.GameType.updated_at:type_name -> google.protobuf.Timestamp
	18, // 3: pb.resource.model.GameType.deleted_at:type_name -> google.protobuf.Timestamp
	18, // 4: pb.resource.model.Game.created_at:type_name -> google.protobuf.Timestamp
	18, // 5: pb.resource.model.Game.updated_at:type_name -> google.protobuf.Timestamp
	18, // 6: pb.resource.model.Game.deleted_at:type_name -> google.protobuf.Timestamp
	3,  // 7: pb.resource.model.Game.game_type:type_name -> pb.resource.model.GameType
	18, // 8: pb.resource.model.GameAddOneOutput.created_at:type_name -> google.protobuf.Timestamp
	18, // 9: pb.resource.model.GameAddOneOutput.updated_at:type_name -> google.protobuf.Timestamp
	18, // 10: pb.resource.model.GameAddOneOutput.deleted_at:type_name -> google.protobuf.Timestamp
	18, // 11: pb.resource.model.GameShowOneByIdOutput.created_at:type_name -> google.protobuf.Timestamp
	18, // 12: pb.resource.model.GameShowOneByIdOutput.updated_at:type_name -> google.protobuf.Timestamp
	18, // 13: pb.resource.model.GameShowOneByIdOutput.deleted_at:type_name -> google.protobuf.Timestamp
	3,  // 14: pb.resource.model.GameShowOneByIdOutput.game_type:type_name -> pb.resource.model.GameType
	0,  // 15: pb.resource.model.GameShowOnesByWheresWithOrdersLimitInput.wheres:type_name -> pb.resource.model.GameWhere
	1,  // 16: pb.resource.model.GameShowOnesByWheresWithOrdersLimitInput.orders:type_name -> pb.resource.model.GameOrder
	2,  // 17: pb.resource.model.GameShowOnesByWheresWithOrdersLimitInput.limit:type_name -> pb.resource.model.GameLimit
	4,  // 18: pb.resource.model.GameShowOnesByWheresWithOrdersLimitOutput.games:type_name -> pb.resource.model.Game
	0,  // 19: pb.resource.model.GameTotalByWheresInput.wheres:type_name -> pb.resource.model.GameWhere
	5,  // 20: pb.resource.model.GameModel.AddOne:input_type -> pb.resource.model.GameAddOneInput
	7,  // 21: pb.resource.model.GameModel.ShowOneById:input_type -> pb.resource.model.GameShowOneByIdInput
	13, // 22: pb.resource.model.GameModel.ShowOnesByWheresWithOrdersLimit:input_type -> pb.resource.model.GameShowOnesByWheresWithOrdersLimitInput
	9,  // 23: pb.resource.model.GameModel.EditOneById:input_type -> pb.resource.model.GameEditOneByIdInput
	11, // 24: pb.resource.model.GameModel.RemoveOneById:input_type -> pb.resource.model.GameRemoveOneByIdInput
	15, // 25: pb.resource.model.GameModel.TotalByWheres:input_type -> pb.resource.model.GameTotalByWheresInput
	6,  // 26: pb.resource.model.GameModel.AddOne:output_type -> pb.resource.model.GameAddOneOutput
	8,  // 27: pb.resource.model.GameModel.ShowOneById:output_type -> pb.resource.model.GameShowOneByIdOutput
	14, // 28: pb.resource.model.GameModel.ShowOnesByWheresWithOrdersLimit:output_type -> pb.resource.model.GameShowOnesByWheresWithOrdersLimitOutput
	10, // 29: pb.resource.model.GameModel.EditOneById:output_type -> pb.resource.model.GameEditOneByIdOutput
	12, // 30: pb.resource.model.GameModel.RemoveOneById:output_type -> pb.resource.model.GameRemoveOneByIdOutput
	16, // 31: pb.resource.model.GameModel.TotalByWheres:output_type -> pb.resource.model.GameTotalByWheresOutput
	26, // [26:32] is the sub-list for method output_type
	20, // [20:26] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_resource_model_game_proto_init() }
func file_resource_model_game_proto_init() {
	if File_resource_model_game_proto != nil {
		return
	}
	file_resource_model_game_proto_msgTypes[5].OneofWrappers = []any{}
	file_resource_model_game_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_resource_model_game_proto_rawDesc), len(file_resource_model_game_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_resource_model_game_proto_goTypes,
		DependencyIndexes: file_resource_model_game_proto_depIdxs,
		MessageInfos:      file_resource_model_game_proto_msgTypes,
	}.Build()
	File_resource_model_game_proto = out.File
	file_resource_model_game_proto_goTypes = nil
	file_resource_model_game_proto_depIdxs = nil
}
