// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: resource/model/table.proto

package pb_resource_model

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TableModel_AddOne_FullMethodName         = "/pb.resource.model.TableModel/AddOne"
	TableModel_EditOneById_FullMethodName    = "/pb.resource.model.TableModel/EditOneById"
	TableModel_RemoveOneById_FullMethodName  = "/pb.resource.model.TableModel/RemoveOneById"
	TableModel_TotalByFilters_FullMethodName = "/pb.resource.model.TableModel/TotalByFilters"
)

// TableModelClient is the client API for TableModel service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TableModelClient interface {
	AddOne(ctx context.Context, in *TableAddOneInput, opts ...grpc.CallOption) (*TableAddOneOutput, error)
	EditOneById(ctx context.Context, in *TableEditOneByIdInput, opts ...grpc.CallOption) (*TableEditOneByIdOutput, error)
	RemoveOneById(ctx context.Context, in *TableRemoveOneByIdInput, opts ...grpc.CallOption) (*TableRemoveOneByIdOutput, error)
	TotalByFilters(ctx context.Context, in *TableTotalByFiltersInput, opts ...grpc.CallOption) (*TableTotalByFiltersOutput, error)
}

type tableModelClient struct {
	cc grpc.ClientConnInterface
}

func NewTableModelClient(cc grpc.ClientConnInterface) TableModelClient {
	return &tableModelClient{cc}
}

func (c *tableModelClient) AddOne(ctx context.Context, in *TableAddOneInput, opts ...grpc.CallOption) (*TableAddOneOutput, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TableAddOneOutput)
	err := c.cc.Invoke(ctx, TableModel_AddOne_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tableModelClient) EditOneById(ctx context.Context, in *TableEditOneByIdInput, opts ...grpc.CallOption) (*TableEditOneByIdOutput, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TableEditOneByIdOutput)
	err := c.cc.Invoke(ctx, TableModel_EditOneById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tableModelClient) RemoveOneById(ctx context.Context, in *TableRemoveOneByIdInput, opts ...grpc.CallOption) (*TableRemoveOneByIdOutput, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TableRemoveOneByIdOutput)
	err := c.cc.Invoke(ctx, TableModel_RemoveOneById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tableModelClient) TotalByFilters(ctx context.Context, in *TableTotalByFiltersInput, opts ...grpc.CallOption) (*TableTotalByFiltersOutput, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TableTotalByFiltersOutput)
	err := c.cc.Invoke(ctx, TableModel_TotalByFilters_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TableModelServer is the server API for TableModel service.
// All implementations must embed UnimplementedTableModelServer
// for forward compatibility.
type TableModelServer interface {
	AddOne(context.Context, *TableAddOneInput) (*TableAddOneOutput, error)
	EditOneById(context.Context, *TableEditOneByIdInput) (*TableEditOneByIdOutput, error)
	RemoveOneById(context.Context, *TableRemoveOneByIdInput) (*TableRemoveOneByIdOutput, error)
	TotalByFilters(context.Context, *TableTotalByFiltersInput) (*TableTotalByFiltersOutput, error)
	mustEmbedUnimplementedTableModelServer()
}

// UnimplementedTableModelServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTableModelServer struct{}

func (UnimplementedTableModelServer) AddOne(context.Context, *TableAddOneInput) (*TableAddOneOutput, error) {
	return nil, status.Error(codes.Unimplemented, "method AddOne not implemented")
}
func (UnimplementedTableModelServer) EditOneById(context.Context, *TableEditOneByIdInput) (*TableEditOneByIdOutput, error) {
	return nil, status.Error(codes.Unimplemented, "method EditOneById not implemented")
}
func (UnimplementedTableModelServer) RemoveOneById(context.Context, *TableRemoveOneByIdInput) (*TableRemoveOneByIdOutput, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveOneById not implemented")
}
func (UnimplementedTableModelServer) TotalByFilters(context.Context, *TableTotalByFiltersInput) (*TableTotalByFiltersOutput, error) {
	return nil, status.Error(codes.Unimplemented, "method TotalByFilters not implemented")
}
func (UnimplementedTableModelServer) mustEmbedUnimplementedTableModelServer() {}
func (UnimplementedTableModelServer) testEmbeddedByValue()                    {}

// UnsafeTableModelServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TableModelServer will
// result in compilation errors.
type UnsafeTableModelServer interface {
	mustEmbedUnimplementedTableModelServer()
}

func RegisterTableModelServer(s grpc.ServiceRegistrar, srv TableModelServer) {
	// If the following call panics, it indicates UnimplementedTableModelServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TableModel_ServiceDesc, srv)
}

func _TableModel_AddOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TableAddOneInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TableModelServer).AddOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TableModel_AddOne_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TableModelServer).AddOne(ctx, req.(*TableAddOneInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _TableModel_EditOneById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TableEditOneByIdInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TableModelServer).EditOneById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TableModel_EditOneById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TableModelServer).EditOneById(ctx, req.(*TableEditOneByIdInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _TableModel_RemoveOneById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TableRemoveOneByIdInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TableModelServer).RemoveOneById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TableModel_RemoveOneById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TableModelServer).RemoveOneById(ctx, req.(*TableRemoveOneByIdInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _TableModel_TotalByFilters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TableTotalByFiltersInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TableModelServer).TotalByFilters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TableModel_TotalByFilters_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TableModelServer).TotalByFilters(ctx, req.(*TableTotalByFiltersInput))
	}
	return interceptor(ctx, in, info, handler)
}

// TableModel_ServiceDesc is the grpc.ServiceDesc for TableModel service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TableModel_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.resource.model.TableModel",
	HandlerType: (*TableModelServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddOne",
			Handler:    _TableModel_AddOne_Handler,
		},
		{
			MethodName: "EditOneById",
			Handler:    _TableModel_EditOneById_Handler,
		},
		{
			MethodName: "RemoveOneById",
			Handler:    _TableModel_RemoveOneById_Handler,
		},
		{
			MethodName: "TotalByFilters",
			Handler:    _TableModel_TotalByFilters_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "resource/model/table.proto",
}
