// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: resource/resource.proto

package pb_resource

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Operator      string                 `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"`
	Value         *structpb.Value        `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Filter) Reset() {
	*x = Filter{}
	mi := &file_resource_resource_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_resource_resource_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_resource_resource_proto_rawDescGZIP(), []int{0}
}

func (x *Filter) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *Filter) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *Filter) GetValue() *structpb.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

type Sorter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Order         string                 `protobuf:"bytes,2,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sorter) Reset() {
	*x = Sorter{}
	mi := &file_resource_resource_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sorter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sorter) ProtoMessage() {}

func (x *Sorter) ProtoReflect() protoreflect.Message {
	mi := &file_resource_resource_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sorter.ProtoReflect.Descriptor instead.
func (*Sorter) Descriptor() ([]byte, []int) {
	return file_resource_resource_proto_rawDescGZIP(), []int{1}
}

func (x *Sorter) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *Sorter) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

type Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          uint64                 `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	Page          uint64                 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_resource_resource_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_resource_resource_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_resource_resource_proto_rawDescGZIP(), []int{2}
}

func (x *Pagination) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Pagination) GetPage() uint64 {
	if x != nil {
		return x.Page
	}
	return 0
}

var File_resource_resource_proto protoreflect.FileDescriptor

const file_resource_resource_proto_rawDesc = "" +
	"\n" +
	"\x17resource/resource.proto\x12\vpb.resource\x1a\x1cgoogle/protobuf/struct.proto\"h\n" +
	"\x06Filter\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x1a\n" +
	"\boperator\x18\x02 \x01(\tR\boperator\x12,\n" +
	"\x05value\x18\x03 \x01(\v2\x16.google.protobuf.ValueR\x05value\"4\n" +
	"\x06Sorter\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x14\n" +
	"\x05order\x18\x02 \x01(\tR\x05order\"4\n" +
	"\n" +
	"Pagination\x12\x12\n" +
	"\x04size\x18\x01 \x01(\x04R\x04size\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x04R\x04pageB!Z\x1fexample/pb/resource;pb_resourceb\x06proto3"

var (
	file_resource_resource_proto_rawDescOnce sync.Once
	file_resource_resource_proto_rawDescData []byte
)

func file_resource_resource_proto_rawDescGZIP() []byte {
	file_resource_resource_proto_rawDescOnce.Do(func() {
		file_resource_resource_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_resource_resource_proto_rawDesc), len(file_resource_resource_proto_rawDesc)))
	})
	return file_resource_resource_proto_rawDescData
}

var file_resource_resource_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_resource_resource_proto_goTypes = []any{
	(*Filter)(nil),         // 0: pb.resource.Filter
	(*Sorter)(nil),         // 1: pb.resource.Sorter
	(*Pagination)(nil),     // 2: pb.resource.Pagination
	(*structpb.Value)(nil), // 3: google.protobuf.Value
}
var file_resource_resource_proto_depIdxs = []int32{
	3, // 0: pb.resource.Filter.value:type_name -> google.protobuf.Value
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_resource_resource_proto_init() }
func file_resource_resource_proto_init() {
	if File_resource_resource_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_resource_resource_proto_rawDesc), len(file_resource_resource_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_resource_resource_proto_goTypes,
		DependencyIndexes: file_resource_resource_proto_depIdxs,
		MessageInfos:      file_resource_resource_proto_msgTypes,
	}.Build()
	File_resource_resource_proto = out.File
	file_resource_resource_proto_goTypes = nil
	file_resource_resource_proto_depIdxs = nil
}
