// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: resource/logic/admin_user.proto

package pb_resource_logic

import (
	resource "example/pb/resource"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdminUserShowAdminUsersTotalByFiltersWithSortersPaginationInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filters       []*resource.Filter     `protobuf:"bytes,1,rep,name=filters,proto3" json:"filters,omitempty"`
	Sorters       []*resource.Sorter     `protobuf:"bytes,2,rep,name=sorters,proto3" json:"sorters,omitempty"`
	Pagination    *resource.Pagination   `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUserShowAdminUsersTotalByFiltersWithSortersPaginationInput) Reset() {
	*x = AdminUserShowAdminUsersTotalByFiltersWithSortersPaginationInput{}
	mi := &file_resource_logic_admin_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUserShowAdminUsersTotalByFiltersWithSortersPaginationInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUserShowAdminUsersTotalByFiltersWithSortersPaginationInput) ProtoMessage() {}

func (x *AdminUserShowAdminUsersTotalByFiltersWithSortersPaginationInput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_logic_admin_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUserShowAdminUsersTotalByFiltersWithSortersPaginationInput.ProtoReflect.Descriptor instead.
func (*AdminUserShowAdminUsersTotalByFiltersWithSortersPaginationInput) Descriptor() ([]byte, []int) {
	return file_resource_logic_admin_user_proto_rawDescGZIP(), []int{0}
}

func (x *AdminUserShowAdminUsersTotalByFiltersWithSortersPaginationInput) GetFilters() []*resource.Filter {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *AdminUserShowAdminUsersTotalByFiltersWithSortersPaginationInput) GetSorters() []*resource.Sorter {
	if x != nil {
		return x.Sorters
	}
	return nil
}

func (x *AdminUserShowAdminUsersTotalByFiltersWithSortersPaginationInput) GetPagination() *resource.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type AdminUserShowAdminUsersTotalByFiltersWithSortersPaginationOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdminUsers    []*resource.AdminUser  `protobuf:"bytes,1,rep,name=admin_users,json=adminUsers,proto3" json:"admin_users,omitempty"`
	Total         uint64                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUserShowAdminUsersTotalByFiltersWithSortersPaginationOutput) Reset() {
	*x = AdminUserShowAdminUsersTotalByFiltersWithSortersPaginationOutput{}
	mi := &file_resource_logic_admin_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUserShowAdminUsersTotalByFiltersWithSortersPaginationOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUserShowAdminUsersTotalByFiltersWithSortersPaginationOutput) ProtoMessage() {}

func (x *AdminUserShowAdminUsersTotalByFiltersWithSortersPaginationOutput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_logic_admin_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUserShowAdminUsersTotalByFiltersWithSortersPaginationOutput.ProtoReflect.Descriptor instead.
func (*AdminUserShowAdminUsersTotalByFiltersWithSortersPaginationOutput) Descriptor() ([]byte, []int) {
	return file_resource_logic_admin_user_proto_rawDescGZIP(), []int{1}
}

func (x *AdminUserShowAdminUsersTotalByFiltersWithSortersPaginationOutput) GetAdminUsers() []*resource.AdminUser {
	if x != nil {
		return x.AdminUsers
	}
	return nil
}

func (x *AdminUserShowAdminUsersTotalByFiltersWithSortersPaginationOutput) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_resource_logic_admin_user_proto protoreflect.FileDescriptor

const file_resource_logic_admin_user_proto_rawDesc = "" +
	"\n" +
	"\x1fresource/logic/admin_user.proto\x12\x11pb.resource.logic\x1a\x15resource/common.proto\"\xd8\x01\n" +
	"?AdminUserShowAdminUsersTotalByFiltersWithSortersPaginationInput\x12-\n" +
	"\afilters\x18\x01 \x03(\v2\x13.pb.resource.FilterR\afilters\x12-\n" +
	"\asorters\x18\x02 \x03(\v2\x13.pb.resource.SorterR\asorters\x127\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2\x17.pb.resource.PaginationR\n" +
	"pagination\"\x91\x01\n" +
	"@AdminUserShowAdminUsersTotalByFiltersWithSortersPaginationOutput\x127\n" +
	"\vadmin_users\x18\x01 \x03(\v2\x16.pb.resource.AdminUserR\n" +
	"adminUsers\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x04R\x05total2\xef\x01\n" +
	"\x0eAdminUserLogic\x12\xdc\x01\n" +
	"1ShowAdminUsersTotalByFiltersWithSortersPagination\x12R.pb.resource.logic.AdminUserShowAdminUsersTotalByFiltersWithSortersPaginationInput\x1aS.pb.resource.logic.AdminUserShowAdminUsersTotalByFiltersWithSortersPaginationOutputB\x15Z\x13./pb_resource_logicb\x06proto3"

var (
	file_resource_logic_admin_user_proto_rawDescOnce sync.Once
	file_resource_logic_admin_user_proto_rawDescData []byte
)

func file_resource_logic_admin_user_proto_rawDescGZIP() []byte {
	file_resource_logic_admin_user_proto_rawDescOnce.Do(func() {
		file_resource_logic_admin_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_resource_logic_admin_user_proto_rawDesc), len(file_resource_logic_admin_user_proto_rawDesc)))
	})
	return file_resource_logic_admin_user_proto_rawDescData
}

var file_resource_logic_admin_user_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_resource_logic_admin_user_proto_goTypes = []any{
	(*AdminUserShowAdminUsersTotalByFiltersWithSortersPaginationInput)(nil),  // 0: pb.resource.logic.AdminUserShowAdminUsersTotalByFiltersWithSortersPaginationInput
	(*AdminUserShowAdminUsersTotalByFiltersWithSortersPaginationOutput)(nil), // 1: pb.resource.logic.AdminUserShowAdminUsersTotalByFiltersWithSortersPaginationOutput
	(*resource.Filter)(nil),     // 2: pb.resource.Filter
	(*resource.Sorter)(nil),     // 3: pb.resource.Sorter
	(*resource.Pagination)(nil), // 4: pb.resource.Pagination
	(*resource.AdminUser)(nil),  // 5: pb.resource.AdminUser
}
var file_resource_logic_admin_user_proto_depIdxs = []int32{
	2, // 0: pb.resource.logic.AdminUserShowAdminUsersTotalByFiltersWithSortersPaginationInput.filters:type_name -> pb.resource.Filter
	3, // 1: pb.resource.logic.AdminUserShowAdminUsersTotalByFiltersWithSortersPaginationInput.sorters:type_name -> pb.resource.Sorter
	4, // 2: pb.resource.logic.AdminUserShowAdminUsersTotalByFiltersWithSortersPaginationInput.pagination:type_name -> pb.resource.Pagination
	5, // 3: pb.resource.logic.AdminUserShowAdminUsersTotalByFiltersWithSortersPaginationOutput.admin_users:type_name -> pb.resource.AdminUser
	0, // 4: pb.resource.logic.AdminUserLogic.ShowAdminUsersTotalByFiltersWithSortersPagination:input_type -> pb.resource.logic.AdminUserShowAdminUsersTotalByFiltersWithSortersPaginationInput
	1, // 5: pb.resource.logic.AdminUserLogic.ShowAdminUsersTotalByFiltersWithSortersPagination:output_type -> pb.resource.logic.AdminUserShowAdminUsersTotalByFiltersWithSortersPaginationOutput
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_resource_logic_admin_user_proto_init() }
func file_resource_logic_admin_user_proto_init() {
	if File_resource_logic_admin_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_resource_logic_admin_user_proto_rawDesc), len(file_resource_logic_admin_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_resource_logic_admin_user_proto_goTypes,
		DependencyIndexes: file_resource_logic_admin_user_proto_depIdxs,
		MessageInfos:      file_resource_logic_admin_user_proto_msgTypes,
	}.Build()
	File_resource_logic_admin_user_proto = out.File
	file_resource_logic_admin_user_proto_goTypes = nil
	file_resource_logic_admin_user_proto_depIdxs = nil
}
