// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: resource/logic/admin_role.proto

package pb_resource_logic

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdminRoleLogic_AddAdminRole_FullMethodName = "/pb.resource.logic.AdminRoleLogic/AddAdminRole"
)

// AdminRoleLogicClient is the client API for AdminRoleLogic service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminRoleLogicClient interface {
	AddAdminRole(ctx context.Context, in *AdminRoleAddAdminRoleInput, opts ...grpc.CallOption) (*AdminRoleAddAdminRoleOutput, error)
}

type adminRoleLogicClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminRoleLogicClient(cc grpc.ClientConnInterface) AdminRoleLogicClient {
	return &adminRoleLogicClient{cc}
}

func (c *adminRoleLogicClient) AddAdminRole(ctx context.Context, in *AdminRoleAddAdminRoleInput, opts ...grpc.CallOption) (*AdminRoleAddAdminRoleOutput, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminRoleAddAdminRoleOutput)
	err := c.cc.Invoke(ctx, AdminRoleLogic_AddAdminRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminRoleLogicServer is the server API for AdminRoleLogic service.
// All implementations must embed UnimplementedAdminRoleLogicServer
// for forward compatibility.
type AdminRoleLogicServer interface {
	AddAdminRole(context.Context, *AdminRoleAddAdminRoleInput) (*AdminRoleAddAdminRoleOutput, error)
	mustEmbedUnimplementedAdminRoleLogicServer()
}

// UnimplementedAdminRoleLogicServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminRoleLogicServer struct{}

func (UnimplementedAdminRoleLogicServer) AddAdminRole(context.Context, *AdminRoleAddAdminRoleInput) (*AdminRoleAddAdminRoleOutput, error) {
	return nil, status.Error(codes.Unimplemented, "method AddAdminRole not implemented")
}
func (UnimplementedAdminRoleLogicServer) mustEmbedUnimplementedAdminRoleLogicServer() {}
func (UnimplementedAdminRoleLogicServer) testEmbeddedByValue()                        {}

// UnsafeAdminRoleLogicServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminRoleLogicServer will
// result in compilation errors.
type UnsafeAdminRoleLogicServer interface {
	mustEmbedUnimplementedAdminRoleLogicServer()
}

func RegisterAdminRoleLogicServer(s grpc.ServiceRegistrar, srv AdminRoleLogicServer) {
	// If the following call panics, it indicates UnimplementedAdminRoleLogicServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminRoleLogic_ServiceDesc, srv)
}

func _AdminRoleLogic_AddAdminRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminRoleAddAdminRoleInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminRoleLogicServer).AddAdminRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminRoleLogic_AddAdminRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminRoleLogicServer).AddAdminRole(ctx, req.(*AdminRoleAddAdminRoleInput))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminRoleLogic_ServiceDesc is the grpc.ServiceDesc for AdminRoleLogic service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminRoleLogic_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.resource.logic.AdminRoleLogic",
	HandlerType: (*AdminRoleLogicServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddAdminRole",
			Handler:    _AdminRoleLogic_AddAdminRole_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "resource/logic/admin_role.proto",
}
