// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: resource/logic/game_type.proto

package pb_resource_logic

import (
	resource "example/pb/resource"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GameTypeShowTreeInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameTypeShowTreeInput) Reset() {
	*x = GameTypeShowTreeInput{}
	mi := &file_resource_logic_game_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameTypeShowTreeInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameTypeShowTreeInput) ProtoMessage() {}

func (x *GameTypeShowTreeInput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_logic_game_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameTypeShowTreeInput.ProtoReflect.Descriptor instead.
func (*GameTypeShowTreeInput) Descriptor() ([]byte, []int) {
	return file_resource_logic_game_type_proto_rawDescGZIP(), []int{0}
}

type GameTypeShowTreeOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameTypes     []*resource.GameType   `protobuf:"bytes,1,rep,name=game_types,json=gameTypes,proto3" json:"game_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameTypeShowTreeOutput) Reset() {
	*x = GameTypeShowTreeOutput{}
	mi := &file_resource_logic_game_type_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameTypeShowTreeOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameTypeShowTreeOutput) ProtoMessage() {}

func (x *GameTypeShowTreeOutput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_logic_game_type_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameTypeShowTreeOutput.ProtoReflect.Descriptor instead.
func (*GameTypeShowTreeOutput) Descriptor() ([]byte, []int) {
	return file_resource_logic_game_type_proto_rawDescGZIP(), []int{1}
}

func (x *GameTypeShowTreeOutput) GetGameTypes() []*resource.GameType {
	if x != nil {
		return x.GameTypes
	}
	return nil
}

type GameTypeShowGameTypesTotalByFiltersWithSortersPaginationInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filters       []*resource.Filter     `protobuf:"bytes,1,rep,name=filters,proto3" json:"filters,omitempty"`
	Sorters       []*resource.Sorter     `protobuf:"bytes,2,rep,name=sorters,proto3" json:"sorters,omitempty"`
	Pagination    *resource.Pagination   `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameTypeShowGameTypesTotalByFiltersWithSortersPaginationInput) Reset() {
	*x = GameTypeShowGameTypesTotalByFiltersWithSortersPaginationInput{}
	mi := &file_resource_logic_game_type_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameTypeShowGameTypesTotalByFiltersWithSortersPaginationInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameTypeShowGameTypesTotalByFiltersWithSortersPaginationInput) ProtoMessage() {}

func (x *GameTypeShowGameTypesTotalByFiltersWithSortersPaginationInput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_logic_game_type_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameTypeShowGameTypesTotalByFiltersWithSortersPaginationInput.ProtoReflect.Descriptor instead.
func (*GameTypeShowGameTypesTotalByFiltersWithSortersPaginationInput) Descriptor() ([]byte, []int) {
	return file_resource_logic_game_type_proto_rawDescGZIP(), []int{2}
}

func (x *GameTypeShowGameTypesTotalByFiltersWithSortersPaginationInput) GetFilters() []*resource.Filter {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *GameTypeShowGameTypesTotalByFiltersWithSortersPaginationInput) GetSorters() []*resource.Sorter {
	if x != nil {
		return x.Sorters
	}
	return nil
}

func (x *GameTypeShowGameTypesTotalByFiltersWithSortersPaginationInput) GetPagination() *resource.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type GameTypeShowGameTypesTotalByFiltersWithSortersPaginationOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameTypes     []*resource.GameType   `protobuf:"bytes,1,rep,name=game_types,json=gameTypes,proto3" json:"game_types,omitempty"`
	Total         uint64                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameTypeShowGameTypesTotalByFiltersWithSortersPaginationOutput) Reset() {
	*x = GameTypeShowGameTypesTotalByFiltersWithSortersPaginationOutput{}
	mi := &file_resource_logic_game_type_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameTypeShowGameTypesTotalByFiltersWithSortersPaginationOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameTypeShowGameTypesTotalByFiltersWithSortersPaginationOutput) ProtoMessage() {}

func (x *GameTypeShowGameTypesTotalByFiltersWithSortersPaginationOutput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_logic_game_type_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameTypeShowGameTypesTotalByFiltersWithSortersPaginationOutput.ProtoReflect.Descriptor instead.
func (*GameTypeShowGameTypesTotalByFiltersWithSortersPaginationOutput) Descriptor() ([]byte, []int) {
	return file_resource_logic_game_type_proto_rawDescGZIP(), []int{3}
}

func (x *GameTypeShowGameTypesTotalByFiltersWithSortersPaginationOutput) GetGameTypes() []*resource.GameType {
	if x != nil {
		return x.GameTypes
	}
	return nil
}

func (x *GameTypeShowGameTypesTotalByFiltersWithSortersPaginationOutput) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_resource_logic_game_type_proto protoreflect.FileDescriptor

const file_resource_logic_game_type_proto_rawDesc = "" +
	"\n" +
	"\x1eresource/logic/game_type.proto\x12\x11pb.resource.logic\x1a\x15resource/common.proto\"\x17\n" +
	"\x15GameTypeShowTreeInput\"N\n" +
	"\x16GameTypeShowTreeOutput\x124\n" +
	"\n" +
	"game_types\x18\x01 \x03(\v2\x15.pb.resource.GameTypeR\tgameTypes\"\xd6\x01\n" +
	"=GameTypeShowGameTypesTotalByFiltersWithSortersPaginationInput\x12-\n" +
	"\afilters\x18\x01 \x03(\v2\x13.pb.resource.FilterR\afilters\x12-\n" +
	"\asorters\x18\x02 \x03(\v2\x13.pb.resource.SorterR\asorters\x127\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2\x17.pb.resource.PaginationR\n" +
	"pagination\"\x8c\x01\n" +
	">GameTypeShowGameTypesTotalByFiltersWithSortersPaginationOutput\x124\n" +
	"\n" +
	"game_types\x18\x01 \x03(\v2\x15.pb.resource.GameTypeR\tgameTypes\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x04R\x05total2\xca\x02\n" +
	"\rGameTypeLogic\x12_\n" +
	"\bShowTree\x12(.pb.resource.logic.GameTypeShowTreeInput\x1a).pb.resource.logic.GameTypeShowTreeOutput\x12\xd7\x01\n" +
	"0ShowGameTypesTotalByFiltersWithSortersPagination\x12P.pb.resource.logic.GameTypeShowGameTypesTotalByFiltersWithSortersPaginationInput\x1aQ.pb.resource.logic.GameTypeShowGameTypesTotalByFiltersWithSortersPaginationOutputB\x15Z\x13./pb_resource_logicb\x06proto3"

var (
	file_resource_logic_game_type_proto_rawDescOnce sync.Once
	file_resource_logic_game_type_proto_rawDescData []byte
)

func file_resource_logic_game_type_proto_rawDescGZIP() []byte {
	file_resource_logic_game_type_proto_rawDescOnce.Do(func() {
		file_resource_logic_game_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_resource_logic_game_type_proto_rawDesc), len(file_resource_logic_game_type_proto_rawDesc)))
	})
	return file_resource_logic_game_type_proto_rawDescData
}

var file_resource_logic_game_type_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_resource_logic_game_type_proto_goTypes = []any{
	(*GameTypeShowTreeInput)(nil),                                          // 0: pb.resource.logic.GameTypeShowTreeInput
	(*GameTypeShowTreeOutput)(nil),                                         // 1: pb.resource.logic.GameTypeShowTreeOutput
	(*GameTypeShowGameTypesTotalByFiltersWithSortersPaginationInput)(nil),  // 2: pb.resource.logic.GameTypeShowGameTypesTotalByFiltersWithSortersPaginationInput
	(*GameTypeShowGameTypesTotalByFiltersWithSortersPaginationOutput)(nil), // 3: pb.resource.logic.GameTypeShowGameTypesTotalByFiltersWithSortersPaginationOutput
	(*resource.GameType)(nil),                                              // 4: pb.resource.GameType
	(*resource.Filter)(nil),                                                // 5: pb.resource.Filter
	(*resource.Sorter)(nil),                                                // 6: pb.resource.Sorter
	(*resource.Pagination)(nil),                                            // 7: pb.resource.Pagination
}
var file_resource_logic_game_type_proto_depIdxs = []int32{
	4, // 0: pb.resource.logic.GameTypeShowTreeOutput.game_types:type_name -> pb.resource.GameType
	5, // 1: pb.resource.logic.GameTypeShowGameTypesTotalByFiltersWithSortersPaginationInput.filters:type_name -> pb.resource.Filter
	6, // 2: pb.resource.logic.GameTypeShowGameTypesTotalByFiltersWithSortersPaginationInput.sorters:type_name -> pb.resource.Sorter
	7, // 3: pb.resource.logic.GameTypeShowGameTypesTotalByFiltersWithSortersPaginationInput.pagination:type_name -> pb.resource.Pagination
	4, // 4: pb.resource.logic.GameTypeShowGameTypesTotalByFiltersWithSortersPaginationOutput.game_types:type_name -> pb.resource.GameType
	0, // 5: pb.resource.logic.GameTypeLogic.ShowTree:input_type -> pb.resource.logic.GameTypeShowTreeInput
	2, // 6: pb.resource.logic.GameTypeLogic.ShowGameTypesTotalByFiltersWithSortersPagination:input_type -> pb.resource.logic.GameTypeShowGameTypesTotalByFiltersWithSortersPaginationInput
	1, // 7: pb.resource.logic.GameTypeLogic.ShowTree:output_type -> pb.resource.logic.GameTypeShowTreeOutput
	3, // 8: pb.resource.logic.GameTypeLogic.ShowGameTypesTotalByFiltersWithSortersPagination:output_type -> pb.resource.logic.GameTypeShowGameTypesTotalByFiltersWithSortersPaginationOutput
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_resource_logic_game_type_proto_init() }
func file_resource_logic_game_type_proto_init() {
	if File_resource_logic_game_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_resource_logic_game_type_proto_rawDesc), len(file_resource_logic_game_type_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_resource_logic_game_type_proto_goTypes,
		DependencyIndexes: file_resource_logic_game_type_proto_depIdxs,
		MessageInfos:      file_resource_logic_game_type_proto_msgTypes,
	}.Build()
	File_resource_logic_game_type_proto = out.File
	file_resource_logic_game_type_proto_goTypes = nil
	file_resource_logic_game_type_proto_depIdxs = nil
}
