// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: resource/logic/game_type.proto

package pb_resource_logic

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GameTypeLogic_ShowTree_FullMethodName = "/pb.resource.logic.GameTypeLogic/ShowTree"
)

// GameTypeLogicClient is the client API for GameTypeLogic service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GameTypeLogicClient interface {
	ShowTree(ctx context.Context, in *GameTypeShowTreeInput, opts ...grpc.CallOption) (*GameTypeShowTreeOutput, error)
}

type gameTypeLogicClient struct {
	cc grpc.ClientConnInterface
}

func NewGameTypeLogicClient(cc grpc.ClientConnInterface) GameTypeLogicClient {
	return &gameTypeLogicClient{cc}
}

func (c *gameTypeLogicClient) ShowTree(ctx context.Context, in *GameTypeShowTreeInput, opts ...grpc.CallOption) (*GameTypeShowTreeOutput, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GameTypeShowTreeOutput)
	err := c.cc.Invoke(ctx, GameTypeLogic_ShowTree_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameTypeLogicServer is the server API for GameTypeLogic service.
// All implementations must embed UnimplementedGameTypeLogicServer
// for forward compatibility.
type GameTypeLogicServer interface {
	ShowTree(context.Context, *GameTypeShowTreeInput) (*GameTypeShowTreeOutput, error)
	mustEmbedUnimplementedGameTypeLogicServer()
}

// UnimplementedGameTypeLogicServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGameTypeLogicServer struct{}

func (UnimplementedGameTypeLogicServer) ShowTree(context.Context, *GameTypeShowTreeInput) (*GameTypeShowTreeOutput, error) {
	return nil, status.Error(codes.Unimplemented, "method ShowTree not implemented")
}
func (UnimplementedGameTypeLogicServer) mustEmbedUnimplementedGameTypeLogicServer() {}
func (UnimplementedGameTypeLogicServer) testEmbeddedByValue()                       {}

// UnsafeGameTypeLogicServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameTypeLogicServer will
// result in compilation errors.
type UnsafeGameTypeLogicServer interface {
	mustEmbedUnimplementedGameTypeLogicServer()
}

func RegisterGameTypeLogicServer(s grpc.ServiceRegistrar, srv GameTypeLogicServer) {
	// If the following call panics, it indicates UnimplementedGameTypeLogicServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GameTypeLogic_ServiceDesc, srv)
}

func _GameTypeLogic_ShowTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GameTypeShowTreeInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameTypeLogicServer).ShowTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameTypeLogic_ShowTree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameTypeLogicServer).ShowTree(ctx, req.(*GameTypeShowTreeInput))
	}
	return interceptor(ctx, in, info, handler)
}

// GameTypeLogic_ServiceDesc is the grpc.ServiceDesc for GameTypeLogic service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GameTypeLogic_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.resource.logic.GameTypeLogic",
	HandlerType: (*GameTypeLogicServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ShowTree",
			Handler:    _GameTypeLogic_ShowTree_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "resource/logic/game_type.proto",
}
