// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: resource/logic/game.proto

package pb_resource_logic

import (
	resource "example/pb/resource"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GameShowGamesTotalByFiltersWithSortersPaginationInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filters       []*resource.Filter     `protobuf:"bytes,1,rep,name=filters,proto3" json:"filters,omitempty"`
	Sorters       []*resource.Sorter     `protobuf:"bytes,2,rep,name=sorters,proto3" json:"sorters,omitempty"`
	Pagination    *resource.Pagination   `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameShowGamesTotalByFiltersWithSortersPaginationInput) Reset() {
	*x = GameShowGamesTotalByFiltersWithSortersPaginationInput{}
	mi := &file_resource_logic_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameShowGamesTotalByFiltersWithSortersPaginationInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameShowGamesTotalByFiltersWithSortersPaginationInput) ProtoMessage() {}

func (x *GameShowGamesTotalByFiltersWithSortersPaginationInput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_logic_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameShowGamesTotalByFiltersWithSortersPaginationInput.ProtoReflect.Descriptor instead.
func (*GameShowGamesTotalByFiltersWithSortersPaginationInput) Descriptor() ([]byte, []int) {
	return file_resource_logic_game_proto_rawDescGZIP(), []int{0}
}

func (x *GameShowGamesTotalByFiltersWithSortersPaginationInput) GetFilters() []*resource.Filter {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *GameShowGamesTotalByFiltersWithSortersPaginationInput) GetSorters() []*resource.Sorter {
	if x != nil {
		return x.Sorters
	}
	return nil
}

func (x *GameShowGamesTotalByFiltersWithSortersPaginationInput) GetPagination() *resource.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type GameShowGamesTotalByFiltersWithSortersPaginationOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Games         []*resource.Game       `protobuf:"bytes,1,rep,name=games,proto3" json:"games,omitempty"`
	Total         uint64                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameShowGamesTotalByFiltersWithSortersPaginationOutput) Reset() {
	*x = GameShowGamesTotalByFiltersWithSortersPaginationOutput{}
	mi := &file_resource_logic_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameShowGamesTotalByFiltersWithSortersPaginationOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameShowGamesTotalByFiltersWithSortersPaginationOutput) ProtoMessage() {}

func (x *GameShowGamesTotalByFiltersWithSortersPaginationOutput) ProtoReflect() protoreflect.Message {
	mi := &file_resource_logic_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameShowGamesTotalByFiltersWithSortersPaginationOutput.ProtoReflect.Descriptor instead.
func (*GameShowGamesTotalByFiltersWithSortersPaginationOutput) Descriptor() ([]byte, []int) {
	return file_resource_logic_game_proto_rawDescGZIP(), []int{1}
}

func (x *GameShowGamesTotalByFiltersWithSortersPaginationOutput) GetGames() []*resource.Game {
	if x != nil {
		return x.Games
	}
	return nil
}

func (x *GameShowGamesTotalByFiltersWithSortersPaginationOutput) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_resource_logic_game_proto protoreflect.FileDescriptor

const file_resource_logic_game_proto_rawDesc = "" +
	"\n" +
	"\x19resource/logic/game.proto\x12\x11pb.resource.logic\x1a\x17resource/resource.proto\"\xce\x01\n" +
	"5GameShowGamesTotalByFiltersWithSortersPaginationInput\x12-\n" +
	"\afilters\x18\x01 \x03(\v2\x13.pb.resource.FilterR\afilters\x12-\n" +
	"\asorters\x18\x02 \x03(\v2\x13.pb.resource.SorterR\asorters\x127\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2\x17.pb.resource.PaginationR\n" +
	"pagination\"w\n" +
	"6GameShowGamesTotalByFiltersWithSortersPaginationOutput\x12'\n" +
	"\x05games\x18\x01 \x03(\v2\x11.pb.resource.GameR\x05games\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x04R\x05total2\xd1\x01\n" +
	"\tGameLogic\x12\xc3\x01\n" +
	",ShowGamesTotalByFiltersWithSortersPagination\x12H.pb.resource.logic.GameShowGamesTotalByFiltersWithSortersPaginationInput\x1aI.pb.resource.logic.GameShowGamesTotalByFiltersWithSortersPaginationOutputB\x15Z\x13./pb_resource_logicb\x06proto3"

var (
	file_resource_logic_game_proto_rawDescOnce sync.Once
	file_resource_logic_game_proto_rawDescData []byte
)

func file_resource_logic_game_proto_rawDescGZIP() []byte {
	file_resource_logic_game_proto_rawDescOnce.Do(func() {
		file_resource_logic_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_resource_logic_game_proto_rawDesc), len(file_resource_logic_game_proto_rawDesc)))
	})
	return file_resource_logic_game_proto_rawDescData
}

var file_resource_logic_game_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_resource_logic_game_proto_goTypes = []any{
	(*GameShowGamesTotalByFiltersWithSortersPaginationInput)(nil),  // 0: pb.resource.logic.GameShowGamesTotalByFiltersWithSortersPaginationInput
	(*GameShowGamesTotalByFiltersWithSortersPaginationOutput)(nil), // 1: pb.resource.logic.GameShowGamesTotalByFiltersWithSortersPaginationOutput
	(*resource.Filter)(nil),     // 2: pb.resource.Filter
	(*resource.Sorter)(nil),     // 3: pb.resource.Sorter
	(*resource.Pagination)(nil), // 4: pb.resource.Pagination
	(*resource.Game)(nil),       // 5: pb.resource.Game
}
var file_resource_logic_game_proto_depIdxs = []int32{
	2, // 0: pb.resource.logic.GameShowGamesTotalByFiltersWithSortersPaginationInput.filters:type_name -> pb.resource.Filter
	3, // 1: pb.resource.logic.GameShowGamesTotalByFiltersWithSortersPaginationInput.sorters:type_name -> pb.resource.Sorter
	4, // 2: pb.resource.logic.GameShowGamesTotalByFiltersWithSortersPaginationInput.pagination:type_name -> pb.resource.Pagination
	5, // 3: pb.resource.logic.GameShowGamesTotalByFiltersWithSortersPaginationOutput.games:type_name -> pb.resource.Game
	0, // 4: pb.resource.logic.GameLogic.ShowGamesTotalByFiltersWithSortersPagination:input_type -> pb.resource.logic.GameShowGamesTotalByFiltersWithSortersPaginationInput
	1, // 5: pb.resource.logic.GameLogic.ShowGamesTotalByFiltersWithSortersPagination:output_type -> pb.resource.logic.GameShowGamesTotalByFiltersWithSortersPaginationOutput
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_resource_logic_game_proto_init() }
func file_resource_logic_game_proto_init() {
	if File_resource_logic_game_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_resource_logic_game_proto_rawDesc), len(file_resource_logic_game_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_resource_logic_game_proto_goTypes,
		DependencyIndexes: file_resource_logic_game_proto_depIdxs,
		MessageInfos:      file_resource_logic_game_proto_msgTypes,
	}.Build()
	File_resource_logic_game_proto = out.File
	file_resource_logic_game_proto_goTypes = nil
	file_resource_logic_game_proto_depIdxs = nil
}
