// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: source/announcement/lottery.proto

package pb_source_announcement

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LotteryController_Watch_FullMethodName = "/pb.source.announcement.LotteryController/Watch"
)

// LotteryControllerClient is the client API for LotteryController service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LotteryControllerClient interface {
	Watch(ctx context.Context, in *LotteryWatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LotteryWatchResponse], error)
}

type lotteryControllerClient struct {
	cc grpc.ClientConnInterface
}

func NewLotteryControllerClient(cc grpc.ClientConnInterface) LotteryControllerClient {
	return &lotteryControllerClient{cc}
}

func (c *lotteryControllerClient) Watch(ctx context.Context, in *LotteryWatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LotteryWatchResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LotteryController_ServiceDesc.Streams[0], LotteryController_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LotteryWatchRequest, LotteryWatchResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LotteryController_WatchClient = grpc.ServerStreamingClient[LotteryWatchResponse]

// LotteryControllerServer is the server API for LotteryController service.
// All implementations must embed UnimplementedLotteryControllerServer
// for forward compatibility.
type LotteryControllerServer interface {
	Watch(*LotteryWatchRequest, grpc.ServerStreamingServer[LotteryWatchResponse]) error
	mustEmbedUnimplementedLotteryControllerServer()
}

// UnimplementedLotteryControllerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLotteryControllerServer struct{}

func (UnimplementedLotteryControllerServer) Watch(*LotteryWatchRequest, grpc.ServerStreamingServer[LotteryWatchResponse]) error {
	return status.Error(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedLotteryControllerServer) mustEmbedUnimplementedLotteryControllerServer() {}
func (UnimplementedLotteryControllerServer) testEmbeddedByValue()                           {}

// UnsafeLotteryControllerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LotteryControllerServer will
// result in compilation errors.
type UnsafeLotteryControllerServer interface {
	mustEmbedUnimplementedLotteryControllerServer()
}

func RegisterLotteryControllerServer(s grpc.ServiceRegistrar, srv LotteryControllerServer) {
	// If the following call panics, it indicates UnimplementedLotteryControllerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LotteryController_ServiceDesc, srv)
}

func _LotteryController_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LotteryWatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LotteryControllerServer).Watch(m, &grpc.GenericServerStream[LotteryWatchRequest, LotteryWatchResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LotteryController_WatchServer = grpc.ServerStreamingServer[LotteryWatchResponse]

// LotteryController_ServiceDesc is the grpc.ServiceDesc for LotteryController service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LotteryController_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.source.announcement.LotteryController",
	HandlerType: (*LotteryControllerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _LotteryController_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "source/announcement/lottery.proto",
}
