facade:        # 面門 服務
  hosts: ["127.0.0.1"]
  ports: ["3001"]
  timeout: 10000

resource:        # 數據服務
  hosts: ["127.0.0.1", "127.0.0.1", "127.0.0.1", "127.0.0.1"]
  ports: ["7002", "7002", "7002", "7002"]
  user: 'resource'
  password: '!Scg]4"?VYY`mzFOV(Nu247ou6O5E@jB'
  timeout: 10000

source:        # 數據服務
  hosts: ["127.0.0.1", "127.0.0.1", "127.0.0.1", "127.0.0.1"]
  ports: ["2008", "2008", "2008", "2008"]
  weights: [100, 1, 1, 1]
  timeout: 10000

tcp:        # 自家 tcp 服務
  hosts: ["127.0.0.1"]
  ports: ["4007"]
  timeout: 10000
  pool: 24

# services 是服務端要配置什麼密碼
# clients 是客戶端連線時候要配置什麼密碼