host: '127.0.0.1'
hosts: ["127.0.0.1", "127.0.0.1", "127.0.0.1", "127.0.0.1", "127.0.0.1", "127.0.0.1"]
username: "backend"
password: 'redis_pass_cli'
port: '6379'
ports: ["6379", "6379", "6379", "6379", "6379", "6379"]
db: 0
cluster: false
timeout: 10000


# REDIS 隊列 類型 1:  pub/ sub (廣播隊列)  一個生產者 多人訂閱都收到
# REDIS 隊列 類型 2:  list (搶佔隊列) 一個生產者 多人只有一個人搶到
# REDIS 隊列 類型 1:  event Streams  (分組隊列)  一個生產者 對 N個組是廣播，一個組內是搶佔
