// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: facade/game/user.proto

package pb_facade_game

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_facade_game_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_facade_game_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_facade_game_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UserCreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCreateUserRequest) Reset() {
	*x = UserCreateUserRequest{}
	mi := &file_facade_game_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCreateUserRequest) ProtoMessage() {}

func (x *UserCreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_facade_game_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCreateUserRequest.ProtoReflect.Descriptor instead.
func (*UserCreateUserRequest) Descriptor() ([]byte, []int) {
	return file_facade_game_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserCreateUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UserCreateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCreateUserResponse) Reset() {
	*x = UserCreateUserResponse{}
	mi := &file_facade_game_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCreateUserResponse) ProtoMessage() {}

func (x *UserCreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_facade_game_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCreateUserResponse.ProtoReflect.Descriptor instead.
func (*UserCreateUserResponse) Descriptor() ([]byte, []int) {
	return file_facade_game_user_proto_rawDescGZIP(), []int{2}
}

func (x *UserCreateUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type UserGetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserGetUserRequest) Reset() {
	*x = UserGetUserRequest{}
	mi := &file_facade_game_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserGetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGetUserRequest) ProtoMessage() {}

func (x *UserGetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_facade_game_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGetUserRequest.ProtoReflect.Descriptor instead.
func (*UserGetUserRequest) Descriptor() ([]byte, []int) {
	return file_facade_game_user_proto_rawDescGZIP(), []int{3}
}

func (x *UserGetUserRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UserGetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserGetUserResponse) Reset() {
	*x = UserGetUserResponse{}
	mi := &file_facade_game_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserGetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGetUserResponse) ProtoMessage() {}

func (x *UserGetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_facade_game_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGetUserResponse.ProtoReflect.Descriptor instead.
func (*UserGetUserResponse) Descriptor() ([]byte, []int) {
	return file_facade_game_user_proto_rawDescGZIP(), []int{4}
}

func (x *UserGetUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

var File_facade_game_user_proto protoreflect.FileDescriptor

const file_facade_game_user_proto_rawDesc = "" +
	"\n" +
	"\x16facade/game/user.proto\x12\x0epb.facade.game\"*\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"+\n" +
	"\x15UserCreateUserRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"B\n" +
	"\x16UserCreateUserResponse\x12(\n" +
	"\x04user\x18\x01 \x01(\v2\x14.pb.facade.game.UserR\x04user\"$\n" +
	"\x12UserGetUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"?\n" +
	"\x13UserGetUserResponse\x12(\n" +
	"\x04user\x18\x01 \x01(\v2\x14.pb.facade.game.UserR\x04user2\xc1\x01\n" +
	"\x0eUserController\x12[\n" +
	"\n" +
	"CreateUser\x12%.pb.facade.game.UserCreateUserRequest\x1a&.pb.facade.game.UserCreateUserResponse\x12R\n" +
	"\aGetUser\x12\".pb.facade.game.UserGetUserRequest\x1a#.pb.facade.game.UserGetUserResponseB\x12Z\x10./pb_facade_gameb\x06proto3"

var (
	file_facade_game_user_proto_rawDescOnce sync.Once
	file_facade_game_user_proto_rawDescData []byte
)

func file_facade_game_user_proto_rawDescGZIP() []byte {
	file_facade_game_user_proto_rawDescOnce.Do(func() {
		file_facade_game_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_facade_game_user_proto_rawDesc), len(file_facade_game_user_proto_rawDesc)))
	})
	return file_facade_game_user_proto_rawDescData
}

var file_facade_game_user_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_facade_game_user_proto_goTypes = []any{
	(*User)(nil),                   // 0: pb.facade.game.User
	(*UserCreateUserRequest)(nil),  // 1: pb.facade.game.UserCreateUserRequest
	(*UserCreateUserResponse)(nil), // 2: pb.facade.game.UserCreateUserResponse
	(*UserGetUserRequest)(nil),     // 3: pb.facade.game.UserGetUserRequest
	(*UserGetUserResponse)(nil),    // 4: pb.facade.game.UserGetUserResponse
}
var file_facade_game_user_proto_depIdxs = []int32{
	0, // 0: pb.facade.game.UserCreateUserResponse.user:type_name -> pb.facade.game.User
	0, // 1: pb.facade.game.UserGetUserResponse.user:type_name -> pb.facade.game.User
	1, // 2: pb.facade.game.UserController.CreateUser:input_type -> pb.facade.game.UserCreateUserRequest
	3, // 3: pb.facade.game.UserController.GetUser:input_type -> pb.facade.game.UserGetUserRequest
	2, // 4: pb.facade.game.UserController.CreateUser:output_type -> pb.facade.game.UserCreateUserResponse
	4, // 5: pb.facade.game.UserController.GetUser:output_type -> pb.facade.game.UserGetUserResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_facade_game_user_proto_init() }
func file_facade_game_user_proto_init() {
	if File_facade_game_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_facade_game_user_proto_rawDesc), len(file_facade_game_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_facade_game_user_proto_goTypes,
		DependencyIndexes: file_facade_game_user_proto_depIdxs,
		MessageInfos:      file_facade_game_user_proto_msgTypes,
	}.Build()
	File_facade_game_user_proto = out.File
	file_facade_game_user_proto_goTypes = nil
	file_facade_game_user_proto_depIdxs = nil
}
