// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: facade/table/scanner.proto

package pb_facade_table

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScannerReportOneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScannerReportOneRequest) Reset() {
	*x = ScannerReportOneRequest{}
	mi := &file_facade_table_scanner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScannerReportOneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScannerReportOneRequest) ProtoMessage() {}

func (x *ScannerReportOneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_facade_table_scanner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScannerReportOneRequest.ProtoReflect.Descriptor instead.
func (*ScannerReportOneRequest) Descriptor() ([]byte, []int) {
	return file_facade_table_scanner_proto_rawDescGZIP(), []int{0}
}

func (x *ScannerReportOneRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ScannerReportOneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScannerReportOneResponse) Reset() {
	*x = ScannerReportOneResponse{}
	mi := &file_facade_table_scanner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScannerReportOneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScannerReportOneResponse) ProtoMessage() {}

func (x *ScannerReportOneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_facade_table_scanner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScannerReportOneResponse.ProtoReflect.Descriptor instead.
func (*ScannerReportOneResponse) Descriptor() ([]byte, []int) {
	return file_facade_table_scanner_proto_rawDescGZIP(), []int{1}
}

func (x *ScannerReportOneResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_facade_table_scanner_proto protoreflect.FileDescriptor

const file_facade_table_scanner_proto_rawDesc = "" +
	"\n" +
	"\x1afacade/table/scanner.proto\x12\x0fpb.facade.table\"-\n" +
	"\x17ScannerReportOneRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\".\n" +
	"\x18ScannerReportOneResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name2u\n" +
	"\x11ScannerController\x12`\n" +
	"\tReportOne\x12(.pb.facade.table.ScannerReportOneRequest\x1a).pb.facade.table.ScannerReportOneResponseB\x13Z\x11./pb_facade_tableb\x06proto3"

var (
	file_facade_table_scanner_proto_rawDescOnce sync.Once
	file_facade_table_scanner_proto_rawDescData []byte
)

func file_facade_table_scanner_proto_rawDescGZIP() []byte {
	file_facade_table_scanner_proto_rawDescOnce.Do(func() {
		file_facade_table_scanner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_facade_table_scanner_proto_rawDesc), len(file_facade_table_scanner_proto_rawDesc)))
	})
	return file_facade_table_scanner_proto_rawDescData
}

var file_facade_table_scanner_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_facade_table_scanner_proto_goTypes = []any{
	(*ScannerReportOneRequest)(nil),  // 0: pb.facade.table.ScannerReportOneRequest
	(*ScannerReportOneResponse)(nil), // 1: pb.facade.table.ScannerReportOneResponse
}
var file_facade_table_scanner_proto_depIdxs = []int32{
	0, // 0: pb.facade.table.ScannerController.ReportOne:input_type -> pb.facade.table.ScannerReportOneRequest
	1, // 1: pb.facade.table.ScannerController.ReportOne:output_type -> pb.facade.table.ScannerReportOneResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_facade_table_scanner_proto_init() }
func file_facade_table_scanner_proto_init() {
	if File_facade_table_scanner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_facade_table_scanner_proto_rawDesc), len(file_facade_table_scanner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_facade_table_scanner_proto_goTypes,
		DependencyIndexes: file_facade_table_scanner_proto_depIdxs,
		MessageInfos:      file_facade_table_scanner_proto_msgTypes,
	}.Build()
	File_facade_table_scanner_proto = out.File
	file_facade_table_scanner_proto_goTypes = nil
	file_facade_table_scanner_proto_depIdxs = nil
}
